"""Platform knowledge base — 40+ platform configurations for signup automation.

Each entry maps directly to a PlatformConfig dataclass. Data is curated from
real platform signup flows — no AI calls, just structured knowledge.
"""

from openclaw.models import (
    CaptchaType,
    FieldConfig,
    PlatformCategory,
    PlatformConfig,
    SignupComplexity,
)

# All platforms indexed by platform_id
PLATFORMS: dict[str, PlatformConfig] = {}


def _register(p: PlatformConfig) -> PlatformConfig:
    """Register a platform config in the global registry."""
    PLATFORMS[p.platform_id] = p
    return p


def get_platform(platform_id: str) -> PlatformConfig | None:
    """Look up a platform by its ID."""
    return PLATFORMS.get(platform_id)


def get_platforms_by_category(category: PlatformCategory) -> list[PlatformConfig]:
    """Return all platforms in a given category."""
    return [p for p in PLATFORMS.values() if p.category == category]


def get_all_platform_ids() -> list[str]:
    """Return all registered platform IDs."""
    return list(PLATFORMS.keys())


def get_platforms_by_complexity(
    complexity: SignupComplexity,
) -> list[PlatformConfig]:
    """Return all platforms matching a given signup complexity."""
    return [p for p in PLATFORMS.values() if p.complexity == complexity]


def get_easy_wins() -> list[PlatformConfig]:
    """Return platforms sorted by effort-to-value ratio (best first)."""
    scored = []
    for p in PLATFORMS.values():
        effort = p.estimated_signup_minutes
        value = p.monetization_potential + p.audience_size + p.seo_value
        ratio = value / max(effort, 1)
        scored.append((ratio, p))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [p for _, p in scored]


# ─────────────────────────────────────────────────────────────────────────────
# AI Marketplaces
# ─────────────────────────────────────────────────────────────────────────────

_register(PlatformConfig(
    platform_id="gpt_store",
    name="OpenAI GPT Store",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://chat.openai.com/auth/login",
    login_url="https://chat.openai.com/auth/login",
    profile_url_template="https://chat.openai.com/g/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google", "microsoft", "apple"],
    username_max_length=50,
    bio_max_length=300,
    tagline_max_length=0,
    description_max_length=8000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=0,
    complexity=SignupComplexity.COMPLEX,
    monetization_potential=9,
    audience_size=10,
    seo_value=8,
    estimated_signup_minutes=10,
    known_quirks=[
        "Requires ChatGPT Plus subscription to publish GPTs",
        "OAuth signup is the primary flow; email signup secondary",
        "GPT builder is separate from account signup",
        "Profile is per-GPT, not per-account",
        "Revenue sharing program requires separate application",
    ],
    notes="Largest AI marketplace. GPTs are published through the builder UI after account creation.",
))

_register(PlatformConfig(
    platform_id="clawhub",
    name="ClawHub",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://clawhub.com/signup",
    login_url="https://clawhub.com/login",
    profile_url_template="https://clawhub.com/creators/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="display_name", selector='input[name="displayName"]', required=False, max_length=50),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=100,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=5,
    audience_size=4,
    seo_value=5,
    estimated_signup_minutes=3,
    known_quirks=[
        "New platform, smaller audience but growing fast",
        "Supports markdown in descriptions",
    ],
    notes="Emerging AI agent marketplace with simple onboarding.",
))

_register(PlatformConfig(
    platform_id="crusty_claws",
    name="Crusty Claws",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://crustyclaws.com/register",
    login_url="https://crustyclaws.com/login",
    profile_url_template="https://crustyclaws.com/u/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=25),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=25,
    bio_max_length=300,
    tagline_max_length=80,
    description_max_length=1500,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=3,
    audience_size=3,
    seo_value=4,
    estimated_signup_minutes=2,
    known_quirks=[
        "Niche community focused on experimental AI tools",
        "Username cannot be changed after signup",
    ],
    notes="Small indie AI tool marketplace.",
))

_register(PlatformConfig(
    platform_id="skills_mp",
    name="Skills Marketplace",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://skillsmarketplace.ai/signup",
    login_url="https://skillsmarketplace.ai/login",
    profile_url_template="https://skillsmarketplace.ai/sellers/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="full_name", selector='input[name="fullName"]', required=True, max_length=60),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=120,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=5,
    audience_size=4,
    seo_value=5,
    estimated_signup_minutes=3,
    known_quirks=[
        "Requires seller application after signup (auto-approved within 24h)",
        "Supports custom storefront themes",
    ],
    notes="AI skills and agent marketplace with seller storefronts.",
))

_register(PlatformConfig(
    platform_id="skills_llm",
    name="Skills.LLM",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://skills.llm.dev/register",
    login_url="https://skills.llm.dev/login",
    profile_url_template="https://skills.llm.dev/@{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="handle"]', required=True, max_length=20),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=20,
    bio_max_length=250,
    tagline_max_length=0,
    description_max_length=1000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=4,
    audience_size=3,
    seo_value=4,
    estimated_signup_minutes=2,
    known_quirks=[
        "Handle uses @ prefix in URLs",
        "Focused on LLM-specific skills and plugins",
    ],
    notes="Developer-focused LLM skill sharing platform.",
))

_register(PlatformConfig(
    platform_id="lobehub",
    name="LobeHub",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://lobehub.com/auth/signin",
    login_url="https://lobehub.com/auth/signin",
    profile_url_template="https://lobehub.com/@{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["github", "google"],
    username_max_length=30,
    bio_max_length=300,
    tagline_max_length=100,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=5,
    audience_size=6,
    seo_value=6,
    estimated_signup_minutes=3,
    known_quirks=[
        "GitHub OAuth is fastest signup path",
        "Plugin marketplace is separate from agent marketplace",
        "Open-source project with strong developer community",
    ],
    notes="Open-source AI assistant framework with plugin and agent marketplace.",
))

_register(PlatformConfig(
    platform_id="playbooks",
    name="Playbooks AI",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://playbooks.ai/signup",
    login_url="https://playbooks.ai/login",
    profile_url_template="https://playbooks.ai/creators/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=50),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=30,
    bio_max_length=400,
    tagline_max_length=100,
    description_max_length=1500,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=4,
    audience_size=3,
    seo_value=4,
    estimated_signup_minutes=2,
    known_quirks=[
        "Focused on reusable AI workflow playbooks",
        "Free tier allows up to 3 published playbooks",
    ],
    notes="Platform for sharing and selling AI workflow playbooks.",
))

_register(PlatformConfig(
    platform_id="ai_agent_store",
    name="AI Agent Store",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://aiagentstore.com/register",
    login_url="https://aiagentstore.com/login",
    profile_url_template="https://aiagentstore.com/vendors/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="confirm_password", selector='input[name="confirmPassword"]', required=True, field_type="password"),
        FieldConfig(name="company_name", selector='input[name="companyName"]', required=False, max_length=60),
        FieldConfig(name="website", selector='input[name="website"]', required=False),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    username_max_length=30,
    bio_max_length=600,
    tagline_max_length=120,
    description_max_length=3000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=8,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=6,
    audience_size=5,
    seo_value=6,
    estimated_signup_minutes=7,
    known_quirks=[
        "Vendor application requires approval (1-3 business days)",
        "Password must include uppercase, lowercase, number, and symbol",
        "reCAPTCHA v2 checkbox on signup form",
        "Company name helps with vendor approval",
    ],
    notes="Curated AI agent marketplace with vendor approval process.",
))

_register(PlatformConfig(
    platform_id="skill_market",
    name="Skill Market",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://skillmarket.io/join",
    login_url="https://skillmarket.io/signin",
    profile_url_template="https://skillmarket.io/u/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=25),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=25,
    bio_max_length=400,
    tagline_max_length=80,
    description_max_length=1500,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=4,
    audience_size=3,
    seo_value=4,
    estimated_signup_minutes=2,
    known_quirks=[
        "Minimal signup flow, profile built post-registration",
        "Supports free and paid skill listings",
    ],
    notes="Lightweight AI skill listing platform.",
))

_register(PlatformConfig(
    platform_id="cursor_marketplace",
    name="Cursor Marketplace",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://marketplace.cursor.com/register",
    login_url="https://marketplace.cursor.com/login",
    profile_url_template="https://marketplace.cursor.com/publishers/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="publisher_name", selector='input[name="publisherName"]', required=True, max_length=40),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["github"],
    username_max_length=40,
    bio_max_length=500,
    tagline_max_length=100,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=7,
    audience_size=7,
    seo_value=7,
    estimated_signup_minutes=5,
    known_quirks=[
        "GitHub OAuth strongly recommended for developer credibility",
        "Publisher name is public-facing and cannot be changed",
        "Extensions are published via CLI tool, not web UI",
        "Growing rapidly alongside Cursor IDE adoption",
    ],
    notes="Extension marketplace for the Cursor AI code editor.",
))

_register(PlatformConfig(
    platform_id="github_openclaw",
    name="GitHub (Marketplace)",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://github.com/signup",
    login_url="https://github.com/login",
    profile_url_template="https://github.com/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="user[email]"]', required=True),
        FieldConfig(name="password", selector='input[name="user[password]"]', required=True, field_type="password"),
        FieldConfig(name="username", selector='input[name="user[login]"]', required=True, max_length=39),
    ],
    captcha_type=CaptchaType.IMAGE_CHALLENGE,
    requires_email_verification=True,
    has_oauth=False,
    username_max_length=39,
    bio_max_length=160,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=1,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=6,
    audience_size=10,
    seo_value=9,
    estimated_signup_minutes=5,
    known_quirks=[
        "Image puzzle CAPTCHA on signup",
        "Email verification is mandatory",
        "Username is the primary profile identity",
        "Bio is very short (160 chars) — used for SEO",
        "GitHub Sponsors requires separate application",
        "Marketplace actions/apps listed via repository topics",
    ],
    notes="World's largest code hosting platform. Profile doubles as portfolio.",
))

_register(PlatformConfig(
    platform_id="clawver",
    name="Clawver",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://clawver.ai/signup",
    login_url="https://clawver.ai/login",
    profile_url_template="https://clawver.ai/creators/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=25),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=25,
    bio_max_length=400,
    tagline_max_length=100,
    description_max_length=1500,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=3,
    audience_size=2,
    seo_value=3,
    estimated_signup_minutes=2,
    known_quirks=[
        "Early-stage platform, small but engaged community",
        "Profile is editable after creation",
    ],
    notes="Newer AI agent sharing platform.",
))


# ─────────────────────────────────────────────────────────────────────────────
# Workflow Marketplaces
# ─────────────────────────────────────────────────────────────────────────────

_register(PlatformConfig(
    platform_id="n8n_creator_hub",
    name="n8n Creator Hub",
    category=PlatformCategory.WORKFLOW_MARKETPLACE,
    signup_url="https://creators.n8n.io/signup",
    login_url="https://creators.n8n.io/login",
    profile_url_template="https://creators.n8n.io/creators/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=30),
        FieldConfig(name="full_name", selector='input[name="fullName"]', required=True, max_length=50),
        FieldConfig(name="terms", selector='input[name="terms"]', required=True, field_type="checkbox"),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=120,
    description_max_length=3000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=7,
    audience_size=7,
    seo_value=7,
    estimated_signup_minutes=8,
    known_quirks=[
        "reCAPTCHA v2 on signup form",
        "Email verification link expires after 24 hours",
        "Creator profile requires at least 1 published workflow to be visible",
        "Workflow templates must pass review before publishing",
        "Strong SEO due to n8n's domain authority",
    ],
    notes="Official n8n workflow marketplace. High-value audience of automation professionals.",
))

_register(PlatformConfig(
    platform_id="n8nmarket",
    name="n8nmarket",
    category=PlatformCategory.WORKFLOW_MARKETPLACE,
    signup_url="https://n8nmarket.com/register",
    login_url="https://n8nmarket.com/login",
    profile_url_template="https://n8nmarket.com/sellers/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=25),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=25,
    bio_max_length=400,
    tagline_max_length=80,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=5,
    audience_size=4,
    seo_value=5,
    estimated_signup_minutes=2,
    known_quirks=[
        "Third-party n8n workflow marketplace",
        "Simpler seller requirements than official hub",
    ],
    notes="Independent n8n workflow marketplace with easy seller onboarding.",
))

_register(PlatformConfig(
    platform_id="haveworkflow",
    name="HaveWorkflow",
    category=PlatformCategory.WORKFLOW_MARKETPLACE,
    signup_url="https://haveworkflow.com/signup",
    login_url="https://haveworkflow.com/login",
    profile_url_template="https://haveworkflow.com/authors/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="display_name", selector='input[name="displayName"]', required=True, max_length=40),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=40,
    bio_max_length=350,
    tagline_max_length=100,
    description_max_length=1500,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=4,
    audience_size=3,
    seo_value=4,
    estimated_signup_minutes=2,
    known_quirks=[
        "Supports multiple automation platforms (n8n, Make, Zapier)",
        "Author profiles are auto-generated from display name",
    ],
    notes="Multi-platform workflow marketplace.",
))

_register(PlatformConfig(
    platform_id="make_marketplace",
    name="Make Marketplace",
    category=PlatformCategory.WORKFLOW_MARKETPLACE,
    signup_url="https://www.make.com/en/register",
    login_url="https://www.make.com/en/login",
    profile_url_template="https://www.make.com/en/templates/author/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="first_name", selector='input[name="firstName"]', required=True, max_length=30),
        FieldConfig(name="last_name", selector='input[name="lastName"]', required=True, max_length=30),
        FieldConfig(name="country", selector='select[name="country"]', required=True, field_type="select"),
        FieldConfig(name="terms", selector='input[name="terms"]', required=True, field_type="checkbox"),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V3,
    requires_email_verification=True,
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=0,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=6,
    audience_size=8,
    seo_value=7,
    estimated_signup_minutes=8,
    known_quirks=[
        "Country selection is required during signup",
        "reCAPTCHA v3 runs invisibly on page load",
        "Template publishing requires creator program acceptance",
        "Email verification required before account activation",
        "Large established user base from Integromat legacy",
    ],
    notes="Major workflow automation platform with template marketplace.",
))


# ─────────────────────────────────────────────────────────────────────────────
# Digital Product Marketplaces
# ─────────────────────────────────────────────────────────────────────────────

_register(PlatformConfig(
    platform_id="gumroad",
    name="Gumroad",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://app.gumroad.com/signup",
    login_url="https://app.gumroad.com/login",
    profile_url_template="https://{username}.gumroad.com",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    username_max_length=20,
    bio_max_length=500,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=10,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=8,
    audience_size=8,
    seo_value=7,
    estimated_signup_minutes=4,
    known_quirks=[
        "Email verification link sent immediately",
        "Profile name is set after signup in settings",
        "Custom subdomain based on username",
        "10% flat fee on sales (no monthly subscription)",
        "Supports memberships, courses, and digital downloads",
    ],
    notes="Popular digital product marketplace. High monetization, simple setup.",
))

_register(PlatformConfig(
    platform_id="lemon_squeezy",
    name="Lemon Squeezy",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://app.lemonsqueezy.com/register",
    login_url="https://app.lemonsqueezy.com/login",
    profile_url_template="https://{username}.lemonsqueezy.com",
    fields=[
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=50),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="password_confirmation", selector='input[name="password_confirmation"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=0,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=7,
    audience_size=6,
    seo_value=6,
    estimated_signup_minutes=5,
    known_quirks=[
        "Password confirmation field required",
        "Store setup wizard runs after signup",
        "Handles VAT/sales tax automatically",
        "5% + $0.50 per transaction",
        "Developer-friendly API for integrations",
    ],
    notes="Modern Gumroad alternative with better developer tools.",
))

_register(PlatformConfig(
    platform_id="whop",
    name="Whop",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://whop.com/signup",
    login_url="https://whop.com/login",
    profile_url_template="https://whop.com/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=30),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=100,
    description_max_length=3000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=8,
    audience_size=7,
    seo_value=6,
    estimated_signup_minutes=7,
    known_quirks=[
        "reCAPTCHA v2 on signup",
        "Seller dashboard unlocks after first product creation",
        "Supports SaaS subscriptions, not just digital downloads",
        "Strong community features (Discord-like chat)",
        "3% transaction fee",
    ],
    notes="Digital product and SaaS marketplace with community features.",
))

_register(PlatformConfig(
    platform_id="etsy",
    name="Etsy",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://www.etsy.com/join",
    login_url="https://www.etsy.com/signin",
    profile_url_template="https://www.etsy.com/shop/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="first_name", selector='input[name="first_name"]', required=True, max_length=30),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V3,
    requires_email_verification=True,
    requires_phone_verification=True,
    username_max_length=20,
    bio_max_length=5000,
    tagline_max_length=0,
    description_max_length=5000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=False,
    max_links=0,
    complexity=SignupComplexity.COMPLEX,
    monetization_potential=9,
    audience_size=10,
    seo_value=9,
    estimated_signup_minutes=20,
    known_quirks=[
        "Phone verification required for seller accounts",
        "Invisible reCAPTCHA on signup",
        "Shop setup is multi-step wizard (shop name, listings, payment, billing)",
        "Requires active payment method to open shop",
        "Strict policies on digital product listings",
        "$0.20 per listing + 6.5% transaction fee + 3% payment processing",
        "Shop name becomes permanent URL slug",
    ],
    notes="Largest marketplace for handmade/digital goods. Complex setup but massive audience.",
))

_register(PlatformConfig(
    platform_id="creative_market",
    name="Creative Market",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://creativemarket.com/sign-up",
    login_url="https://creativemarket.com/sign-in",
    profile_url_template="https://creativemarket.com/{username}",
    fields=[
        FieldConfig(name="first_name", selector='input[name="first_name"]', required=True, max_length=30),
        FieldConfig(name="last_name", selector='input[name="last_name"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="terms", selector='input[name="tos"]', required=True, field_type="checkbox"),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=100,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=7,
    audience_size=8,
    seo_value=8,
    estimated_signup_minutes=8,
    known_quirks=[
        "Shop application requires portfolio review",
        "reCAPTCHA v2 on registration form",
        "Separate buyer and seller accounts",
        "60% revenue share for sellers",
        "Strong emphasis on design assets (fonts, templates, graphics)",
    ],
    notes="Premium design marketplace. Good for AI-generated templates and assets.",
))

_register(PlatformConfig(
    platform_id="envato",
    name="Envato Market",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://account.envato.com/sign_up",
    login_url="https://account.envato.com/sign_in",
    profile_url_template="https://codecanyon.net/user/{username}",
    fields=[
        FieldConfig(name="first_name", selector='input[name="first_name"]', required=True, max_length=30),
        FieldConfig(name="last_name", selector='input[name="last_name"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=20),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="terms", selector='input[name="terms"]', required=True, field_type="checkbox"),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    username_max_length=20,
    bio_max_length=600,
    tagline_max_length=100,
    description_max_length=3000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=8,
    audience_size=9,
    seo_value=9,
    estimated_signup_minutes=10,
    known_quirks=[
        "Author application requires portfolio and item review",
        "Single Envato account spans all sub-markets (CodeCanyon, ThemeForest, etc.)",
        "reCAPTCHA v2 on signup",
        "Strict item quality review process (can take days)",
        "Revenue share varies by exclusivity (37.5%-62.5%)",
    ],
    notes="Massive digital marketplace (CodeCanyon, ThemeForest). Excellent SEO authority.",
))

_register(PlatformConfig(
    platform_id="payhip",
    name="Payhip",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://payhip.com/auth/register",
    login_url="https://payhip.com/auth/login",
    profile_url_template="https://payhip.com/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=0,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=6,
    audience_size=5,
    seo_value=5,
    estimated_signup_minutes=3,
    known_quirks=[
        "No captcha, no email verification needed",
        "Free plan with 5% transaction fee",
        "Supports ebooks, courses, memberships, and coaching",
        "Built-in EU VAT handling",
    ],
    notes="Simple digital product store with generous free tier.",
))

_register(PlatformConfig(
    platform_id="sendowl",
    name="SendOwl",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://dashboard.sendowl.com/signup",
    login_url="https://dashboard.sendowl.com/login",
    profile_url_template="",
    fields=[
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=50),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    username_max_length=0,
    bio_max_length=0,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=False,
    allows_banner=False,
    allows_links=False,
    max_links=0,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=5,
    audience_size=3,
    seo_value=3,
    estimated_signup_minutes=4,
    known_quirks=[
        "Email verification required",
        "No public storefront or profile — checkout links only",
        "Primarily a delivery tool, not a marketplace",
        "14-day free trial, then paid plans from $9/mo",
    ],
    notes="Digital delivery platform (not a marketplace). Good for checkout embeds.",
))

_register(PlatformConfig(
    platform_id="thrivecart",
    name="ThriveCart",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://thrivecart.com/signup",
    login_url="https://app.thrivecart.com/login",
    profile_url_template="",
    fields=[
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=50),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="business_name", selector='input[name="businessName"]', required=False, max_length=60),
    ],
    captcha_type=CaptchaType.TURNSTILE,
    requires_email_verification=True,
    username_max_length=0,
    bio_max_length=0,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=False,
    allows_banner=False,
    allows_links=False,
    max_links=0,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=7,
    audience_size=4,
    seo_value=3,
    estimated_signup_minutes=7,
    known_quirks=[
        "Cloudflare Turnstile CAPTCHA",
        "Lifetime deal model (one-time payment for access)",
        "No public storefront — cart pages are standalone",
        "Powerful affiliate management built in",
        "Checkout page builder with A/B testing",
    ],
    notes="High-converting cart platform. No marketplace, but powerful for direct sales.",
))


# ─────────────────────────────────────────────────────────────────────────────
# Education Platforms
# ─────────────────────────────────────────────────────────────────────────────

_register(PlatformConfig(
    platform_id="teachable",
    name="Teachable",
    category=PlatformCategory.EDUCATION,
    signup_url="https://sso.teachable.com/secure/teachable_accounts/sign_up",
    login_url="https://sso.teachable.com/secure/teachable_accounts/sign_in",
    profile_url_template="",
    fields=[
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=50),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    username_max_length=0,
    bio_max_length=1000,
    tagline_max_length=0,
    description_max_length=5000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=8,
    audience_size=7,
    seo_value=6,
    estimated_signup_minutes=5,
    known_quirks=[
        "Email verification required",
        "School (subdomain) setup is separate from account signup",
        "Free plan limited to 1 course and 10 students",
        "Custom domains available on paid plans",
        "No marketplace listing — you drive your own traffic",
    ],
    notes="Course hosting platform. Great for AI/automation courses.",
))

_register(PlatformConfig(
    platform_id="thinkific",
    name="Thinkific",
    category=PlatformCategory.EDUCATION,
    signup_url="https://www.thinkific.com/begin/",
    login_url="https://app.thinkific.com/login",
    profile_url_template="",
    fields=[
        FieldConfig(name="first_name", selector='input[name="first_name"]', required=True, max_length=30),
        FieldConfig(name="last_name", selector='input[name="last_name"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="school_name", selector='input[name="site_name"]', required=True, max_length=40),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    username_max_length=40,
    bio_max_length=1000,
    tagline_max_length=0,
    description_max_length=5000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=7,
    audience_size=6,
    seo_value=6,
    estimated_signup_minutes=6,
    known_quirks=[
        "School name determines subdomain (cannot be changed easily)",
        "Onboarding wizard asks about course topic and audience size",
        "Free plan allows 1 course",
        "Email verification required",
        "Thinkific Marketplace (new) is separate opt-in",
    ],
    notes="Course hosting platform with emerging marketplace feature.",
))

_register(PlatformConfig(
    platform_id="udemy",
    name="Udemy",
    category=PlatformCategory.EDUCATION,
    signup_url="https://www.udemy.com/join/signup-popup/",
    login_url="https://www.udemy.com/join/login-popup/",
    profile_url_template="https://www.udemy.com/user/{username}/",
    fields=[
        FieldConfig(name="fullname", selector='input[name="name"]', required=True, max_length=60),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google", "apple", "facebook"],
    username_max_length=60,
    bio_max_length=600,
    tagline_max_length=60,
    description_max_length=6000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=9,
    audience_size=10,
    seo_value=9,
    estimated_signup_minutes=8,
    known_quirks=[
        "reCAPTCHA v2 on signup",
        "Instructor application is separate from student signup",
        "Course must meet quality standards (video, audio, content)",
        "Udemy controls pricing with frequent sales",
        "37% revenue on organic sales, 97% on self-promoted",
        "Massive SEO authority and internal search traffic",
    ],
    notes="Largest online course marketplace. Incredible audience reach.",
))

_register(PlatformConfig(
    platform_id="skillshare",
    name="Skillshare",
    category=PlatformCategory.EDUCATION,
    signup_url="https://www.skillshare.com/signup",
    login_url="https://www.skillshare.com/login",
    profile_url_template="https://www.skillshare.com/en/profile/{username}",
    fields=[
        FieldConfig(name="first_name", selector='input[name="firstName"]', required=True, max_length=30),
        FieldConfig(name="last_name", selector='input[name="lastName"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.HCAPTCHA,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google", "apple", "facebook"],
    username_max_length=30,
    bio_max_length=1000,
    tagline_max_length=100,
    description_max_length=3000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=7,
    audience_size=8,
    seo_value=7,
    estimated_signup_minutes=8,
    known_quirks=[
        "hCaptcha on signup form",
        "Teacher application requires sample class proposal",
        "Payment based on minutes watched (royalty model)",
        "No per-course pricing — everything is subscription-based",
        "Strong in creative and business categories",
    ],
    notes="Subscription-based learning platform. Royalty payment model.",
))


# ─────────────────────────────────────────────────────────────────────────────
# Prompt / AI Config Marketplaces
# ─────────────────────────────────────────────────────────────────────────────

_register(PlatformConfig(
    platform_id="promptbase",
    name="PromptBase",
    category=PlatformCategory.PROMPT_MARKETPLACE,
    signup_url="https://promptbase.com/signup",
    login_url="https://promptbase.com/login",
    profile_url_template="https://promptbase.com/profile/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google"],
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=100,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=6,
    audience_size=6,
    seo_value=6,
    estimated_signup_minutes=4,
    known_quirks=[
        "Email verification required before selling",
        "Google OAuth available for faster signup",
        "Prompts priced at $1.99-$9.99 typically",
        "80% revenue share for sellers",
        "Supports GPT, DALL-E, Midjourney, Stable Diffusion prompts",
    ],
    notes="Largest prompt marketplace. Good for AI prompt and config sales.",
))

_register(PlatformConfig(
    platform_id="gptsmoney",
    name="GPTsMoney",
    category=PlatformCategory.PROMPT_MARKETPLACE,
    signup_url="https://gptsmoney.com/register",
    login_url="https://gptsmoney.com/login",
    profile_url_template="https://gptsmoney.com/creators/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=25),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=25,
    bio_max_length=300,
    tagline_max_length=80,
    description_max_length=1500,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=4,
    audience_size=3,
    seo_value=4,
    estimated_signup_minutes=2,
    known_quirks=[
        "Focused on monetizing GPT configurations",
        "Simple listing process for GPT links",
        "Smaller but targeted audience",
    ],
    notes="GPT monetization platform for ChatGPT creators.",
))

_register(PlatformConfig(
    platform_id="calstudio",
    name="Cal Studio",
    category=PlatformCategory.PROMPT_MARKETPLACE,
    signup_url="https://calstudio.ai/signup",
    login_url="https://calstudio.ai/login",
    profile_url_template="https://calstudio.ai/creators/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=40),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=30,
    bio_max_length=400,
    tagline_max_length=80,
    description_max_length=1500,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=3,
    audience_size=2,
    seo_value=3,
    estimated_signup_minutes=2,
    known_quirks=[
        "Early-stage prompt and AI config platform",
        "Focus on Claude and GPT system prompts",
    ],
    notes="Niche AI configuration marketplace.",
))

_register(PlatformConfig(
    platform_id="fastbot",
    name="FastBot",
    category=PlatformCategory.PROMPT_MARKETPLACE,
    signup_url="https://fastbot.ai/signup",
    login_url="https://fastbot.ai/login",
    profile_url_template="https://fastbot.ai/bots/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=40),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=False,
    username_max_length=25,
    bio_max_length=300,
    tagline_max_length=80,
    description_max_length=1000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=2,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=4,
    audience_size=3,
    seo_value=3,
    estimated_signup_minutes=2,
    known_quirks=[
        "Chatbot builder with marketplace component",
        "Bots can be shared publicly or embedded on websites",
        "Free tier includes basic bot creation",
    ],
    notes="Chatbot creation and sharing platform.",
))


# ─────────────────────────────────────────────────────────────────────────────
# 3D Models
# ─────────────────────────────────────────────────────────────────────────────

_register(PlatformConfig(
    platform_id="cgtrader",
    name="CGTrader",
    category=PlatformCategory.THREE_D_MODELS,
    signup_url="https://www.cgtrader.com/signup",
    login_url="https://www.cgtrader.com/login",
    profile_url_template="https://www.cgtrader.com/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="user[login]"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="user[email]"]', required=True),
        FieldConfig(name="password", selector='input[name="user[password]"]', required=True, field_type="password"),
        FieldConfig(name="terms", selector='input[name="user[terms]"]', required=True, field_type="checkbox"),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google", "facebook"],
    username_max_length=30,
    bio_max_length=1000,
    tagline_max_length=100,
    description_max_length=5000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=7,
    audience_size=7,
    seo_value=8,
    estimated_signup_minutes=8,
    known_quirks=[
        "reCAPTCHA v2 on signup",
        "Email verification required",
        "Seller profile created separately from buyer account",
        "80% revenue share for exclusive models",
        "Supports 3D print models, game assets, and VFX models",
        "Model uploads require format and preview image validation",
        "Strong Google indexing for 3D model searches",
    ],
    notes="Major 3D model marketplace. Excellent for AI-generated 3D models and printables.",
))


# ─────────────────────────────────────────────────────────────────────────────
# Additional Platforms (Expansion Pack: 12 more platforms)
# ─────────────────────────────────────────────────────────────────────────────

# --- Developer Platforms ---

_register(PlatformConfig(
    platform_id="huggingface",
    name="Hugging Face",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://huggingface.co/join",
    login_url="https://huggingface.co/login",
    profile_url_template="https://huggingface.co/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=50),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="fullname", selector='input[name="fullname"]', required=False, max_length=100),
        FieldConfig(name="bio", selector='textarea[name="bio"]', required=False, field_type="textarea", max_length=1000),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google", "github"],
    username_max_length=50,
    bio_max_length=1000,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=8,
    audience_size=9,
    seo_value=9,
    estimated_signup_minutes=3,
    known_quirks=[
        "GitHub OAuth is the most common signup method",
        "Spaces and Models have separate visibility settings",
        "Organization creation is separate from personal account",
    ],
    notes="Largest AI/ML model hub. Essential for AI tool distribution.",
))

_register(PlatformConfig(
    platform_id="replit",
    name="Replit",
    category=PlatformCategory.AI_MARKETPLACE,
    signup_url="https://replit.com/signup",
    login_url="https://replit.com/login",
    profile_url_template="https://replit.com/@{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=39),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="bio", selector='textarea[name="bio"]', required=False, field_type="textarea", max_length=500),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google", "github", "apple"],
    username_max_length=39,
    bio_max_length=500,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=7,
    audience_size=8,
    seo_value=7,
    estimated_signup_minutes=3,
    known_quirks=[
        "Templates/Bounties are the main monetization path",
        "GitHub OAuth recommended",
    ],
    notes="Code-first platform with AI integration. Good for selling templates and tools.",
))

_register(PlatformConfig(
    platform_id="vercel",
    name="Vercel",
    category=PlatformCategory.CODE_REPOSITORY,
    signup_url="https://vercel.com/signup",
    login_url="https://vercel.com/login",
    profile_url_template="https://vercel.com/{username}",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="name", selector='input[name="name"]', required=False, max_length=64),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["github", "gitlab", "bitbucket"],
    username_max_length=48,
    bio_max_length=0,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=True,
    allows_banner=False,
    allows_links=False,
    max_links=0,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=4,
    audience_size=8,
    seo_value=8,
    estimated_signup_minutes=2,
    known_quirks=[
        "Primarily GitHub OAuth signup",
        "Profile is minimal — mainly for template marketplace",
    ],
    notes="Deploy platform. Templates marketplace is growing.",
))

_register(PlatformConfig(
    platform_id="supabase",
    name="Supabase",
    category=PlatformCategory.CODE_REPOSITORY,
    signup_url="https://supabase.com/dashboard/sign-up",
    login_url="https://supabase.com/dashboard/sign-in",
    profile_url_template="",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["github"],
    username_max_length=0,
    bio_max_length=0,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=False,
    allows_banner=False,
    allows_links=False,
    max_links=0,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=3,
    audience_size=7,
    seo_value=5,
    estimated_signup_minutes=2,
    known_quirks=["Minimal profile — mainly for hosting open-source projects"],
    notes="Backend-as-a-service. Presence for open-source credibility.",
))

_register(PlatformConfig(
    platform_id="railway",
    name="Railway",
    category=PlatformCategory.CODE_REPOSITORY,
    signup_url="https://railway.app/login",
    login_url="https://railway.app/login",
    profile_url_template="",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["github"],
    username_max_length=0,
    bio_max_length=0,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=False,
    allows_banner=False,
    allows_links=False,
    max_links=0,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=3,
    audience_size=6,
    seo_value=4,
    estimated_signup_minutes=2,
    known_quirks=["GitHub-only signup", "Templates marketplace"],
    notes="Deploy platform. Growing template marketplace.",
))

# --- Community / Creator Platforms ---

_register(PlatformConfig(
    platform_id="producthunt",
    name="Product Hunt",
    category=PlatformCategory.SOCIAL_PLATFORM,
    signup_url="https://www.producthunt.com/",
    login_url="https://www.producthunt.com/login",
    profile_url_template="https://www.producthunt.com/@{username}",
    fields=[
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=50),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="headline", selector='input[name="headline"]', required=False, max_length=80),
        FieldConfig(name="bio", selector='textarea[name="bio"]', required=False, field_type="textarea", max_length=500),
        FieldConfig(name="website", selector='input[name="website"]', required=False),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["twitter", "google"],
    username_max_length=20,
    bio_max_length=500,
    tagline_max_length=80,
    description_max_length=0,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=6,
    audience_size=9,
    seo_value=9,
    estimated_signup_minutes=3,
    known_quirks=[
        "Launch day upvotes are critical",
        "Maker profile separate from hunter profile",
        "High DA backlink from profile",
    ],
    notes="Essential for product launches. Very high SEO value from profile backlinks.",
))

_register(PlatformConfig(
    platform_id="indiehackers",
    name="Indie Hackers",
    category=PlatformCategory.SOCIAL_PLATFORM,
    signup_url="https://www.indiehackers.com/sign-up",
    login_url="https://www.indiehackers.com/sign-in",
    profile_url_template="https://www.indiehackers.com/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=20),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="bio", selector='textarea[name="bio"]', required=False, field_type="textarea", max_length=500),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=False,
    username_max_length=20,
    bio_max_length=500,
    tagline_max_length=0,
    description_max_length=1000,
    allows_avatar=True,
    allows_banner=False,
    allows_links=True,
    max_links=3,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=5,
    audience_size=7,
    seo_value=8,
    estimated_signup_minutes=3,
    known_quirks=["Product listing is separate from profile", "Revenue milestone badges"],
    notes="Community for indie makers. Good for credibility and networking.",
))

_register(PlatformConfig(
    platform_id="buymeacoffee",
    name="Buy Me a Coffee",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://www.buymeacoffee.com/signup",
    login_url="https://www.buymeacoffee.com/login",
    profile_url_template="https://www.buymeacoffee.com/{username}",
    fields=[
        FieldConfig(name="name", selector='input[name="name"]', required=True, max_length=50),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=30),
        FieldConfig(name="bio", selector='textarea[name="bio"]', required=False, field_type="textarea", max_length=500),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google", "apple"],
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=0,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=7,
    audience_size=8,
    seo_value=7,
    estimated_signup_minutes=3,
    known_quirks=[
        "Three monetization types: tips, memberships, shop",
        "PayPal or Stripe required for payouts",
        "Custom page URL is the username",
    ],
    notes="Creator monetization platform. Good for community support and digital products.",
))

_register(PlatformConfig(
    platform_id="kofi",
    name="Ko-fi",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://ko-fi.com/account/register",
    login_url="https://ko-fi.com/account/login",
    profile_url_template="https://ko-fi.com/{username}",
    fields=[
        FieldConfig(name="displayname", selector='input[name="DisplayName"]', required=True, max_length=50),
        FieldConfig(name="email", selector='input[name="Email"]', required=True),
        FieldConfig(name="password", selector='input[name="Password"]', required=True, field_type="password"),
        FieldConfig(name="bio", selector='textarea[name="bio"]', required=False, field_type="textarea", max_length=500),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google"],
    username_max_length=30,
    bio_max_length=500,
    tagline_max_length=0,
    description_max_length=2000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=6,
    audience_size=7,
    seo_value=6,
    estimated_signup_minutes=5,
    known_quirks=[
        "reCAPTCHA on signup",
        "Ko-fi Gold unlocks additional features",
        "Shop, commissions, and memberships available",
    ],
    notes="Alternative to BMC. Good for creators selling digital products.",
))

_register(PlatformConfig(
    platform_id="notion_marketplace",
    name="Notion Marketplace",
    category=PlatformCategory.DIGITAL_PRODUCT,
    signup_url="https://www.notion.so/signup",
    login_url="https://www.notion.so/login",
    profile_url_template="",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="name", selector='input[name="name"]', required=False, max_length=50),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["google", "apple"],
    username_max_length=0,
    bio_max_length=0,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=True,
    allows_banner=False,
    allows_links=False,
    max_links=0,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=7,
    audience_size=9,
    seo_value=6,
    estimated_signup_minutes=2,
    known_quirks=[
        "Template marketplace is separate from Notion account",
        "Need to apply as template creator",
    ],
    notes="Huge audience. Template marketplace growing rapidly.",
))

_register(PlatformConfig(
    platform_id="render",
    name="Render",
    category=PlatformCategory.CODE_REPOSITORY,
    signup_url="https://dashboard.render.com/register",
    login_url="https://dashboard.render.com/login",
    profile_url_template="",
    fields=[
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="name", selector='input[name="name"]', required=False, max_length=50),
    ],
    captcha_type=CaptchaType.NONE,
    requires_email_verification=True,
    has_oauth=True,
    oauth_providers=["github", "gitlab", "google"],
    username_max_length=0,
    bio_max_length=0,
    tagline_max_length=0,
    description_max_length=0,
    allows_avatar=False,
    allows_banner=False,
    allows_links=False,
    max_links=0,
    complexity=SignupComplexity.SIMPLE,
    monetization_potential=3,
    audience_size=6,
    seo_value=5,
    estimated_signup_minutes=2,
    known_quirks=["Primarily GitHub OAuth"],
    notes="Cloud deploy platform. Blueprint marketplace growing.",
))

_register(PlatformConfig(
    platform_id="thingiverse",
    name="Thingiverse",
    category=PlatformCategory.THREE_D_MODELS,
    signup_url="https://www.thingiverse.com/register",
    login_url="https://www.thingiverse.com/login",
    profile_url_template="https://www.thingiverse.com/{username}",
    fields=[
        FieldConfig(name="username", selector='input[name="username"]', required=True, max_length=30),
        FieldConfig(name="email", selector='input[name="email"]', required=True),
        FieldConfig(name="password", selector='input[name="password"]', required=True, field_type="password"),
        FieldConfig(name="bio", selector='textarea[name="bio"]', required=False, field_type="textarea", max_length=1000),
    ],
    captcha_type=CaptchaType.RECAPTCHA_V2,
    requires_email_verification=True,
    has_oauth=False,
    username_max_length=30,
    bio_max_length=1000,
    tagline_max_length=0,
    description_max_length=5000,
    allows_avatar=True,
    allows_banner=True,
    allows_links=True,
    max_links=5,
    complexity=SignupComplexity.MODERATE,
    monetization_potential=5,
    audience_size=8,
    seo_value=8,
    estimated_signup_minutes=5,
    known_quirks=[
        "Owned by MakerBot/Stratasys",
        "Free-only model uploads (no direct monetization)",
        "High SEO value for 3D model searches",
        "Tip jar feature for creators",
    ],
    notes="Largest free 3D model repository. Excellent SEO for 3D printable models.",
))


# ─────────────────────────────────────────────────────────────────────────────
# Summary counts (populated at import time)
# ─────────────────────────────────────────────────────────────────────────────

PLATFORM_COUNT = len(PLATFORMS)
CATEGORIES_COVERED = len({p.category for p in PLATFORMS.values()})
SIMPLE_PLATFORMS = [p for p in PLATFORMS.values() if p.complexity == SignupComplexity.SIMPLE]
MODERATE_PLATFORMS = [p for p in PLATFORMS.values() if p.complexity == SignupComplexity.MODERATE]
COMPLEX_PLATFORMS = [p for p in PLATFORMS.values() if p.complexity in (SignupComplexity.COMPLEX, SignupComplexity.MANUAL_ONLY)]
