"""Smoke tests for anthropic-cost-optimizer-bundle — auto-generated by EMPIRE-BRAIN Evolution Engine."""
import pytest
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


class TestImports:
    """Verify module can be imported (requires ANTHROPIC_API_KEY)."""

    @pytest.mark.skip(reason="Requires ANTHROPIC_API_KEY — client initializes at import time")
    def test_import_anthropic_optimized(self):
        import anthropic_optimized
        assert anthropic_optimized is not None

    @pytest.mark.skip(reason="Requires ANTHROPIC_API_KEY")
    def test_has_call_function(self):
        from anthropic_optimized import call
        assert callable(call)

    @pytest.mark.skip(reason="Requires ANTHROPIC_API_KEY")
    def test_has_classify_function(self):
        from anthropic_optimized import classify
        assert callable(classify)

    @pytest.mark.skip(reason="Requires ANTHROPIC_API_KEY")
    def test_has_extract_function(self):
        from anthropic_optimized import extract
        assert callable(extract)


class TestModuleStructure:
    """Verify project file structure is intact."""

    def test_main_module_exists(self):
        main_file = Path(__file__).parent.parent / "anthropic_optimized.py"
        assert main_file.exists()

    def test_deploy_workflow_exists(self):
        deploy_file = Path(__file__).parent.parent / "deploy_workflow.py"
        assert deploy_file.exists()
