"""Smoke tests for empire-mcp-server -- auto-generated by EMPIRE-BRAIN Evolution Engine.

All tests are purely local. No network connections, API keys, or running
services required. Tests that would need external resources are skipped.

Generated: 2026-03-06 23:43
"""
import pytest
import sys
import importlib
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


class TestImports:
    """Verify core modules for empire-mcp-server can be imported."""

    def test_import_server(self):
        import server
        assert server is not None

    def test_import_project_templates(self):
        import project_templates
        assert project_templates is not None


class TestFunctionExistence:
    """Verify key functions and constants exist and are accessible."""

    def test_server_query_db_exists(self):
        from server import query_db
        assert query_db is not None

    def test_server_send_response_exists(self):
        from server import send_response
        assert send_response is not None

    def test_server_send_error_exists(self):
        from server import send_error
        assert send_error is not None

    def test_server_handle_initialize_exists(self):
        from server import handle_initialize
        assert handle_initialize is not None

    def test_server_handle_tools_list_exists(self):
        from server import handle_tools_list
        assert handle_tools_list is not None

    def test_project_templates_ProjectTemplates_exists(self):
        from project_templates import ProjectTemplates
        assert ProjectTemplates is not None


class TestClassInstantiation:
    """Verify key classes can be instantiated."""

    @pytest.mark.skip(reason="Requires empire-skill-library on path")
    def test_create_project_templates_ProjectTemplates(self):
        from project_templates import ProjectTemplates
        obj = ProjectTemplates()
        assert obj is not None


class TestMCPServerFunctions:
    """Verify MCP server utility functions."""

    def test_handle_initialize_structure(self, capsys):
        from server import handle_initialize
        import json
        handle_initialize("test-id", {})
        captured = capsys.readouterr()
        response = json.loads(captured.out)
        assert response['id'] == 'test-id'
        assert 'result' in response
        assert 'capabilities' in response['result']

    def test_handle_tools_list_returns_tools(self, capsys):
        from server import handle_tools_list
        import json
        handle_tools_list("tools-id")
        captured = capsys.readouterr()
        response = json.loads(captured.out)
        assert 'result' in response
        tools = response['result'].get('tools', [])
        assert len(tools) > 0, 'MCP server should expose at least one tool'

