"""
Site preset configurations for all 16 websites.
Each preset maps the site-configs.json data into ZimmWriter controller parameters.
"""

from typing import Dict, Any, Optional

SITE_PRESETS: Dict[str, Dict[str, Any]] = {

    # ═══════════════════════════════════════
    # AI & TECHNOLOGY SITES
    # ═══════════════════════════════════════

    "aiinactionhub.com": {
        "domain": "aiinactionhub.com",
        "niche": "AI & Technology",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": True,
        "deep_research": False,
        "wordpress_category": "AI Technology",
        "wordpress_settings": {
            "site_url": "https://aiinactionhub.com",
            "user_name": "AIinActionEditor",
            "category": "AI Technology",
            "article_status": "draft",
        },
    },

    "aidiscoverydigest.com": {
        "domain": "aidiscoverydigest.com",
        "niche": "AI Research & Analysis",
        "h2_count": "Automatic",
        "h2_auto_limit": 12,
        "section_length": "Long",
        "voice": "Third Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": True,
        "deep_research": True,
        "wordpress_category": "AI Research",
        "wordpress_settings": {
            "site_url": "https://aidiscoverydigest.com",
            "user_name": "AITrendCurator",
            "category": "AI Research",
            "article_status": "draft",
        },
    },

    "clearainews.com": {
        "domain": "clearainews.com",
        "niche": "AI News & Tech Journalism",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "section_length": "Short",
        "voice": "Third Person",
        "intro": "Standard Intro",
        "faq": "No FAQ",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": True,
        "deep_research": True,
        "wordpress_category": "AI News",
        "wordpress_settings": {
            "site_url": "https://clearainews.com",
            "user_name": "ClearAIEditor",
            "category": "AI News",
            "article_status": "draft",
        },
    },

    "aiinactionblueprint.com": {
        "domain": "aiinactionblueprint.com",
        "niche": "AI Automation & Workflows",
        "h2_count": "Automatic",
        "h2_auto_limit": 12,
        "section_length": "Long",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "Automation Blueprints",
        "wordpress_settings": {
            "site_url": "https://aiinactionblueprint.com",
            "user_name": "AIinActionEditor",
            "category": "Automation Blueprints",
            "article_status": "draft",
        },
    },

    "wealthfromai.com": {
        "domain": "wealthfromai.com",
        "niche": "AI-Powered Income Strategies",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "AI Income Strategies",
        "wordpress_settings": {
            "site_url": "https://wealthfromai.com",
            "user_name": "AIWealthGuide",
            "category": "AI Income Strategies",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # SMART HOME SITES
    # ═══════════════════════════════════════

    "smarthomewizards.com": {
        "domain": "smarthomewizards.com",
        "niche": "Smart Home Automation",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": True,
        "link_pack": True,
        "wordpress_category": "Smart Home Guides",
        "wordpress_settings": {
            "site_url": "https://smarthomewizards.com",
            "user_name": "SmartHomeGuru",
            "category": "Smart Home Guides",
            "article_status": "draft",
        },
    },

    "smarthomegearreviews.com": {
        "domain": "smarthomegearreviews.com",
        "niche": "Smart Home Product Reviews",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": True,
        "link_pack": True,
        "wordpress_category": "Product Reviews",
        "wordpress_settings": {
            "site_url": "https://smarthomegearreviews.com",
            "user_name": "SmartHomeEditor",
            "category": "Product Reviews",
            "article_status": "draft",
        },
    },

    "theconnectedhaven.com": {
        "domain": "theconnectedhaven.com",
        "niche": "Smart Home Lifestyle & Wellness",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "Connected Living",
        "wordpress_settings": {
            "site_url": "https://theconnectedhaven.com",
            "user_name": "TheSmartHomeGuide",
            "category": "Connected Living",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # SPIRITUALITY & WITCHCRAFT
    # ═══════════════════════════════════════

    "witchcraftforbeginners.com": {
        "domain": "witchcraftforbeginners.com",
        "niche": "Witchcraft & Spirituality",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,  # Preserve unique voice
        "wordpress_category": "Witchcraft Basics",
        "wordpress_settings": {
            "site_url": "https://witchcraftforbeginners.com",
            "user_name": "MoonlightMystic",
            "category": "Witchcraft Basics",
            "article_status": "draft",
        },
    },

    "manifestandalign.com": {
        "domain": "manifestandalign.com",
        "niche": "Manifestation & Spiritual Growth",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "Manifestation Guides",
        "wordpress_settings": {
            "site_url": "https://manifestandalign.com",
            "user_name": "ManifestMaster",
            "category": "Manifestation Guides",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # LIFESTYLE & FAMILY
    # ═══════════════════════════════════════

    "family-flourish.com": {
        "domain": "family-flourish.com",
        "niche": "Family & Parenting",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "Family Life",
        "wordpress_settings": {
            "site_url": "https://family-flourish.com",
            "user_name": "FamilyGrowthGuide",
            "category": "Family Life",
            "article_status": "draft",
        },
    },

    "celebrationseason.net": {
        "domain": "celebrationseason.net",
        "niche": "Holiday & Celebration Guides",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "Holiday Guides",
        "wordpress_settings": {
            "site_url": "https://celebrationseason.net",
            "user_name": "CelebrationEditor",
            "category": "Holiday Guides",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # KNOWLEDGE & EDUCATION
    # ═══════════════════════════════════════

    "mythicalarchives.com": {
        "domain": "mythicalarchives.com",
        "niche": "Mythology & Folklore",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "section_length": "Long",
        "voice": "Third Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": True,
        "wordpress_category": "Mythology",
        "wordpress_settings": {
            "site_url": "https://mythicalarchives.com",
            "user_name": "ArcaneArchivist",
            "category": "Mythology",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # PRODUCT REVIEW SITES
    # ═══════════════════════════════════════

    "wearablegearreviews.com": {
        "domain": "wearablegearreviews.com",
        "niche": "Wearable Tech Reviews",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": True,
        "link_pack": True,
        "wordpress_category": "Wearable Reviews",
        "wordpress_settings": {
            "site_url": "https://wearablegearreviews.com",
            "user_name": "WearableReviewPro",
            "category": "Wearable Reviews",
            "article_status": "draft",
        },
    },

    "pulsegearreviews.com": {
        "domain": "pulsegearreviews.com",
        "niche": "EDC & Tactical Gear Reviews",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": True,
        "link_pack": True,
        "wordpress_category": "EDC Reviews",
        "wordpress_settings": {
            "site_url": "https://pulsegearreviews.com",
            "user_name": "PulseGearEditor",
            "category": "EDC Reviews",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # HOBBY & NICHE SITES
    # ═══════════════════════════════════════

    "sprout-and-spruce.com": {
        "domain": "sprout-and-spruce.com",
        "niche": "Gardening & Plant Care",
        "h2_count": "Automatic",
        "h2_auto_limit": 9,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "Plant Care",
        "wordpress_settings": {
            "site_url": "https://sprout-and-spruce.com",
            "user_name": "SproutEditor",
            "category": "Plant Care",
            "article_status": "draft",
        },
    },

    "flavors-and-forks.com": {
        "domain": "flavors-and-forks.com",
        "niche": "Recipes & Cooking Guides",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "section_length": "Short",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": False,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "Recipes",
        "wordpress_settings": {
            "site_url": "https://flavors-and-forks.com",
            "user_name": "FlavorsEditor",
            "category": "Recipes",
            "article_status": "draft",
        },
    },

    "bulletjournals.net": {
        "domain": "bulletjournals.net",
        "niche": "Bullet Journaling & Productivity",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "section_length": "Medium",
        "voice": "Second Person",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "progress_indicator": True,
        "serp_scraping": False,
        "wordpress_category": "Bullet Journal Ideas",
        "wordpress_settings": {
            "site_url": "https://bulletjournals.net",
            "user_name": "BulletJournalPro",
            "category": "Bullet Journal Ideas",
            "article_status": "draft",
        },
    },
}


def get_preset(domain: str) -> Optional[Dict[str, Any]]:
    """Get preset config for a domain."""
    return SITE_PRESETS.get(domain)

def get_all_domains() -> list:
    """Get list of all configured domains."""
    return list(SITE_PRESETS.keys())

def get_presets_by_niche(niche_keyword: str) -> Dict[str, Dict[str, Any]]:
    """Find presets matching a niche keyword."""
    return {
        domain: config
        for domain, config in SITE_PRESETS.items()
        if niche_keyword.lower() in config.get("niche", "").lower()
    }
