"""
Site preset configurations for 14 active websites.
Each preset maps the site-configs.json data into ZimmWriter controller parameters.

Fields cover ALL Bulk Writer dropdowns and checkboxes so profiles can be saved
with complete, exact settings.
"""

from typing import Dict, Any, Optional

SITE_PRESETS: Dict[str, Dict[str, Any]] = {

    # ═══════════════════════════════════════
    # AI & TECHNOLOGY SITES
    # ═══════════════════════════════════════

    "aiinactionhub.com": {
        "domain": "aiinactionhub.com",
        "niche": "AI & Technology",
        # Dropdowns
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "h2_lower_limit": 5,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Explorer",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "ideogram 3t $.030/img (F)",
        "subheading_image_quantity": "Every Other H2 (Max 3)",
        "subheading_images_model": "flux schnell $.003/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        # Checkboxes
        "lists": True,
        "tables": True,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        # Feature toggles
        "serp_scraping": True,
        "deep_research": False,
        # WordPress
        "wordpress_category": "AI Technology",
        "wordpress_settings": {
            "site_url": "https://aiinactionhub.com",
            "user_name": "AIinActionEditor",
            "category": "AI Technology",
            "article_status": "draft",
        },
    },

    "aidiscoverydigest.com": {
        "domain": "aidiscoverydigest.com",
        "niche": "AI Research & Analysis",
        "h2_count": "Automatic",
        "h2_auto_limit": 12,
        "h2_lower_limit": 6,
        "ai_outline_quality": "High $$",
        "section_length": "Long",
        "voice": "Third Person (He, She, It, They)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Sage",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "flux dev $.025/img (F)",
        "subheading_image_quantity": "Every 3rd H2 (Max 3)",
        "subheading_images_model": "flux schnell $.003/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": True,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": True,
        "deep_research": True,
        "wordpress_category": "AI Research",
        "wordpress_settings": {
            "site_url": "https://aidiscoverydigest.com",
            "user_name": "AITrendCurator",
            "category": "AI Research",
            "article_status": "draft",
        },
    },

    "clearainews.com": {
        "domain": "clearainews.com",
        "niche": "AI News & Tech Journalism",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "h2_lower_limit": 4,
        "ai_outline_quality": "Normal $",
        "section_length": "Short",
        "voice": "Third Person (He, She, It, They)",
        "intro": "Standard Intro",
        "faq": "No FAQ",
        "audience_personality": "Ruler",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "ideogram 3b $.060/img (F)",
        "subheading_image_quantity": "Every 3rd H2 (Max 3)",
        "subheading_images_model": "flux schnell $.003/img (F)",
        "ai_model_image_prompts": "GPT-4o Mini (OA)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": True,
        "deep_research": True,
        "wordpress_category": "AI News",
        "wordpress_settings": {
            "site_url": "https://clearainews.com",
            "user_name": "ClearAIEditor",
            "category": "AI News",
            "article_status": "draft",
        },
    },

    "wealthfromai.com": {
        "domain": "wealthfromai.com",
        "niche": "AI-Powered Income Strategies",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "h2_lower_limit": 5,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Hero",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "ideogram 3t $.030/img (F)",
        "subheading_image_quantity": "Every Other H2 (Max 5)",
        "subheading_images_model": "flux dev $.025/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": True,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": False,
        "wordpress_category": "AI Income Strategies",
        "wordpress_settings": {
            "site_url": "https://wealthfromai.com",
            "user_name": "AIWealthGuide",
            "category": "AI Income Strategies",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # SMART HOME SITES
    # ═══════════════════════════════════════

    "smarthomewizards.com": {
        "domain": "smarthomewizards.com",
        "niche": "Smart Home Automation",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "h2_lower_limit": 5,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Magician",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "imagegen-4 $.050/img (F)",
        "subheading_image_quantity": "Every Other H2 (Max 5)",
        "subheading_images_model": "ideogram 3t $.030/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": True,
        "link_pack": True,
        "wordpress_category": "Smart Home Guides",
        "wordpress_settings": {
            "site_url": "https://smarthomewizards.com",
            "user_name": "SmartHomeGuru",
            "category": "Smart Home Guides",
            "article_status": "draft",
        },
    },

    "smarthomegearreviews.com": {
        "domain": "smarthomegearreviews.com",
        "niche": "Smart Home Product Reviews",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "h2_lower_limit": 5,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Everyman",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "gpt-image-1 med $.063/img (OA)",
        "subheading_image_quantity": "Every H2 (Max 5)",
        "subheading_images_model": "ideogram 3t $.030/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": True,
        "link_pack": True,
        "wordpress_category": "Product Reviews",
        "wordpress_settings": {
            "site_url": "https://smarthomegearreviews.com",
            "user_name": "SmartHomeEditor",
            "category": "Product Reviews",
            "article_status": "draft",
        },
    },

    "theconnectedhaven.com": {
        "domain": "theconnectedhaven.com",
        "niche": "Smart Home Lifestyle & Wellness",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "h2_lower_limit": 4,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Caregiver",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "flux pro $.040/img (F)",
        "subheading_image_quantity": "Every Other H2 (Max 3)",
        "subheading_images_model": "flux schnell $.003/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": False,
        "wordpress_category": "Connected Living",
        "wordpress_settings": {
            "site_url": "https://theconnectedhaven.com",
            "user_name": "TheSmartHomeGuide",
            "category": "Connected Living",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # SPIRITUALITY & WITCHCRAFT
    # ═══════════════════════════════════════

    "witchcraftforbeginners.com": {
        "domain": "witchcraftforbeginners.com",
        "niche": "Witchcraft & Spirituality",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "h2_lower_limit": 4,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Creator",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "ideogram 3q $.090/img (F)",
        "subheading_image_quantity": "Every Other H2 (Max 5)",
        "subheading_images_model": "ideogram 3t $.030/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Sonnet (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": False,
        "wordpress_category": "Witchcraft Basics",
        "wordpress_settings": {
            "site_url": "https://witchcraftforbeginners.com",
            "user_name": "MoonlightMystic",
            "category": "Witchcraft Basics",
            "article_status": "draft",
        },
    },

    "manifestandalign.com": {
        "domain": "manifestandalign.com",
        "niche": "Manifestation & Spiritual Growth",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "h2_lower_limit": 4,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Innocent",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "flux pro $.040/img (F)",
        "subheading_image_quantity": "Every 3rd H2 (Max 3)",
        "subheading_images_model": "flux schnell $.003/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": False,
        "wordpress_category": "Manifestation Guides",
        "wordpress_settings": {
            "site_url": "https://manifestandalign.com",
            "user_name": "ManifestMaster",
            "category": "Manifestation Guides",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # LIFESTYLE & FAMILY
    # ═══════════════════════════════════════

    "family-flourish.com": {
        "domain": "family-flourish.com",
        "niche": "Family & Parenting",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "h2_lower_limit": 4,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Lover",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "flux dev $.025/img (F)",
        "subheading_image_quantity": "Every Other H2 (Max 3)",
        "subheading_images_model": "flux schnell $.003/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": False,
        "wordpress_category": "Family Life",
        "wordpress_settings": {
            "site_url": "https://family-flourish.com",
            "user_name": "FamilyGrowthGuide",
            "category": "Family Life",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # KNOWLEDGE & EDUCATION
    # ═══════════════════════════════════════

    "mythicalarchives.com": {
        "domain": "mythicalarchives.com",
        "niche": "Mythology & Folklore",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "h2_lower_limit": 5,
        "ai_outline_quality": "High $$",
        "section_length": "Long",
        "voice": "Third Person (He, She, It, They)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Sage",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "ideogram 3b $.060/img (F)",
        "subheading_image_quantity": "Every Other H2 (Max 5)",
        "subheading_images_model": "ideogram 3t $.030/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Sonnet (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": True,
        "blockquotes": True,
        "literary_devices": True,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": True,
        "wordpress_category": "Mythology",
        "wordpress_settings": {
            "site_url": "https://mythicalarchives.com",
            "user_name": "ArcaneArchivist",
            "category": "Mythology",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # PRODUCT REVIEW SITES
    # ═══════════════════════════════════════

    "wearablegearreviews.com": {
        "domain": "wearablegearreviews.com",
        "niche": "Wearable Tech Reviews",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "h2_lower_limit": 5,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Explorer",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "gpt-image-1 med $.063/img (OA)",
        "subheading_image_quantity": "Every H2 (Max 5)",
        "subheading_images_model": "ideogram 3t $.030/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": True,
        "link_pack": True,
        "wordpress_category": "Wearable Reviews",
        "wordpress_settings": {
            "site_url": "https://wearablegearreviews.com",
            "user_name": "WearableReviewPro",
            "category": "Wearable Reviews",
            "article_status": "draft",
        },
    },

    "pulsegearreviews.com": {
        "domain": "pulsegearreviews.com",
        "niche": "EDC & Tactical Gear Reviews",
        "h2_count": "Automatic",
        "h2_auto_limit": 10,
        "h2_lower_limit": 5,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Outlaw",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "gpt-image-1 low $.016/img (OA)",
        "subheading_image_quantity": "Every H2 (Max 5)",
        "subheading_images_model": "flux dev $.025/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": True,
        "blockquotes": False,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": True,
        "link_pack": True,
        "wordpress_category": "EDC Reviews",
        "wordpress_settings": {
            "site_url": "https://pulsegearreviews.com",
            "user_name": "PulseGearEditor",
            "category": "EDC Reviews",
            "article_status": "draft",
        },
    },

    # ═══════════════════════════════════════
    # HOBBY & NICHE SITES
    # ═══════════════════════════════════════

    "bulletjournals.net": {
        "domain": "bulletjournals.net",
        "niche": "Bullet Journaling & Productivity",
        "h2_count": "Automatic",
        "h2_auto_limit": 8,
        "h2_lower_limit": 4,
        "ai_outline_quality": "High $$",
        "section_length": "Medium",
        "voice": "Second Person (You, Your, Yours)",
        "intro": "Standard Intro",
        "faq": "FAQ + Long Answers",
        "audience_personality": "Creator",
        "ai_model": "Claude-4.5 Sonnet (ANT)",
        "featured_image": "flux pro $.040/img (F)",
        "subheading_image_quantity": "Every Other H2 (Max 5)",
        "subheading_images_model": "flux schnell $.003/img (F)",
        "ai_model_image_prompts": "Claude-4.5 Haiku (ANT)",
        "ai_model_translation": "None",
        "lists": True,
        "tables": False,
        "blockquotes": True,
        "literary_devices": False,
        "enable_h3": True,
        "key_takeaways": True,
        "nuke_ai_words": True,
        "bold_readability": True,
        "disable_skinny_paragraphs": False,
        "disable_active_voice": False,
        "disable_conclusion": False,
        "auto_style": False,
        "automatic_keywords": False,
        "image_prompt_per_h2": False,
        "progress_indicator": True,
        "overwrite_url_cache": False,
        "serp_scraping": False,
        "wordpress_category": "Bullet Journal Ideas",
        "wordpress_settings": {
            "site_url": "https://bulletjournals.net",
            "user_name": "BulletJournalPro",
            "category": "Bullet Journal Ideas",
            "article_status": "draft",
        },
    },
}


def get_preset(domain: str) -> Optional[Dict[str, Any]]:
    """Get preset config for a domain."""
    return SITE_PRESETS.get(domain)

def get_all_domains() -> list:
    """Get list of all configured domains."""
    return list(SITE_PRESETS.keys())

def get_presets_by_niche(niche_keyword: str) -> Dict[str, Dict[str, Any]]:
    """Find presets matching a niche keyword."""
    return {
        domain: config
        for domain, config in SITE_PRESETS.items()
        if niche_keyword.lower() in config.get("niche", "").lower()
    }
