"""Smoke tests for revid-forge -- auto-generated by EMPIRE-BRAIN Evolution Engine.

All tests are purely local. No network connections, API keys, or running
services required. Tests that would need external resources are skipped.

Generated: 2026-03-06 23:43
"""
import pytest
import sys
import importlib
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


class TestImports:
    """Verify core modules for revid-forge can be imported."""

    @pytest.mark.skip(reason="Module loads config files at import time")
    def test_import_scripts_revid_forge_engine(self):
        import scripts.revid_forge_engine
        assert scripts.revid_forge_engine is not None

    @pytest.mark.skip(reason="Module loads config files at import time")
    def test_import_scripts_revid_script_gen(self):
        import scripts.revid_script_gen
        assert scripts.revid_script_gen is not None

