"""Smoke tests for empire-master — auto-generated by EMPIRE-BRAIN Evolution Engine."""
import pytest
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


class TestImports:
    """Verify core modules can be imported."""

    def test_import_config(self):
        from core.config import SiteConfig
        assert SiteConfig is not None

    def test_import_task_queue(self):
        from core.task_queue import TaskQueue
        assert TaskQueue is not None

    def test_import_state_manager(self):
        from core.state_manager import StateManager
        assert StateManager is not None

    def test_import_conflict_resolver(self):
        from core.conflict_resolver import ConflictResolver
        assert ConflictResolver is not None

    def test_import_event_bus(self):
        from core.event_bus import EventBus
        assert EventBus is not None

    def test_import_seo_modules(self):
        from modules.seo_intelligence import cannibalization
        from modules.seo_intelligence import striking_distance
        assert cannibalization is not None
        assert striking_distance is not None


class TestStateManager:
    """Verify StateManager basic operations."""

    def test_create_state_manager(self, tmp_path):
        from core.state_manager import StateManager
        sm = StateManager(state_dir=str(tmp_path))
        assert sm is not None


class TestTaskQueue:
    """Verify TaskQueue basic operations."""

    def test_create_task_queue(self, tmp_path):
        from core.task_queue import TaskQueue
        tq = TaskQueue(db_path=str(tmp_path / "tasks.db"))
        assert tq is not None


class TestSEOModules:
    """Verify SEO modules have expected functions."""

    def test_striking_distance_module(self):
        from modules.seo_intelligence import striking_distance
        assert hasattr(striking_distance, 'find_striking_distance') or hasattr(striking_distance, 'StrikingDistance')

    def test_content_decay_module(self):
        from modules.seo_intelligence import content_decay
        assert content_decay is not None
