"""Color grading presets per niche — hex values, saturation, contrast, warmth."""

COLOR_GRADES = {
    "witchcraft_dark": {
        "name": "Dark Witchcraft",
        "primary": "#1A0A2E",
        "accent": "#C084FC",
        "text": "#F5F0FF",
        "saturation": 0.7,
        "contrast": 1.2,
        "warmth": -0.1,
        "vignette": 0.4,
        "description": "Deep purples and blacks, mystical glow",
    },
    "witchcraft_earthy": {
        "name": "Earthy Witch",
        "primary": "#2D1B0E",
        "accent": "#D4A574",
        "text": "#FFF8F0",
        "saturation": 0.6,
        "contrast": 1.1,
        "warmth": 0.2,
        "vignette": 0.3,
        "description": "Warm browns, candlelight, herbalist aesthetic",
    },
    "mythology_epic": {
        "name": "Epic Mythology",
        "primary": "#0A1628",
        "accent": "#FFD700",
        "text": "#FFFFFF",
        "saturation": 0.9,
        "contrast": 1.3,
        "warmth": 0.0,
        "vignette": 0.2,
        "description": "Deep blues, gold accents, cinematic scope",
    },
    "mythology_ancient": {
        "name": "Ancient Mythology",
        "primary": "#1A1409",
        "accent": "#C9A44A",
        "text": "#F0E6C8",
        "saturation": 0.5,
        "contrast": 1.1,
        "warmth": 0.3,
        "vignette": 0.4,
        "description": "Aged parchment tones, weathered gold",
    },
    "tech_clean": {
        "name": "Clean Tech",
        "primary": "#0F172A",
        "accent": "#38BDF8",
        "text": "#F8FAFC",
        "saturation": 0.8,
        "contrast": 1.2,
        "warmth": -0.15,
        "vignette": 0.1,
        "description": "Cool blues on dark, sharp and modern",
    },
    "tech_neon": {
        "name": "Neon Tech",
        "primary": "#0A0A0A",
        "accent": "#00FF88",
        "text": "#FFFFFF",
        "saturation": 1.2,
        "contrast": 1.4,
        "warmth": -0.2,
        "vignette": 0.3,
        "description": "High contrast neon on black, cyberpunk feel",
    },
    "ai_futuristic": {
        "name": "AI Futuristic",
        "primary": "#0D0221",
        "accent": "#7C3AED",
        "text": "#E0E7FF",
        "saturation": 0.9,
        "contrast": 1.25,
        "warmth": -0.1,
        "vignette": 0.2,
        "description": "Purple/violet AI vibes, digital gradient",
    },
    "news_urgent": {
        "name": "News Urgent",
        "primary": "#1A1A2E",
        "accent": "#E63946",
        "text": "#FFFFFF",
        "saturation": 0.85,
        "contrast": 1.3,
        "warmth": -0.05,
        "vignette": 0.1,
        "description": "Dark background, red accents, breaking news feel",
    },
    "lifestyle_warm": {
        "name": "Lifestyle Warm",
        "primary": "#FFF7ED",
        "accent": "#F97316",
        "text": "#1C1917",
        "saturation": 0.7,
        "contrast": 1.0,
        "warmth": 0.3,
        "vignette": 0.15,
        "description": "Warm oranges, cozy and inviting",
    },
    "lifestyle_pastel": {
        "name": "Lifestyle Pastel",
        "primary": "#FDF2F8",
        "accent": "#EC4899",
        "text": "#1F2937",
        "saturation": 0.5,
        "contrast": 0.9,
        "warmth": 0.1,
        "vignette": 0.1,
        "description": "Soft pastels, feminine, gentle",
    },
    "fitness_intense": {
        "name": "Fitness Intense",
        "primary": "#0F0F0F",
        "accent": "#EF4444",
        "text": "#FFFFFF",
        "saturation": 1.0,
        "contrast": 1.4,
        "warmth": 0.0,
        "vignette": 0.3,
        "description": "High contrast, red accents, aggressive",
    },
    "journal_cozy": {
        "name": "Journal Cozy",
        "primary": "#FFFBEB",
        "accent": "#92400E",
        "text": "#1C1917",
        "saturation": 0.4,
        "contrast": 0.95,
        "warmth": 0.25,
        "vignette": 0.15,
        "description": "Paper-like warmth, vintage stationery feel",
    },
    "manifestation_glow": {
        "name": "Manifestation Glow",
        "primary": "#0C0A1A",
        "accent": "#F59E0B",
        "text": "#FEF3C7",
        "saturation": 0.8,
        "contrast": 1.15,
        "warmth": 0.1,
        "vignette": 0.35,
        "description": "Golden glow on dark, celestial abundance",
    },
    "celebration_festive": {
        "name": "Celebration Festive",
        "primary": "#1A0505",
        "accent": "#DC2626",
        "text": "#FFFFFF",
        "saturation": 1.1,
        "contrast": 1.2,
        "warmth": 0.15,
        "vignette": 0.2,
        "description": "Rich reds, gold sparkles, holiday cheer",
    },
    "nature_green": {
        "name": "Nature Green",
        "primary": "#022C22",
        "accent": "#10B981",
        "text": "#ECFDF5",
        "saturation": 0.75,
        "contrast": 1.1,
        "warmth": 0.05,
        "vignette": 0.2,
        "description": "Deep greens, earth tones, organic",
    },
    "money_green": {
        "name": "Money Green",
        "primary": "#042F2E",
        "accent": "#34D399",
        "text": "#F0FDF4",
        "saturation": 0.85,
        "contrast": 1.2,
        "warmth": -0.05,
        "vignette": 0.15,
        "description": "Financial green, wealth and growth",
    },
}

# Niche ID -> default color grade
NICHE_COLOR_MAP = {
    "witchcraftforbeginners": "witchcraft_dark",
    "moonrituallibrary": "witchcraft_dark",
    "manifestandalign": "manifestation_glow",
    "mythicalarchives": "mythology_epic",
    "smarthomewizards": "tech_clean",
    "smarthomegearreviews": "tech_clean",
    "pulsegearreviews": "fitness_intense",
    "wearablegearreviews": "tech_neon",
    "aidiscoverydigest": "ai_futuristic",
    "aiinactionhub": "tech_clean",
    "clearainews": "news_urgent",
    "wealthfromai": "money_green",
    "bulletjournals": "journal_cozy",
    "theconnectedhaven": "lifestyle_warm",
    "familyflourish": "lifestyle_pastel",
    "celebrationseason": "celebration_festive",
}


def get_color_grade(key: str = None, niche: str = None) -> dict:
    """Get color grade by key or niche."""
    if niche and niche in NICHE_COLOR_MAP:
        key = NICHE_COLOR_MAP[niche]
    if key and key in COLOR_GRADES:
        return COLOR_GRADES[key]
    return COLOR_GRADES["tech_clean"]
