"""40+ music mood categories with free source recommendations."""

MUSIC_MOODS = {
    # ── Mystical / Spiritual ──
    "dark_ambient": {
        "name": "Dark Ambient",
        "energy": "low",
        "bpm_range": (60, 80),
        "niches": ["witchcraft", "mythology", "horror"],
        "keywords": ["drone", "reverb", "atmospheric", "haunting"],
        "instruments": ["synth pad", "singing bowl", "cello"],
    },
    "ethereal": {
        "name": "Ethereal / Celestial",
        "energy": "low",
        "bpm_range": (70, 90),
        "niches": ["witchcraft", "manifestation", "meditation"],
        "keywords": ["angelic", "floating", "shimmering", "dreamy"],
        "instruments": ["harp", "choir", "glass", "pad"],
    },
    "ritual_drums": {
        "name": "Ritual Drums",
        "energy": "medium",
        "bpm_range": (80, 120),
        "niches": ["witchcraft", "mythology"],
        "keywords": ["tribal", "primal", "rhythmic", "ceremonial"],
        "instruments": ["frame drum", "djembe", "timpani"],
    },
    "celtic": {
        "name": "Celtic / Folk",
        "energy": "medium",
        "bpm_range": (100, 130),
        "niches": ["witchcraft", "mythology"],
        "keywords": ["folk", "fiddle", "jig", "pastoral"],
        "instruments": ["fiddle", "tin whistle", "bodhran", "harp"],
    },
    "meditation_bowl": {
        "name": "Meditation Bowls",
        "energy": "very_low",
        "bpm_range": (0, 60),
        "niches": ["manifestation", "meditation", "wellness"],
        "keywords": ["healing", "resonance", "calm", "mindful"],
        "instruments": ["singing bowl", "chime", "bell"],
    },
    # ── Epic / Cinematic ──
    "epic_orchestral": {
        "name": "Epic Orchestral",
        "energy": "high",
        "bpm_range": (100, 140),
        "niches": ["mythology", "documentary"],
        "keywords": ["cinematic", "heroic", "sweeping", "dramatic"],
        "instruments": ["orchestra", "choir", "brass", "percussion"],
    },
    "cinematic_tension": {
        "name": "Cinematic Tension",
        "energy": "medium",
        "bpm_range": (80, 110),
        "niches": ["mythology", "documentary", "true_crime"],
        "keywords": ["suspense", "building", "dark", "pulsing"],
        "instruments": ["strings", "synth", "timpani"],
    },
    "trailer_impact": {
        "name": "Trailer / Impact",
        "energy": "very_high",
        "bpm_range": (110, 150),
        "niches": ["mythology", "tech"],
        "keywords": ["hits", "risers", "impacts", "build-drop"],
        "instruments": ["sub bass", "brass stabs", "percussion"],
    },
    # ── Tech / Modern ──
    "synth_wave": {
        "name": "Synthwave / Retro",
        "energy": "medium",
        "bpm_range": (100, 130),
        "niches": ["tech", "ai_news", "gaming"],
        "keywords": ["retro", "neon", "80s", "digital"],
        "instruments": ["synth", "arpeggiator", "drum machine"],
    },
    "lo_fi": {
        "name": "Lo-Fi Chill",
        "energy": "low",
        "bpm_range": (70, 90),
        "niches": ["tutorial", "lifestyle", "study"],
        "keywords": ["chill", "relaxed", "study", "warm"],
        "instruments": ["vinyl crackle", "Rhodes", "soft drums"],
    },
    "tech_minimal": {
        "name": "Tech Minimal",
        "energy": "medium",
        "bpm_range": (100, 125),
        "niches": ["tech", "ai_news", "product_review"],
        "keywords": ["clean", "modern", "digital", "precise"],
        "instruments": ["synth", "click", "pad", "glitch"],
    },
    "corporate_upbeat": {
        "name": "Corporate Upbeat",
        "energy": "medium",
        "bpm_range": (110, 130),
        "niches": ["tech", "business", "tutorial"],
        "keywords": ["positive", "professional", "motivational"],
        "instruments": ["acoustic guitar", "claps", "piano", "light drums"],
    },
    "futuristic": {
        "name": "Futuristic / Sci-Fi",
        "energy": "medium",
        "bpm_range": (90, 120),
        "niches": ["ai_news", "tech", "innovation"],
        "keywords": ["futuristic", "space", "innovation", "evolving"],
        "instruments": ["synth pad", "vocoder", "glitch", "sub bass"],
    },
    # ── Energetic / Upbeat ──
    "pop_upbeat": {
        "name": "Pop Upbeat",
        "energy": "high",
        "bpm_range": (115, 135),
        "niches": ["lifestyle", "fashion", "celebration"],
        "keywords": ["happy", "catchy", "energetic", "bouncy"],
        "instruments": ["synth", "claps", "bass", "vocals"],
    },
    "hip_hop_trap": {
        "name": "Hip Hop / Trap",
        "energy": "high",
        "bpm_range": (130, 160),
        "niches": ["hustle", "motivation", "fitness"],
        "keywords": ["hard", "bass", "swagger", "street"],
        "instruments": ["808", "hi-hat rolls", "synth lead"],
    },
    "edm_drop": {
        "name": "EDM / Drop",
        "energy": "very_high",
        "bpm_range": (126, 150),
        "niches": ["fitness", "extreme", "party"],
        "keywords": ["build", "drop", "euphoric", "massive"],
        "instruments": ["synth", "kick", "riser", "super saw"],
    },
    "funk_groove": {
        "name": "Funk / Groove",
        "energy": "high",
        "bpm_range": (100, 120),
        "niches": ["lifestyle", "cooking", "diy"],
        "keywords": ["groovy", "funky", "playful", "smooth"],
        "instruments": ["bass guitar", "wah guitar", "brass", "clav"],
    },
    # ── Calm / Gentle ──
    "acoustic_warm": {
        "name": "Acoustic Warm",
        "energy": "low",
        "bpm_range": (80, 110),
        "niches": ["lifestyle", "family", "journal"],
        "keywords": ["warm", "gentle", "organic", "heartfelt"],
        "instruments": ["acoustic guitar", "ukulele", "soft strings"],
    },
    "piano_emotional": {
        "name": "Piano Emotional",
        "energy": "low",
        "bpm_range": (60, 90),
        "niches": ["story", "memorial", "reflection"],
        "keywords": ["emotional", "beautiful", "nostalgic", "moving"],
        "instruments": ["piano", "strings", "celesta"],
    },
    "nature_ambient": {
        "name": "Nature Ambient",
        "energy": "very_low",
        "bpm_range": (0, 70),
        "niches": ["wellness", "meditation", "nature"],
        "keywords": ["rain", "forest", "ocean", "birds"],
        "instruments": ["field recording", "pad", "wind chimes"],
    },
    "jazz_smooth": {
        "name": "Smooth Jazz",
        "energy": "low",
        "bpm_range": (80, 110),
        "niches": ["lifestyle", "food", "travel"],
        "keywords": ["smooth", "sophisticated", "laid-back"],
        "instruments": ["saxophone", "piano", "upright bass", "brush drums"],
    },
    # ── Niche-specific ──
    "witchcraft_ambient": {
        "name": "Witchcraft Ambient",
        "energy": "low",
        "bpm_range": (60, 85),
        "niches": ["witchcraft"],
        "keywords": ["mystical", "candlelit", "herbal", "nocturnal"],
        "instruments": ["pad", "singing bowl", "chime", "whisper"],
    },
    "mythology_epic": {
        "name": "Mythology Epic",
        "energy": "high",
        "bpm_range": (90, 130),
        "niches": ["mythology"],
        "keywords": ["ancient", "epic", "storytelling", "mythic"],
        "instruments": ["oud", "orchestra", "choir", "war drums"],
    },
    "smart_home_tech": {
        "name": "Smart Home Tech",
        "energy": "medium",
        "bpm_range": (100, 120),
        "niches": ["smart_home", "tech"],
        "keywords": ["clean", "innovation", "connected", "modern"],
        "instruments": ["synth", "click", "subtle bass"],
    },
    "fitness_pump": {
        "name": "Fitness Pump",
        "energy": "very_high",
        "bpm_range": (130, 160),
        "niches": ["fitness", "gear_review"],
        "keywords": ["powerful", "intense", "driven", "sweat"],
        "instruments": ["808", "heavy kick", "power synth"],
    },
    "journal_cozy": {
        "name": "Journal / Cozy",
        "energy": "very_low",
        "bpm_range": (70, 95),
        "niches": ["journal", "lifestyle", "crafts"],
        "keywords": ["cozy", "soft", "creative", "indie"],
        "instruments": ["glockenspiel", "acoustic guitar", "soft piano"],
    },
    "news_urgent": {
        "name": "News Urgent",
        "energy": "medium",
        "bpm_range": (110, 130),
        "niches": ["news", "ai_news"],
        "keywords": ["breaking", "urgent", "developing", "pulse"],
        "instruments": ["snare roll", "synth stab", "timpani", "bass pulse"],
    },
    "motivational": {
        "name": "Motivational",
        "energy": "high",
        "bpm_range": (100, 130),
        "niches": ["hustle", "business", "self_improvement"],
        "keywords": ["inspiring", "powerful", "uplifting", "triumphant"],
        "instruments": ["piano", "strings", "drums build", "brass"],
    },
    "horror_dark": {
        "name": "Horror / Dark",
        "energy": "medium",
        "bpm_range": (70, 100),
        "niches": ["horror", "creepy", "dark_mythology"],
        "keywords": ["creepy", "tense", "disturbing", "eerie"],
        "instruments": ["dissonant strings", "reverse reverb", "low drone"],
    },
    "playful_quirky": {
        "name": "Playful / Quirky",
        "energy": "medium",
        "bpm_range": (110, 140),
        "niches": ["kids", "diy", "comedy"],
        "keywords": ["fun", "silly", "bouncy", "cheerful"],
        "instruments": ["marimba", "pizzicato", "whistle", "claps"],
    },
    "world_arabic": {
        "name": "Arabic / Middle Eastern",
        "energy": "medium",
        "bpm_range": (90, 120),
        "niches": ["mythology", "cultural"],
        "keywords": ["exotic", "desert", "ancient", "ornate"],
        "instruments": ["oud", "darbuka", "ney", "qanun"],
    },
    "world_asian": {
        "name": "Asian / Eastern",
        "energy": "low",
        "bpm_range": (70, 100),
        "niches": ["mythology", "meditation", "cultural"],
        "keywords": ["zen", "serene", "ancient", "flowing"],
        "instruments": ["koto", "shakuhachi", "erhu", "taiko"],
    },
    "world_norse": {
        "name": "Norse / Viking",
        "energy": "high",
        "bpm_range": (90, 130),
        "niches": ["mythology", "viking"],
        "keywords": ["battle", "frost", "saga", "warrior"],
        "instruments": ["tagelharpa", "war drum", "horn", "chant"],
    },
    "romantic": {
        "name": "Romantic",
        "energy": "low",
        "bpm_range": (70, 100),
        "niches": ["love", "wedding", "valentine"],
        "keywords": ["love", "tender", "sweet", "intimate"],
        "instruments": ["strings", "piano", "harp", "flute"],
    },
    "holiday_festive": {
        "name": "Holiday / Festive",
        "energy": "high",
        "bpm_range": (110, 140),
        "niches": ["celebration", "holiday", "seasonal"],
        "keywords": ["festive", "joyful", "celebration", "sparkle"],
        "instruments": ["bells", "orchestra", "choir", "sleigh bells"],
    },
}

# Niche ID -> preferred moods
NICHE_MOOD_MAP = {
    "witchcraftforbeginners": ["witchcraft_ambient", "dark_ambient", "ethereal", "ritual_drums"],
    "moonrituallibrary": ["meditation_bowl", "ethereal", "dark_ambient"],
    "manifestandalign": ["ethereal", "meditation_bowl", "acoustic_warm"],
    "mythicalarchives": ["mythology_epic", "epic_orchestral", "cinematic_tension"],
    "smarthomewizards": ["smart_home_tech", "tech_minimal", "corporate_upbeat"],
    "smarthomegearreviews": ["tech_minimal", "corporate_upbeat"],
    "pulsegearreviews": ["fitness_pump", "hip_hop_trap", "motivational"],
    "wearablegearreviews": ["tech_minimal", "synth_wave"],
    "aidiscoverydigest": ["futuristic", "news_urgent", "tech_minimal"],
    "aiinactionhub": ["tech_minimal", "corporate_upbeat", "lo_fi"],
    "clearainews": ["news_urgent", "futuristic", "tech_minimal"],
    "wealthfromai": ["motivational", "hip_hop_trap", "corporate_upbeat"],
    "bulletjournals": ["journal_cozy", "lo_fi", "acoustic_warm"],
    "theconnectedhaven": ["acoustic_warm", "lo_fi", "piano_emotional"],
    "familyflourish": ["acoustic_warm", "playful_quirky", "pop_upbeat"],
    "celebrationseason": ["holiday_festive", "pop_upbeat", "playful_quirky"],
}


def get_mood(key: str) -> dict:
    """Get mood data by key."""
    return MUSIC_MOODS.get(key, MUSIC_MOODS["lo_fi"])


def get_mood_for_niche(niche: str) -> list:
    """Get preferred mood keys for a niche."""
    return NICHE_MOOD_MAP.get(niche, ["lo_fi", "corporate_upbeat"])
