"""16 niche profiles with visual DNA, content pillars, and brand voice."""

NICHE_PROFILES = {
    "witchcraftforbeginners": {
        "name": "Witchcraft for Beginners",
        "brand": "Witchcraft for Beginners",
        "category": "witchcraft",
        "content_pillars": ["spells", "herbs", "moon_rituals", "divination", "sabbats"],
        "visual_dna": {
            "aesthetic": "dark mystical",
            "key_visuals": ["candles", "herbs", "crystals", "moon", "cauldron", "smoke", "altar"],
            "color_palette": ["#1A0A2E", "#C084FC", "#4A1D8E", "#F5F0FF"],
            "textures": ["candlelight glow", "smoke wisps", "starfield"],
            "avoid": ["cartoon witch hats", "halloween clichés", "bright neon"],
        },
        "voice": {
            "tone": "mystical, warm, inviting",
            "personality": "wise guide, gentle teacher",
            "vocab": ["intention", "correspondences", "manifest", "sacred", "ritual"],
            "avoid": ["scary", "hex", "curse", "dark magic"],
        },
        "voice_card": {
            "identity": "a practicing witch who's been at this for twenty years and remembers what it felt like to start",
            "emotional_register": "warm and grounded, like a trusted friend sharing secrets by candlelight",
            "viewer_relationship": "you're guiding someone who just discovered the path — be the mentor you wish you had",
            "speaking_style": "gentle pace, short sentences for emphasis, longer ones for atmosphere. pause before revealing something important.",
            "forbidden_tones": ["academic", "lecturing", "preachy", "Halloween-spooky", "new age guru"],
            "signature_phrases": ["here's what nobody tells beginners", "the real magic is simpler than you think", "try this tonight", "this is the part that changes everything"],
            "never_say": ["harness the power", "unlock your potential", "on this magical journey", "let me explain", "it's important to note"],
        },
        "hashtags": ["#witchcraft", "#witchtok", "#babywitch", "#spellwork", "#moonritual",
                      "#witchesofinstagram", "#crystalmagic", "#herbalism", "#divination"],
        "cta_templates": [
            "Follow for daily witchcraft tips",
            "Save this spell for later",
            "Comment your moon sign below",
        ],
        "best_formats": ["tutorial", "listicle", "story"],
    },
    "smarthomewizards": {
        "name": "Smart Home Wizards",
        "brand": "Smart Home Wizards",
        "category": "tech",
        "content_pillars": ["smart_home", "automation", "reviews", "diy", "comparison"],
        "visual_dna": {
            "aesthetic": "clean tech",
            "key_visuals": ["smart devices", "app interfaces", "modern home", "LED lights"],
            "color_palette": ["#0F172A", "#38BDF8", "#1E40AF", "#F8FAFC"],
            "textures": ["glass", "brushed metal", "soft glow"],
            "avoid": ["cluttered rooms", "tangled wires", "outdated tech"],
        },
        "voice": {
            "tone": "enthusiastic, clear, helpful",
            "personality": "tech-savvy neighbor",
            "vocab": ["automation", "smart", "integrate", "ecosystem", "setup"],
            "avoid": ["jargon overload", "elitist", "gatekeeping"],
        },
        "voice_card": {
            "identity": "your neighbor who set up a ridiculously smart house and actually knows what works versus what's hype",
            "emotional_register": "excited but honest, like showing off a build you're proud of",
            "viewer_relationship": "you're saving them from buying the wrong thing and showing them what actually works",
            "speaking_style": "fast-paced, punchy. name the product, say what it does, move on. no fluff.",
            "forbidden_tones": ["salesy", "infomercial", "overly technical", "corporate"],
            "signature_phrases": ["okay so here's the thing", "this one's a no-brainer", "I tested this for a month", "skip this one, trust me"],
            "never_say": ["revolutionary product", "game-changing device", "in the world of smart home", "as technology evolves"],
        },
        "hashtags": ["#smarthome", "#homeautomation", "#alexatips", "#googlehome",
                      "#smarthometech", "#iot", "#techreview"],
        "cta_templates": [
            "Follow for smart home tips",
            "Save this setup guide",
            "Comment your favorite smart device",
        ],
        "best_formats": ["review", "tutorial", "comparison"],
    },
    "mythicalarchives": {
        "name": "Mythical Archives",
        "brand": "Mythical Archives",
        "category": "mythology",
        "content_pillars": ["mythology", "legends", "ancient_history", "folklore", "deities"],
        "visual_dna": {
            "aesthetic": "epic cinematic",
            "key_visuals": ["ancient temples", "gods", "battles", "artifacts", "dragons"],
            "color_palette": ["#0A1628", "#FFD700", "#8B0000", "#FFFFFF"],
            "textures": ["marble", "gold leaf", "storm clouds", "fire"],
            "avoid": ["cartoon style", "modern elements", "low quality"],
        },
        "voice": {
            "tone": "epic, dramatic, authoritative",
            "personality": "master storyteller",
            "vocab": ["ancient", "legendary", "mythic", "divine", "eternal"],
            "avoid": ["casual slang", "modern references", "simplistic"],
        },
        "voice_card": {
            "identity": "a campfire storyteller who studied ancient texts for decades and tells these stories like they happened yesterday",
            "emotional_register": "dramatic but grounded, epic without being cheesy — the weight of three thousand years in every sentence",
            "viewer_relationship": "revealing hidden knowledge, pulling back the curtain on stories everyone thinks they know",
            "speaking_style": "short punches for impact, longer sentences for world-building. dramatic pauses before reveals. rhythm changes with tension.",
            "forbidden_tones": ["academic paper", "textbook", "Wikipedia summary", "dry historian"],
            "signature_phrases": ["here's the part nobody talks about", "this story is older than civilization itself", "and that's when everything changed", "but the real story? it's stranger than the myth"],
            "never_say": ["throughout history", "it is worth noting", "scholars believe", "in ancient times people believed", "furthermore"],
        },
        "hashtags": ["#mythology", "#greekmythology", "#myths", "#ancienthistory",
                      "#folklore", "#legends", "#mythicalcreatures"],
        "cta_templates": [
            "Subscribe for mythological stories",
            "Which mythology should we explore next?",
            "Follow for daily mythology",
        ],
        "best_formats": ["story", "listicle", "educational"],
    },
    "bulletjournals": {
        "name": "Bullet Journals",
        "brand": "Bullet Journals",
        "category": "lifestyle",
        "content_pillars": ["journal_setup", "spreads", "organization", "creative", "planning"],
        "visual_dna": {
            "aesthetic": "cozy creative",
            "key_visuals": ["notebooks", "washi tape", "pens", "desk setup", "hands drawing"],
            "color_palette": ["#FFFBEB", "#92400E", "#F59E0B", "#1C1917"],
            "textures": ["paper grain", "watercolor", "ink splatter"],
            "avoid": ["digital only", "messy", "clinical"],
        },
        "voice": {
            "tone": "gentle, encouraging, creative",
            "personality": "creative friend",
            "vocab": ["spread", "layout", "tracker", "creative", "organize"],
            "avoid": ["perfectionist pressure", "complicated", "overwhelming"],
        },
        "voice_card": {
            "identity": "a journaling addict who's filled dozens of notebooks and loves showing people how to start without being perfect",
            "emotional_register": "cozy and encouraging, like a friend at a coffee shop showing their latest spread",
            "viewer_relationship": "making creativity feel accessible, killing the perfectionism that stops people from starting",
            "speaking_style": "relaxed, conversational. short tips. lots of 'you can' and 'try this'. no pressure.",
            "forbidden_tones": ["perfectionist", "preachy", "overly artsy", "intimidating"],
            "signature_phrases": ["this takes five minutes", "messy is fine, seriously", "here's the trick", "I do this every single week"],
            "never_say": ["elevate your journaling experience", "transform your productivity", "embrace the art of", "let me walk you through"],
        },
        "hashtags": ["#bujo", "#bulletjournal", "#journaling", "#planner",
                      "#bulletjournaling", "#bujoideas", "#journalspread"],
        "cta_templates": [
            "Save this spread idea",
            "Show me your journal!",
            "Follow for bujo inspo",
        ],
        "best_formats": ["tutorial", "listicle", "behind_the_scenes"],
    },
    "wealthfromai": {
        "name": "Wealth from AI",
        "brand": "Wealth from AI",
        "category": "business",
        "content_pillars": ["ai_income", "tools", "automation", "side_hustle", "productivity"],
        "visual_dna": {
            "aesthetic": "money tech",
            "key_visuals": ["charts", "AI interfaces", "money", "laptops", "dashboards"],
            "color_palette": ["#042F2E", "#34D399", "#10B981", "#F0FDF4"],
            "textures": ["matrix code", "holographic", "clean gradient"],
            "avoid": ["get rich quick", "lambos", "fake luxury"],
        },
        "voice": {
            "tone": "confident, actionable, fast-paced",
            "personality": "AI hustler, results-focused",
            "vocab": ["leverage", "scale", "automate", "monetize", "passive income"],
            "avoid": ["hype", "guaranteed", "overnight"],
        },
        "voice_card": {
            "identity": "someone who actually makes money with AI tools every day, not a guru selling courses about it",
            "emotional_register": "direct and no-nonsense, excited about real results, zero patience for fluff",
            "viewer_relationship": "sharing exact playbooks that work, treating the viewer like a peer not a student",
            "speaking_style": "fast. direct. every sentence has a number or a tool name. no filler. no disclaimers.",
            "forbidden_tones": ["guru", "get-rich-quick hype", "vague motivational", "passive aggressive"],
            "signature_phrases": ["I tested this last week", "here's the exact setup", "this made me four hundred dollars", "stop overcomplicating it"],
            "never_say": ["unlock your potential", "the key to success", "in today's digital landscape", "leverage the power of"],
        },
        "hashtags": ["#aitools", "#makemoneyonline", "#aimoney", "#sidehustle",
                      "#passiveincome", "#aiautomation", "#chatgpt"],
        "cta_templates": [
            "Follow for AI money tips",
            "Comment 'AI' for the full guide",
            "Save this before it blows up",
        ],
        "best_formats": ["tutorial", "listicle", "review"],
    },
    "aidiscoverydigest": {
        "name": "AI Discovery Digest",
        "brand": "AI Discovery Digest",
        "category": "ai_news",
        "content_pillars": ["ai_news", "tools", "breakthroughs", "tutorials", "analysis"],
        "visual_dna": {
            "aesthetic": "futuristic",
            "key_visuals": ["AI visuals", "neural networks", "robots", "data", "screens"],
            "color_palette": ["#0D0221", "#7C3AED", "#A78BFA", "#E0E7FF"],
            "textures": ["digital grid", "particle effects", "hologram"],
            "avoid": ["Terminator clichés", "fear-mongering", "dated tech"],
        },
        "voice": {
            "tone": "informed, exciting, accessible",
            "personality": "AI-savvy journalist",
            "vocab": ["breakthrough", "disrupting", "model", "benchmark", "intelligence"],
            "avoid": ["doom", "replace all jobs", "too technical"],
        },
        "voice_card": {
            "identity": "an AI insider who actually builds with these tools and cuts through the hype to tell you what matters",
            "emotional_register": "genuinely excited about real breakthroughs, skeptical of hype, zero tolerance for buzzwords",
            "viewer_relationship": "you're the friend who explains AI news in plain english over drinks",
            "speaking_style": "lead with the impact, not the technical details. short declarative sentences. name names.",
            "forbidden_tones": ["fear-mongering", "overly academic", "breathless hype", "condescending"],
            "signature_phrases": ["here's why this actually matters", "ignore the headlines, here's what happened", "this is the one to watch", "okay this one's actually big"],
            "never_say": ["in the rapidly evolving landscape", "it remains to be seen", "the implications are profound", "artificial intelligence continues to"],
        },
        "hashtags": ["#ainews", "#artificialintelligence", "#aitools", "#machinelearning",
                      "#chatgpt", "#aiupdate", "#techinnovation"],
        "cta_templates": [
            "Follow for daily AI updates",
            "Save this AI breakdown",
            "Which AI tool surprised you most?",
        ],
        "best_formats": ["news", "listicle", "comparison"],
    },
    "aiinactionhub": {
        "name": "AI in Action Hub",
        "brand": "AI in Action Hub",
        "category": "tech",
        "content_pillars": ["tutorials", "workflows", "tools", "automation", "integration"],
        "visual_dna": {
            "aesthetic": "clean tutorial",
            "key_visuals": ["screen recordings", "workflow diagrams", "before/after"],
            "color_palette": ["#0F172A", "#38BDF8", "#06B6D4", "#F8FAFC"],
            "textures": ["flat design", "gradient", "clean lines"],
            "avoid": ["cluttered UI", "too fast", "no context"],
        },
        "voice": {
            "tone": "practical, step-by-step, encouraging",
            "personality": "helpful tutor",
            "vocab": ["implement", "step", "workflow", "integrate", "prompt"],
            "avoid": ["gatekeeping", "assuming knowledge", "rush"],
        },
        "voice_card": {
            "identity": "a builder who ships real AI workflows every week and shows you exactly how, step by step",
            "emotional_register": "patient and practical, like pair-programming with a friend who's done this before",
            "viewer_relationship": "walking alongside them, not lecturing from above. they'll have this working in ten minutes.",
            "speaking_style": "numbered steps. clear actions. 'do this, then this, then this.' show don't tell.",
            "forbidden_tones": ["condescending", "gatekeeping", "overly theoretical", "vague"],
            "signature_phrases": ["step one, open this", "takes about three minutes", "copy this exact prompt", "here's what most tutorials skip"],
            "never_say": ["in this comprehensive tutorial", "before we begin let me explain", "it's crucial to understand", "let us explore"],
        },
        "hashtags": ["#aitutorial", "#aiworkflow", "#chatgpt", "#aitools",
                      "#productivity", "#automation"],
        "cta_templates": [
            "Follow for AI tutorials",
            "Save this workflow",
            "Try this and share your results",
        ],
        "best_formats": ["tutorial", "comparison", "review"],
    },
    "pulsegearreviews": {
        "name": "Pulse Gear Reviews",
        "brand": "Pulse Gear Reviews",
        "category": "fitness",
        "content_pillars": ["fitness_tech", "wearables", "workout_gear", "reviews", "comparison"],
        "visual_dna": {
            "aesthetic": "fitness intense",
            "key_visuals": ["workout", "gym", "devices on wrist", "data screens"],
            "color_palette": ["#0F0F0F", "#EF4444", "#F97316", "#FFFFFF"],
            "textures": ["sweat", "rubber", "gym floor"],
            "avoid": ["sedentary", "boring", "static"],
        },
        "voice": {
            "tone": "energetic, honest, data-driven",
            "personality": "fitness tech reviewer",
            "vocab": ["performance", "accuracy", "battery", "comfort", "tracking"],
            "avoid": ["lazy", "fake hype", "biased"],
        },
        "voice_card": {
            "identity": "a runner and lifter who tests every piece of fitness tech on real workouts, not on a desk",
            "emotional_register": "high energy but brutally honest, hyped when something works, blunt when it doesn't",
            "viewer_relationship": "saving them money and time, giving the verdict a friend would give before they buy",
            "speaking_style": "fast cuts between points. numbers and comparisons. 'this versus that.' decisive.",
            "forbidden_tones": ["boring", "corporate review", "wishy-washy", "sponsored-sounding"],
            "signature_phrases": ["I wore this for thirty days straight", "here's where it falls apart", "worth every dollar", "save your money on this one"],
            "never_say": ["in the fitness industry", "it boasts impressive features", "a testament to innovation", "let me break down the specifications"],
        },
        "hashtags": ["#fitnesstech", "#fitnessgadgets", "#gearreview",
                      "#fitnesstracker", "#workout", "#healthtech"],
        "cta_templates": [
            "Follow for honest gear reviews",
            "Comment your favorite fitness tracker",
            "Save this comparison",
        ],
        "best_formats": ["review", "comparison", "listicle"],
    },
    "wearablegearreviews": {
        "name": "Wearable Gear Reviews",
        "brand": "Wearable Gear Reviews",
        "category": "tech",
        "content_pillars": ["wearables", "smartwatches", "earbuds", "reviews", "comparison"],
        "visual_dna": {
            "aesthetic": "neon tech",
            "key_visuals": ["wearable devices", "close-ups", "lifestyle shots", "UI"],
            "color_palette": ["#0A0A0A", "#00FF88", "#3B82F6", "#FFFFFF"],
            "textures": ["glass", "silicon", "LED glow"],
            "avoid": ["cheap feel", "outdated products"],
        },
        "voice": {
            "tone": "balanced, thorough, tech-savvy",
            "personality": "trusted tech reviewer",
            "vocab": ["specs", "build quality", "value", "ecosystem", "upgrade"],
            "avoid": ["fanboy", "clickbait", "rushing"],
        },
        "voice_card": {
            "identity": "a tech reviewer who wears every device for at least two weeks before saying a word about it",
            "emotional_register": "measured and confident, genuinely impressed when warranted, unflinching when not",
            "viewer_relationship": "the review they trust before spending their money, no affiliate bias",
            "speaking_style": "structured comparisons. 'this does X, that does Y, here's which one wins.' clear verdicts.",
            "forbidden_tones": ["fanboy", "sponsored feel", "wishy-washy", "overly enthusiastic about everything"],
            "signature_phrases": ["after two weeks on my wrist", "here's the honest truth", "for the price? absolutely", "pass on this one"],
            "never_say": ["in the wearable space", "a paradigm shift", "boasts an impressive array of", "it's worth mentioning that"],
        },
        "hashtags": ["#wearabletech", "#smartwatch", "#techreview",
                      "#gadgets", "#wearables", "#techgear"],
        "cta_templates": [
            "Follow for wearable reviews",
            "Which do you prefer? Comment below",
            "Save for your next purchase",
        ],
        "best_formats": ["review", "comparison", "listicle"],
    },
    "smarthomegearreviews": {
        "name": "Smart Home Gear Reviews",
        "brand": "Smart Home Gear Reviews",
        "category": "tech",
        "content_pillars": ["smart_home", "product_reviews", "setup_guides", "comparison"],
        "visual_dna": {
            "aesthetic": "clean tech",
            "key_visuals": ["smart home devices", "app interfaces", "installations"],
            "color_palette": ["#0F172A", "#38BDF8", "#1E40AF", "#F8FAFC"],
            "textures": ["clean surfaces", "ambient light", "modern interiors"],
            "avoid": ["messy wiring", "outdated tech", "dark rooms"],
        },
        "voice": {
            "tone": "expert, detailed, helpful",
            "personality": "hands-on tech expert",
            "vocab": ["integration", "compatibility", "setup", "value", "smart"],
            "avoid": ["too technical", "overwhelming", "boring"],
        },
        "voice_card": {
            "identity": "a smart home installer who's set up hundreds of homes and knows exactly what breaks and what lasts",
            "emotional_register": "knowledgeable and direct, like getting advice from the pro before you make a purchase",
            "viewer_relationship": "the expert friend they consult before every purchase, honest about what's worth it",
            "speaking_style": "product name first, verdict fast. comparisons are direct. 'A does this better, B does that better.'",
            "forbidden_tones": ["boring spec sheet", "corporate", "sales pitch", "indecisive"],
            "signature_phrases": ["I've installed over a hundred of these", "here's what breaks first", "best value right now", "don't bother with this one"],
            "never_say": ["in the smart home ecosystem", "boasts seamless integration", "a worthy addition to", "it's important to consider"],
        },
        "hashtags": ["#smarthomegear", "#smarthomereview", "#hometech",
                      "#smartdevice", "#techreview"],
        "cta_templates": [
            "Follow for smart home reviews",
            "Save this buying guide",
            "Comment your smart home setup",
        ],
        "best_formats": ["review", "tutorial", "comparison"],
    },
    "clearainews": {
        "name": "Clear AI News",
        "brand": "Clear AI News",
        "category": "ai_news",
        "content_pillars": ["ai_news", "explainers", "industry", "predictions", "ethics"],
        "visual_dna": {
            "aesthetic": "news urgent",
            "key_visuals": ["news graphics", "AI visuals", "data charts", "headlines"],
            "color_palette": ["#1A1A2E", "#E63946", "#457B9D", "#FFFFFF"],
            "textures": ["news ticker", "glass panel", "digital overlay"],
            "avoid": ["boring", "text-only", "fear-mongering"],
        },
        "voice": {
            "tone": "authoritative, clear, fast-paced",
            "personality": "AI news anchor",
            "vocab": ["breaking", "developing", "impact", "industry", "regulation"],
            "avoid": ["sensational", "doom", "too casual"],
        },
        "voice_card": {
            "identity": "a tech journalist who reads every paper and press release so you don't have to",
            "emotional_register": "urgent but measured, like a trusted anchor who gets to the point",
            "viewer_relationship": "their go-to source for what just happened in AI, explained in thirty seconds",
            "speaking_style": "lead with the news. one sentence for what happened. one for why it matters. move on.",
            "forbidden_tones": ["sensational", "clickbait", "fear-mongering", "rambling"],
            "signature_phrases": ["here's what just dropped", "this affects you if", "the real story here", "thirty seconds, here's what you need"],
            "never_say": ["in a groundbreaking development", "the AI landscape continues to evolve", "experts weigh in on", "it remains to be seen"],
        },
        "hashtags": ["#ainews", "#artificialintelligence", "#techbreaking",
                      "#aiindustry", "#ainewsupdate"],
        "cta_templates": [
            "Follow for AI news daily",
            "What do you think about this?",
            "Share this update",
        ],
        "best_formats": ["news", "educational", "listicle"],
    },
    "theconnectedhaven": {
        "name": "The Connected Haven",
        "brand": "The Connected Haven",
        "category": "lifestyle",
        "content_pillars": ["family_tech", "productivity", "home", "balance", "tips"],
        "visual_dna": {
            "aesthetic": "warm lifestyle",
            "key_visuals": ["family", "cozy home", "laptops", "organization"],
            "color_palette": ["#FFF7ED", "#F97316", "#EA580C", "#1C1917"],
            "textures": ["wood grain", "soft fabric", "warm light"],
            "avoid": ["cold", "sterile", "chaotic"],
        },
        "voice": {
            "tone": "warm, relatable, supportive",
            "personality": "helpful friend",
            "vocab": ["connect", "balance", "simplify", "family", "together"],
            "avoid": ["preachy", "guilt-tripping", "judgmental"],
        },
        "voice_card": {
            "identity": "a parent who figured out how to make tech work for the family instead of against it",
            "emotional_register": "warm and real, like chatting with a friend who gets the chaos of family life",
            "viewer_relationship": "sharing what actually worked in your house, not perfect Instagram life",
            "speaking_style": "conversational, gentle pace. 'we tried this and it changed everything.' real examples.",
            "forbidden_tones": ["preachy", "guilt-tripping", "perfect parent", "corporate"],
            "signature_phrases": ["we tried this last month", "my kids actually use this", "takes two minutes to set up", "wish I'd known this sooner"],
            "never_say": ["in today's busy world", "it's essential for families to", "navigate the challenges of", "foster meaningful connections"],
        },
        "hashtags": ["#familylife", "#productivity", "#homeorganization",
                      "#techmom", "#worklifebalance"],
        "cta_templates": [
            "Follow for family-friendly tips",
            "Tag a parent who needs this",
            "Save for your morning routine",
        ],
        "best_formats": ["tutorial", "listicle", "story"],
    },
    "manifestandalign": {
        "name": "Manifest & Align",
        "brand": "Manifest & Align",
        "category": "witchcraft",
        "content_pillars": ["manifestation", "law_of_attraction", "meditation", "affirmations", "moon"],
        "visual_dna": {
            "aesthetic": "golden glow",
            "key_visuals": ["golden light", "cosmos", "crystals", "journal", "moon"],
            "color_palette": ["#0C0A1A", "#F59E0B", "#D97706", "#FEF3C7"],
            "textures": ["golden sparkles", "soft glow", "celestial"],
            "avoid": ["dark", "scary", "negative imagery"],
        },
        "voice": {
            "tone": "soothing, affirming, empowering",
            "personality": "manifestation guide",
            "vocab": ["manifest", "align", "abundance", "attract", "frequency"],
            "avoid": ["demanding", "aggressive", "doubtful"],
        },
        "voice_card": {
            "identity": "someone who manifested their way out of rock bottom and now shares the exact techniques that worked",
            "emotional_register": "calm and certain, like someone who's already seen the proof and is just sharing the method",
            "viewer_relationship": "gently reminding them of their own power, not selling them a fantasy",
            "speaking_style": "slow, deliberate. affirmations land like anchors. short powerful statements. space between sentences.",
            "forbidden_tones": ["desperate", "salesy", "cult-like", "woo-woo without substance"],
            "signature_phrases": ["feel that shift", "this is already yours", "say it with me", "the universe doesn't do accidents"],
            "never_say": ["unlock your true potential", "embrace the journey", "it's vital to remember", "as we embark on"],
        },
        "hashtags": ["#manifestation", "#lawofattraction", "#manifest",
                      "#affirmations", "#abundance", "#spiritualawakening"],
        "cta_templates": [
            "Follow for daily manifestation",
            "Type 'YES' to claim this energy",
            "Save this affirmation",
        ],
        "best_formats": ["inspirational", "listicle", "tutorial"],
    },
    "familyflourish": {
        "name": "Family Flourish",
        "brand": "Family Flourish",
        "category": "lifestyle",
        "content_pillars": ["parenting", "activities", "education", "health", "budgeting"],
        "visual_dna": {
            "aesthetic": "bright pastel",
            "key_visuals": ["families", "kids", "activities", "meals", "outdoors"],
            "color_palette": ["#FDF2F8", "#EC4899", "#F472B6", "#1F2937"],
            "textures": ["soft pastels", "playful patterns", "clean"],
            "avoid": ["dark", "intense", "overly clinical"],
        },
        "voice": {
            "tone": "friendly, practical, empathetic",
            "personality": "experienced parent friend",
            "vocab": ["family", "kids", "easy", "fun", "budget-friendly"],
            "avoid": ["shaming", "elitist", "unrealistic"],
        },
        "voice_card": {
            "identity": "a real parent with real kids who's tried everything and shares what actually survived the chaos",
            "emotional_register": "empathetic and funny, like texting with your favorite parent friend",
            "viewer_relationship": "zero judgment, just 'hey this worked for us, maybe it'll work for you'",
            "speaking_style": "casual, relatable. short sentences. real examples with ages and situations.",
            "forbidden_tones": ["preachy", "perfect parent", "shaming", "clinical"],
            "signature_phrases": ["my five year old tested this", "under ten dollars", "takes five minutes", "game changer for bedtime"],
            "never_say": ["nurture your child's development", "it's essential for parents to", "foster a supportive environment", "in the realm of parenting"],
        },
        "hashtags": ["#parenting", "#familylife", "#momlife",
                      "#kidsactivities", "#parentingtips"],
        "cta_templates": [
            "Follow for family tips",
            "Tag a parent who needs this",
            "Save for the weekend",
        ],
        "best_formats": ["tutorial", "listicle", "story"],
    },
    "moonrituallibrary": {
        "name": "Moon Ritual Library",
        "brand": "Moon Ritual Library",
        "category": "witchcraft",
        "content_pillars": ["moon_rituals", "lunar_phases", "meditation", "intention", "ceremonies"],
        "visual_dna": {
            "aesthetic": "dark celestial",
            "key_visuals": ["moon", "stars", "night sky", "candles", "water reflection"],
            "color_palette": ["#0A0A2E", "#818CF8", "#312E81", "#E0E7FF"],
            "textures": ["starfield", "moonlight", "water ripple"],
            "avoid": ["daylight", "bright colors", "busy"],
        },
        "voice": {
            "tone": "meditative, deep, ritualistic",
            "personality": "lunar priestess",
            "vocab": ["lunar", "phase", "ceremony", "intention", "release"],
            "avoid": ["rushed", "casual", "disrespectful"],
        },
        "voice_card": {
            "identity": "a lunar priestess who's tracked every moon phase for fifteen years and knows exactly what each one asks of us",
            "emotional_register": "reverent and deep, like a guided meditation that actually means something",
            "viewer_relationship": "holding sacred space for their practice, honoring where they are in their cycle",
            "speaking_style": "slow and measured. let silences breathe. short sentences that land like offerings. poetic without being flowery.",
            "forbidden_tones": ["rushed", "casual", "surface-level", "new age cliché"],
            "signature_phrases": ["the moon is asking you to", "this is your time to", "sit with this for a moment", "release what no longer serves"],
            "never_say": ["harness the lunar energy", "on this celestial journey", "it's important to connect with", "as we navigate this phase"],
        },
        "hashtags": ["#moonritual", "#fullmoon", "#newmoon", "#lunarphases",
                      "#moonmagic", "#moonwitch"],
        "cta_templates": [
            "Follow for moon rituals",
            "Save for the next full moon",
            "What's your moon sign?",
        ],
        "best_formats": ["tutorial", "story", "inspirational"],
    },
    "celebrationseason": {
        "name": "Celebration Season",
        "brand": "Celebration Season",
        "category": "lifestyle",
        "content_pillars": ["holidays", "parties", "decorations", "recipes", "gifts"],
        "visual_dna": {
            "aesthetic": "festive bright",
            "key_visuals": ["decorations", "food", "gifts", "parties", "sparkle"],
            "color_palette": ["#1A0505", "#DC2626", "#FFD700", "#FFFFFF"],
            "textures": ["glitter", "ribbon", "confetti", "bokeh lights"],
            "avoid": ["plain", "boring", "generic"],
        },
        "voice": {
            "tone": "excited, festive, helpful",
            "personality": "party planner friend",
            "vocab": ["celebrate", "festive", "easy", "DIY", "stunning"],
            "avoid": ["stressful", "expensive", "complicated"],
        },
        "voice_card": {
            "identity": "the friend who throws the best parties on a budget and makes everything look Pinterest-perfect with dollar store supplies",
            "emotional_register": "excited and bubbly, like showing off a DIY that came out amazing",
            "viewer_relationship": "making celebrations feel doable, not overwhelming. everything's under twenty dollars.",
            "speaking_style": "upbeat, fast-paced. lots of 'oh my gosh' and 'look at this'. show the result first.",
            "forbidden_tones": ["stressful", "expensive-sounding", "complicated", "perfectionist"],
            "signature_phrases": ["under ten dollars for all of this", "your guests won't believe you made this", "takes twenty minutes", "dollar store find"],
            "never_say": ["elevate your celebration", "create an unforgettable experience", "it's essential to plan ahead", "in the spirit of the season"],
        },
        "hashtags": ["#celebration", "#partyideas", "#holidaydecor",
                      "#diyparty", "#festivedecor"],
        "cta_templates": [
            "Follow for holiday inspo",
            "Save this party idea",
            "Tag someone who loves to celebrate",
        ],
        "best_formats": ["tutorial", "listicle", "behind_the_scenes"],
    },
}


def get_niche_profile(niche: str) -> dict:
    """Get full niche profile by ID."""
    return NICHE_PROFILES.get(niche, {})


def get_visual_dna(niche: str) -> dict:
    """Get just the visual DNA for a niche."""
    profile = NICHE_PROFILES.get(niche, {})
    return profile.get("visual_dna", {})


def get_content_pillars(niche: str) -> list:
    """Get content pillars for a niche."""
    profile = NICHE_PROFILES.get(niche, {})
    return profile.get("content_pillars", [])


def get_all_niche_ids() -> list:
    """Return all niche IDs."""
    return list(NICHE_PROFILES.keys())
