"""Platform specifications — dimensions, limits, hashtags, best practices."""

PLATFORM_SPECS = {
    "youtube_shorts": {
        "name": "YouTube Shorts",
        "width": 1080,
        "height": 1920,
        "aspect_ratio": "9:16",
        "max_duration": 60,
        "min_duration": 15,
        "ideal_duration": (30, 58),
        "max_file_size_mb": 256,
        "format": "mp4",
        "codec": "h264",
        "max_bitrate_mbps": 8,
        "fps": 30,
        "max_title_chars": 100,
        "max_description_chars": 5000,
        "max_hashtags": 15,
        "thumbnail": {"width": 1280, "height": 720},
        "safe_zone": {"top": 150, "bottom": 200, "left": 40, "right": 40},
        "best_practices": [
            "Hook in first 1-2 seconds",
            "Vertical ONLY (9:16)",
            "No watermarks from other platforms",
            "Loop-friendly endings boost rewatches",
            "Use #Shorts in description",
        ],
    },
    "youtube": {
        "name": "YouTube Standard",
        "width": 1920,
        "height": 1080,
        "aspect_ratio": "16:9",
        "max_duration": 43200,  # 12 hours
        "min_duration": 60,
        "ideal_duration": (120, 600),
        "max_file_size_mb": 12288,  # 12GB
        "format": "mp4",
        "codec": "h264",
        "max_bitrate_mbps": 16,
        "fps": 30,
        "max_title_chars": 100,
        "max_description_chars": 5000,
        "max_hashtags": 15,
        "thumbnail": {"width": 1280, "height": 720},
        "safe_zone": None,
        "best_practices": [
            "Hook within 5 seconds",
            "Pattern interrupt every 30-60 seconds",
            "End screen last 20 seconds",
            "Custom thumbnail critical for CTR",
            "Timestamps in description",
        ],
    },
    "tiktok": {
        "name": "TikTok",
        "width": 1080,
        "height": 1920,
        "aspect_ratio": "9:16",
        "max_duration": 600,
        "min_duration": 5,
        "ideal_duration": (15, 60),
        "max_file_size_mb": 287,
        "format": "mp4",
        "codec": "h264",
        "max_bitrate_mbps": 8,
        "fps": 30,
        "max_title_chars": 150,
        "max_description_chars": 2200,
        "max_hashtags": 5,
        "thumbnail": None,
        "safe_zone": {"top": 130, "bottom": 270, "left": 40, "right": 40},
        "best_practices": [
            "Hook in first 1 second — NO intro",
            "Loop structure (end connects to start)",
            "Trending sounds boost reach 2-5x",
            "3-5 hashtags max, mix broad + niche",
            "Subtitles required (85% watch muted)",
        ],
    },
    "instagram_reels": {
        "name": "Instagram Reels",
        "width": 1080,
        "height": 1920,
        "aspect_ratio": "9:16",
        "max_duration": 90,
        "min_duration": 3,
        "ideal_duration": (15, 60),
        "max_file_size_mb": 250,
        "format": "mp4",
        "codec": "h264",
        "max_bitrate_mbps": 8,
        "fps": 30,
        "max_title_chars": 0,
        "max_description_chars": 2200,
        "max_hashtags": 30,
        "thumbnail": {"width": 1080, "height": 1080},  # Square cover
        "safe_zone": {"top": 200, "bottom": 340, "left": 40, "right": 40},
        "best_practices": [
            "Hook in first 1.5 seconds",
            "Cover image should work as square",
            "Use 20-30 hashtags in caption",
            "Original audio preferred over trending",
            "CTA in caption, not video",
        ],
    },
    "facebook_reels": {
        "name": "Facebook Reels",
        "width": 1080,
        "height": 1920,
        "aspect_ratio": "9:16",
        "max_duration": 90,
        "min_duration": 3,
        "ideal_duration": (30, 60),
        "max_file_size_mb": 250,
        "format": "mp4",
        "codec": "h264",
        "max_bitrate_mbps": 8,
        "fps": 30,
        "max_title_chars": 0,
        "max_description_chars": 2200,
        "max_hashtags": 10,
        "thumbnail": None,
        "safe_zone": {"top": 150, "bottom": 280, "left": 40, "right": 40},
        "best_practices": [
            "Hook in first 2 seconds",
            "Older demographic than TikTok — less chaotic",
            "Informational content performs well",
            "Cross-post from Reels for easy reach",
        ],
    },
}


def get_platform_spec(platform: str) -> dict:
    """Get platform specifications by key."""
    return PLATFORM_SPECS.get(platform, PLATFORM_SPECS["youtube_shorts"])
