"""Subtitle style presets — Hormozi, Ali Abdaal, Clean, Kinetic, Karaoke."""

SUBTITLE_STYLES = {
    "hormozi": {
        "name": "Hormozi Style",
        "description": "Bold centered, 2-3 words at a time, color-highlighted keyword",
        "position": "center",
        "max_words_per_segment": 3,
        "font": "Montserrat",
        "font_weight": "ExtraBold",
        "font_size": 52,
        "color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "stroke_color": "#000000",
        "stroke_width": 4,
        "background": None,
        "animation": "pop_in",
        "timing_mode": "word_burst",  # Show 2-3 words at a time
        "capitalize": True,
        "best_for": ["short_form", "motivational", "hooks"],
        "creatomate_settings": {
            "font_family": "Montserrat",
            "font_weight": "800",
            "font_size": "8 vmin",
            "color": "#FFFFFF",
            "stroke_color": "#000000",
            "stroke_width": "0.4 vmin",
            "x_alignment": "50%",
            "y_alignment": "50%",
        },
    },
    "ali_abdaal": {
        "name": "Ali Abdaal Style",
        "description": "Clean bottom bar, full sentence, subtle background",
        "position": "bottom",
        "max_words_per_segment": 12,
        "font": "Inter",
        "font_weight": "SemiBold",
        "font_size": 36,
        "color": "#FFFFFF",
        "highlight_color": "#60A5FA",
        "stroke_color": None,
        "stroke_width": 0,
        "background": "rgba(0,0,0,0.5)",
        "background_padding": 12,
        "animation": "fade_in",
        "timing_mode": "sentence",  # Full sentences synced
        "capitalize": False,
        "best_for": ["educational", "tutorial", "long_form"],
        "creatomate_settings": {
            "font_family": "Inter",
            "font_weight": "600",
            "font_size": "4.5 vmin",
            "color": "#FFFFFF",
            "background_color": "rgba(0,0,0,0.5)",
            "x_alignment": "50%",
            "y_alignment": "85%",
        },
    },
    "clean": {
        "name": "Clean Minimal",
        "description": "Simple bottom text, no effects, professional",
        "position": "bottom",
        "max_words_per_segment": 10,
        "font": "Roboto",
        "font_weight": "Medium",
        "font_size": 32,
        "color": "#FFFFFF",
        "highlight_color": None,
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": None,
        "animation": "none",
        "timing_mode": "sentence",
        "capitalize": False,
        "best_for": ["documentary", "news", "professional"],
        "creatomate_settings": {
            "font_family": "Roboto",
            "font_weight": "500",
            "font_size": "4 vmin",
            "color": "#FFFFFF",
            "stroke_color": "#000000",
            "stroke_width": "0.2 vmin",
            "x_alignment": "50%",
            "y_alignment": "88%",
        },
    },
    "kinetic": {
        "name": "Kinetic Typography",
        "description": "Word-by-word animation, movement and scale changes",
        "position": "center",
        "max_words_per_segment": 1,
        "font": "Poppins",
        "font_weight": "Black",
        "font_size": 64,
        "color": "#FFFFFF",
        "highlight_color": "#EF4444",
        "stroke_color": "#000000",
        "stroke_width": 3,
        "background": None,
        "animation": "scale_bounce",
        "timing_mode": "word_by_word",  # Each word animated individually
        "capitalize": True,
        "best_for": ["short_form", "impact", "tiktok"],
        "creatomate_settings": {
            "font_family": "Poppins",
            "font_weight": "900",
            "font_size": "10 vmin",
            "color": "#FFFFFF",
            "stroke_color": "#000000",
            "stroke_width": "0.3 vmin",
            "x_alignment": "50%",
            "y_alignment": "50%",
        },
    },
    "karaoke": {
        "name": "Karaoke Highlight",
        "description": "Full line shown, words highlight as spoken",
        "position": "bottom",
        "max_words_per_segment": 8,
        "font": "Nunito",
        "font_weight": "Bold",
        "font_size": 40,
        "color": "rgba(255,255,255,0.5)",
        "highlight_color": "#FFFFFF",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": "rgba(0,0,0,0.4)",
        "background_padding": 8,
        "animation": "highlight_sweep",
        "timing_mode": "karaoke",  # All words shown, current word highlighted
        "capitalize": False,
        "best_for": ["music", "lyric_video", "meditation"],
        "creatomate_settings": {
            "font_family": "Nunito",
            "font_weight": "700",
            "font_size": "5 vmin",
            "color": "rgba(255,255,255,0.5)",
            "x_alignment": "50%",
            "y_alignment": "85%",
        },
    },
    "neon_glow": {
        "name": "Neon Glow",
        "description": "Centered neon-colored text with glow shadow, great for tech/AI niches",
        "position": "center",
        "max_words_per_segment": 3,
        "font": "Montserrat",
        "font_weight": "ExtraBold",
        "font_size": 48,
        "color": "#00FF88",
        "highlight_color": "#38BDF8",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "background": None,
        "animation": "scale_bounce",
        "timing_mode": "word_burst",
        "capitalize": True,
        "best_for": ["tech", "ai", "gaming", "neon"],
        "creatomate_settings": {
            "font_family": "Montserrat",
            "font_weight": "800",
            "font_size": "7 vmin",
            "color": "#00FF88",
            "stroke_color": "#000000",
            "stroke_width": "0.2 vmin",
            "shadow_color": "rgba(0,255,136,0.6)",
            "shadow_blur": 20,
            "shadow_x": 0,
            "shadow_y": 0,
            "x_alignment": "50%",
            "y_alignment": "50%",
        },
    },
    "typewriter": {
        "name": "Typewriter",
        "description": "Bottom monospace text, character-by-character reveal, news/documentary",
        "position": "bottom",
        "max_words_per_segment": 10,
        "font": "Courier New",
        "font_weight": "Bold",
        "font_size": 34,
        "color": "#E0E0E0",
        "highlight_color": "#FFFFFF",
        "stroke_color": "#000000",
        "stroke_width": 1,
        "background": "rgba(0,0,0,0.7)",
        "background_padding": 10,
        "animation": "typewriter",
        "timing_mode": "sentence",
        "capitalize": False,
        "best_for": ["documentary", "news", "history", "mystery"],
        "creatomate_settings": {
            "font_family": "Courier New",
            "font_weight": "700",
            "font_size": "4 vmin",
            "color": "#E0E0E0",
            "stroke_color": "#000000",
            "stroke_width": "0.1 vmin",
            "background_color": "rgba(0,0,0,0.7)",
            "x_alignment": "50%",
            "y_alignment": "88%",
        },
    },
    "bold_impact": {
        "name": "Bold Impact",
        "description": "Ultra-bold centered Impact-style text, great for fitness/energy niches",
        "position": "center",
        "max_words_per_segment": 2,
        "font": "Impact",
        "font_weight": "Normal",
        "font_size": 72,
        "color": "#FFFFFF",
        "highlight_color": "#EF4444",
        "stroke_color": "#000000",
        "stroke_width": 5,
        "background": None,
        "animation": "scale_bounce",
        "timing_mode": "word_by_word",
        "capitalize": True,
        "best_for": ["fitness", "sports", "motivation", "impact"],
        "creatomate_settings": {
            "font_family": "Impact",
            "font_weight": "400",
            "font_size": "12 vmin",
            "color": "#FFFFFF",
            "stroke_color": "#000000",
            "stroke_width": "0.5 vmin",
            "shadow_color": "rgba(0,0,0,0.8)",
            "shadow_blur": 8,
            "shadow_x": 3,
            "shadow_y": 3,
            "x_alignment": "50%",
            "y_alignment": "50%",
        },
    },
}


def get_subtitle_style(key: str) -> dict:
    """Get subtitle style preset by key."""
    return SUBTITLE_STYLES.get(key, SUBTITLE_STYLES["hormozi"])
