"""20+ transition types with pacing and mood context."""

TRANSITIONS = {
    "cut": {
        "name": "Hard Cut",
        "speed": "instant",
        "energy": "neutral",
        "pacing": ["fast", "medium"],
        "creatomate_effect": "cut",
        "description": "Instant scene change, most common",
    },
    "crossfade": {
        "name": "Crossfade / Dissolve",
        "speed": "slow",
        "energy": "calm",
        "pacing": ["slow", "medium"],
        "creatomate_effect": "fade",
        "duration_ms": 800,
        "description": "Smooth blend between scenes",
    },
    "fade_black": {
        "name": "Fade to Black",
        "speed": "slow",
        "energy": "dramatic",
        "pacing": ["slow"],
        "creatomate_effect": "fade",
        "duration_ms": 600,
        "description": "Scene fades out then in, passage of time or emphasis",
    },
    "fade_white": {
        "name": "Fade to White",
        "speed": "slow",
        "energy": "ethereal",
        "pacing": ["slow"],
        "creatomate_effect": "fade",
        "duration_ms": 600,
        "description": "Bright flash transition, spiritual or dream sequences",
    },
    "slide_left": {
        "name": "Slide Left",
        "speed": "medium",
        "energy": "progressive",
        "pacing": ["medium", "fast"],
        "creatomate_effect": "slide",
        "direction": "left",
        "duration_ms": 400,
        "description": "New scene slides in from right",
    },
    "slide_right": {
        "name": "Slide Right",
        "speed": "medium",
        "energy": "progressive",
        "pacing": ["medium", "fast"],
        "creatomate_effect": "slide",
        "direction": "right",
        "duration_ms": 400,
        "description": "New scene slides in from left",
    },
    "slide_up": {
        "name": "Slide Up",
        "speed": "medium",
        "energy": "ascending",
        "pacing": ["medium", "fast"],
        "creatomate_effect": "slide",
        "direction": "up",
        "duration_ms": 400,
        "description": "Upward reveal, progression feel",
    },
    "slide_down": {
        "name": "Slide Down",
        "speed": "medium",
        "energy": "grounding",
        "pacing": ["medium"],
        "creatomate_effect": "slide",
        "direction": "down",
        "duration_ms": 400,
        "description": "Downward reveal",
    },
    "zoom_in": {
        "name": "Zoom In Transition",
        "speed": "fast",
        "energy": "dynamic",
        "pacing": ["fast"],
        "creatomate_effect": "zoom-in",
        "duration_ms": 300,
        "description": "Camera pushes into next scene",
    },
    "zoom_out": {
        "name": "Zoom Out Transition",
        "speed": "fast",
        "energy": "revealing",
        "pacing": ["fast", "medium"],
        "creatomate_effect": "zoom-out",
        "duration_ms": 300,
        "description": "Camera pulls back to reveal new scene",
    },
    "whip_pan": {
        "name": "Whip Pan",
        "speed": "very_fast",
        "energy": "high_energy",
        "pacing": ["fast"],
        "creatomate_effect": "slide",
        "duration_ms": 200,
        "description": "Ultra-fast horizontal blur, TikTok style",
    },
    "glitch": {
        "name": "Glitch",
        "speed": "fast",
        "energy": "chaotic",
        "pacing": ["fast"],
        "creatomate_effect": "custom",
        "duration_ms": 300,
        "description": "Digital distortion between scenes",
    },
    "morph": {
        "name": "Morph / Shape Shift",
        "speed": "medium",
        "energy": "magical",
        "pacing": ["medium", "slow"],
        "creatomate_effect": "custom",
        "duration_ms": 600,
        "description": "One shape transforms into another",
    },
    "wipe_horizontal": {
        "name": "Horizontal Wipe",
        "speed": "medium",
        "energy": "clean",
        "pacing": ["medium"],
        "creatomate_effect": "wipe",
        "direction": "right",
        "duration_ms": 500,
        "description": "Clean horizontal reveal",
    },
    "wipe_circular": {
        "name": "Circular Wipe",
        "speed": "medium",
        "energy": "playful",
        "pacing": ["medium"],
        "creatomate_effect": "circular-wipe",
        "duration_ms": 500,
        "description": "Circle expands to reveal next scene",
    },
    "flash": {
        "name": "Flash",
        "speed": "very_fast",
        "energy": "impactful",
        "pacing": ["fast"],
        "creatomate_effect": "flash",
        "duration_ms": 150,
        "description": "Quick white flash between scenes",
    },
    "blur_transition": {
        "name": "Blur Transition",
        "speed": "medium",
        "energy": "dreamy",
        "pacing": ["slow", "medium"],
        "creatomate_effect": "custom",
        "duration_ms": 500,
        "description": "Focus blur out then into new scene",
    },
    "spin": {
        "name": "Spin Transition",
        "speed": "fast",
        "energy": "playful",
        "pacing": ["fast"],
        "creatomate_effect": "spin",
        "duration_ms": 400,
        "description": "Rotational transition, fun and energetic",
    },
    "split_reveal": {
        "name": "Split Reveal",
        "speed": "medium",
        "energy": "dramatic",
        "pacing": ["medium"],
        "creatomate_effect": "custom",
        "duration_ms": 500,
        "description": "Scene splits apart to reveal next",
    },
    "bounce": {
        "name": "Bounce",
        "speed": "fast",
        "energy": "playful",
        "pacing": ["fast"],
        "creatomate_effect": "custom",
        "duration_ms": 300,
        "description": "New scene bounces in with elastic feel",
    },
    "particle_dissolve": {
        "name": "Particle Dissolve",
        "speed": "slow",
        "energy": "magical",
        "pacing": ["slow"],
        "creatomate_effect": "custom",
        "duration_ms": 800,
        "description": "Scene dissolves into particles, mystical",
    },
}


def get_transition(key: str) -> dict:
    """Get transition data by key."""
    return TRANSITIONS.get(key, TRANSITIONS["cut"])


def get_transitions_for_pacing(pacing: str) -> list:
    """Get all transitions suitable for a pacing level."""
    return [
        {"key": k, **v}
        for k, v in TRANSITIONS.items()
        if pacing.lower() in v.get("pacing", [])
    ]
