"""Smoke tests for EMPIRE-BRAIN -- auto-generated by EMPIRE-BRAIN Evolution Engine.

All tests are purely local. No network connections, API keys, or running
services required. Tests that would need external resources are skipped.

Generated: 2026-03-06 23:43
"""
import pytest
import sys
import importlib
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


class TestImports:
    """Verify core modules for EMPIRE-BRAIN can be imported."""

    def test_import_knowledge_brain_db(self):
        import knowledge.brain_db
        assert knowledge.brain_db is not None

    def test_import_core_event_bus(self):
        import core.event_bus
        assert core.event_bus is not None

    def test_import_forge_brain_scout(self):
        import forge.brain_scout
        assert forge.brain_scout is not None

    def test_import_forge_brain_sentinel(self):
        import forge.brain_sentinel
        assert forge.brain_sentinel is not None

    def test_import_forge_brain_codex(self):
        import forge.brain_codex
        assert forge.brain_codex is not None

    def test_import_forge_brain_oracle(self):
        import forge.brain_oracle
        assert forge.brain_oracle is not None

    def test_import_forge_brain_smith(self):
        import forge.brain_smith
        assert forge.brain_smith is not None

    def test_import_amplify_pipeline(self):
        import amplify.pipeline
        assert amplify.pipeline is not None

    def test_import_config_settings(self):
        import config.settings
        assert config.settings is not None

    def test_import_api_brain_mcp(self):
        import api.brain_mcp
        assert api.brain_mcp is not None


class TestFunctionExistence:
    """Verify key functions and constants exist and are accessible."""

    def test_knowledge_brain_db_BrainDB_exists(self):
        from knowledge.brain_db import BrainDB
        assert BrainDB is not None

    def test_knowledge_brain_db_get_db_exists(self):
        from knowledge.brain_db import get_db
        assert get_db is not None

    def test_knowledge_brain_db_init_db_exists(self):
        from knowledge.brain_db import init_db
        assert init_db is not None

    def test_knowledge_brain_db_content_hash_exists(self):
        from knowledge.brain_db import content_hash
        assert content_hash is not None

    def test_core_event_bus_EventBus_exists(self):
        from core.event_bus import EventBus
        assert EventBus is not None

    def test_forge_brain_scout_BrainScout_exists(self):
        from forge.brain_scout import BrainScout
        assert BrainScout is not None

    def test_forge_brain_sentinel_BrainSentinel_exists(self):
        from forge.brain_sentinel import BrainSentinel
        assert BrainSentinel is not None

    def test_forge_brain_codex_BrainCodex_exists(self):
        from forge.brain_codex import BrainCodex
        assert BrainCodex is not None

    def test_forge_brain_oracle_BrainOracle_exists(self):
        from forge.brain_oracle import BrainOracle
        assert BrainOracle is not None

    def test_forge_brain_smith_BrainSmith_exists(self):
        from forge.brain_smith import BrainSmith
        assert BrainSmith is not None

    def test_amplify_pipeline_AmplifyPipeline_exists(self):
        from amplify.pipeline import AmplifyPipeline
        assert AmplifyPipeline is not None

    def test_config_settings_EMPIRE_ROOT_exists(self):
        from config.settings import EMPIRE_ROOT
        assert EMPIRE_ROOT is not None

    def test_config_settings_BRAIN_ROOT_exists(self):
        from config.settings import BRAIN_ROOT
        assert BRAIN_ROOT is not None

    def test_config_settings_SERVICES_exists(self):
        from config.settings import SERVICES
        assert SERVICES is not None

    def test_config_settings_EMPIRE_SITES_exists(self):
        from config.settings import EMPIRE_SITES
        assert EMPIRE_SITES is not None


class TestClassInstantiation:
    """Verify key classes can be instantiated."""

    def test_create_knowledge_brain_db_BrainDB(self):
        from knowledge.brain_db import BrainDB
        obj = BrainDB()
        assert obj is not None

    def test_create_core_event_bus_EventBus(self, tmp_path, monkeypatch):
        import core.event_bus as eb_mod
        monkeypatch.setattr(eb_mod, 'EVENTS_DIR', tmp_path / 'events')
        monkeypatch.setattr(eb_mod, 'EVENT_LOG', tmp_path / 'events' / 'log.jsonl')
        from core.event_bus import EventBus
        bus = EventBus()
        assert bus is not None
        assert hasattr(bus, 'subscribe')
        assert hasattr(bus, 'emit')

    def test_create_forge_brain_scout_BrainScout(self, tmp_path):
        from forge.brain_scout import BrainScout
        from knowledge.brain_db import BrainDB
        db = BrainDB(db_path=tmp_path / 'test.db')
        obj = BrainScout(db=db)
        assert obj is not None

    def test_create_forge_brain_sentinel_BrainSentinel(self, tmp_path):
        from forge.brain_sentinel import BrainSentinel
        from knowledge.brain_db import BrainDB
        db = BrainDB(db_path=tmp_path / 'test.db')
        obj = BrainSentinel(db=db)
        assert obj is not None

    def test_create_forge_brain_codex_BrainCodex(self, tmp_path):
        from forge.brain_codex import BrainCodex
        from knowledge.brain_db import BrainDB
        db = BrainDB(db_path=tmp_path / 'test.db')
        obj = BrainCodex(db=db)
        assert obj is not None

    def test_create_forge_brain_oracle_BrainOracle(self, tmp_path):
        from forge.brain_oracle import BrainOracle
        from knowledge.brain_db import BrainDB
        db = BrainDB(db_path=tmp_path / 'test.db')
        obj = BrainOracle(db=db)
        assert obj is not None

    def test_create_forge_brain_smith_BrainSmith(self, tmp_path):
        from forge.brain_smith import BrainSmith
        from knowledge.brain_db import BrainDB
        db = BrainDB(db_path=tmp_path / 'test.db')
        obj = BrainSmith(db=db)
        assert obj is not None

    def test_create_amplify_pipeline_AmplifyPipeline(self, tmp_path):
        from amplify.pipeline import AmplifyPipeline
        from knowledge.brain_db import BrainDB
        db = BrainDB(db_path=tmp_path / 'test.db')
        obj = AmplifyPipeline(db=db)
        assert obj is not None


class TestAPIEndpoints:
    """Verify the FastAPI app has expected routes."""

    def test_api_brain_mcp_app_exists(self):
        from api.brain_mcp import app
        assert app is not None
        assert hasattr(app, 'routes')

    def test_api_brain_mcp_has_routes(self):
        from api.brain_mcp import app
        routes = [app.routes[i].path for i in range(len(app.routes)) if hasattr(app.routes[i], 'path')]
        assert len(routes) > 0, 'App should have at least one route'

    def test_api_brain_mcp_has_health_endpoint(self):
        from api.brain_mcp import app
        paths = [r.path for r in app.routes if hasattr(r, 'path')]
        health_paths = [p for p in paths if 'health' in p.lower()]
        assert len(health_paths) > 0, "API should have a /health endpoint"

    def test_api_brain_mcp_known_routes_registered(self):
        from api.brain_mcp import app
        registered = [r.path for r in app.routes if hasattr(r, 'path')]
        known_routes = ['/tools/brain_briefing', '/tools/brain_cross_reference', '/tools/brain_health', '/tools/brain_learn', '/tools/brain_opportunities']
        for route in known_routes:
            assert route in registered, f"Expected route {route} not found"


class TestBrainDB:
    """Verify BrainDB core operations with a temp database."""

    def test_create_temp_db(self, tmp_path):
        from knowledge.brain_db import BrainDB
        db = BrainDB(db_path=tmp_path / 'test.db')
        assert db is not None
        assert (tmp_path / 'test.db').exists()

    def test_content_hash_deterministic(self):
        from knowledge.brain_db import content_hash
        h1 = content_hash("hello world")
        h2 = content_hash("hello world")
        assert h1 == h2

    def test_content_hash_normalized(self):
        from knowledge.brain_db import content_hash
        h1 = content_hash("hello   world")
        h2 = content_hash("  Hello   World  ")
        assert h1 == h2, 'content_hash should normalize whitespace and case'

    def test_upsert_and_get_project(self, tmp_path):
        from knowledge.brain_db import BrainDB
        db = BrainDB(db_path=tmp_path / 'test.db')
        db.upsert_project({"slug": "test-proj", "name": "Test", "path": "/tmp/test"})
        projects = db.get_projects()
        slugs = [p['slug'] for p in projects]
        assert 'test-proj' in slugs

    def test_get_db_returns_connection(self, tmp_path):
        from knowledge.brain_db import get_db
        conn = get_db(tmp_path / 'test.db')
        assert conn is not None
        conn.close()


class TestEventBusBehavior:
    """Verify EventBus pub/sub with temp directory."""

    def test_subscribe_and_emit(self, tmp_path, monkeypatch):
        import core.event_bus as eb_mod
        monkeypatch.setattr(eb_mod, 'EVENTS_DIR', tmp_path / 'events')
        monkeypatch.setattr(eb_mod, 'EVENT_LOG', tmp_path / 'events' / 'log.jsonl')
        bus = eb_mod.EventBus()
        received = []
        bus.subscribe("test.event", lambda e: received.append(e))
        bus.emit("test.event", {"key": "value"})
        assert len(received) == 1
        assert received[0]['data']['key'] == 'value'

    def test_wildcard_subscriber(self, tmp_path, monkeypatch):
        import core.event_bus as eb_mod
        monkeypatch.setattr(eb_mod, 'EVENTS_DIR', tmp_path / 'events')
        monkeypatch.setattr(eb_mod, 'EVENT_LOG', tmp_path / 'events' / 'log.jsonl')
        bus = eb_mod.EventBus()
        received = []
        bus.subscribe("*", lambda e: received.append(e))
        bus.emit("any.event", {"data": 1})
        bus.emit("other.event", {"data": 2})
        assert len(received) == 2

