"""Smoke tests for empire-toolbox -- auto-generated by EMPIRE-BRAIN Evolution Engine.

All tests are purely local. No network connections, API keys, or running
services required. Tests that would need external resources are skipped.

Generated: 2026-03-07
"""
import pytest
import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


class TestImports:
    """Verify core modules can be imported."""

    def test_import_app(self):
        import app
        assert app is not None

    def test_import_tools_package(self):
        import tools
        assert tools is not None

    def test_import_exa_tool(self):
        from tools import exa_tool
        assert exa_tool is not None

    def test_import_context7_tool(self):
        from tools import context7_tool
        assert context7_tool is not None

    def test_import_brave_tool(self):
        from tools import brave_tool
        assert brave_tool is not None

    def test_import_github_tool(self):
        from tools import github_tool
        assert github_tool is not None

    def test_import_wordpress_tool(self):
        from tools import wordpress_tool
        assert wordpress_tool is not None

    def test_import_openclaw_tool(self):
        from tools import openclaw_tool
        assert openclaw_tool is not None


class TestPydanticModels:
    """Verify request models can be instantiated."""

    def test_exa_search_request(self):
        from app import ExaSearchRequest
        req = ExaSearchRequest(query="test")
        assert req.query == "test"
        assert req.num_results == 10

    def test_exa_similar_request(self):
        from app import ExaSimilarRequest
        req = ExaSimilarRequest(url="https://example.com")
        assert req.url == "https://example.com"

    def test_context7_resolve_request(self):
        from app import Context7ResolveRequest
        req = Context7ResolveRequest(name="react")
        assert req.name == "react"

    def test_brave_search_request(self):
        from app import BraveSearchRequest
        req = BraveSearchRequest(query="test")
        assert req.query == "test"

    def test_github_search_request(self):
        from app import GithubSearchRequest
        req = GithubSearchRequest(query="test")
        assert req.query == "test"

    def test_openclaw_request(self):
        from app import OpenClawRequest
        req = OpenClawRequest(path="/health")
        assert req.path == "/health"


class TestAPIEndpoints:
    """Verify the FastAPI app has expected routes."""

    def test_app_exists(self):
        from app import app
        assert app is not None
        assert hasattr(app, 'routes')

    def test_has_routes(self):
        from app import app
        routes = [r.path for r in app.routes if hasattr(r, 'path')]
        assert len(routes) > 0

    def test_has_health_endpoint(self):
        from app import app
        paths = [r.path for r in app.routes if hasattr(r, 'path')]
        assert '/health' in paths

    def test_has_registry_endpoint(self):
        from app import app
        paths = [r.path for r in app.routes if hasattr(r, 'path')]
        assert '/registry' in paths

    def test_known_routes_registered(self):
        from app import app
        registered = [r.path for r in app.routes if hasattr(r, 'path')]
        expected = ['/health', '/registry', '/tools/exa/search', '/tools/brave/search',
                    '/tools/github/trending', '/tools/wordpress/sites']
        for route in expected:
            assert route in registered, f"Expected route {route} not found"
