"""Smoke tests for forgefiles-pipeline -- auto-generated by EMPIRE-BRAIN Evolution Engine.

All tests are purely local. No network connections, API keys, or running
services required. Tests that would need external resources are skipped.

Generated: 2026-03-06 23:43
"""
import pytest
import sys
import importlib
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


class TestImports:
    """Verify core modules for forgefiles-pipeline can be imported."""

    def test_import_api(self):
        import api
        assert api is not None

    def test_import_scripts_stl_analyzer(self):
        import scripts.stl_analyzer
        assert scripts.stl_analyzer is not None

    def test_import_scripts_caption_engine(self):
        import scripts.caption_engine
        assert scripts.caption_engine is not None

    def test_import_scripts_logger(self):
        import scripts.logger
        assert scripts.logger is not None


class TestFunctionExistence:
    """Verify key functions and constants exist and are accessible."""

    def test_api_PipelineRequest_exists(self):
        from api import PipelineRequest
        assert PipelineRequest is not None

    def test_api_BatchRequest_exists(self):
        from api import BatchRequest
        assert BatchRequest is not None

    def test_scripts_stl_analyzer_analyze_stl_exists(self):
        from scripts.stl_analyzer import analyze_stl
        assert analyze_stl is not None

    def test_scripts_caption_engine_generate_all_captions_exists(self):
        from scripts.caption_engine import generate_all_captions
        assert generate_all_captions is not None

    def test_scripts_caption_engine_detect_collections_exists(self):
        from scripts.caption_engine import detect_collections
        assert detect_collections is not None

    def test_scripts_logger_get_logger_exists(self):
        from scripts.logger import get_logger
        assert get_logger is not None

    def test_scripts_logger_log_stage_exists(self):
        from scripts.logger import log_stage
        assert log_stage is not None

    def test_scripts_logger_BatchProgress_exists(self):
        from scripts.logger import BatchProgress
        assert BatchProgress is not None


class TestClassInstantiation:
    """Verify key classes can be instantiated."""

    def test_create_api_PipelineRequest(self):
        from api import PipelineRequest
        obj = PipelineRequest(stl="/tmp/test.stl")
        assert obj is not None

    def test_create_api_BatchRequest(self):
        from api import BatchRequest
        obj = BatchRequest(directory="/tmp/models")
        assert obj is not None


class TestAPIEndpoints:
    """Verify the FastAPI app has expected routes."""

    def test_api_app_exists(self):
        from api import app
        assert app is not None
        assert hasattr(app, 'routes')

    def test_api_has_routes(self):
        from api import app
        routes = [app.routes[i].path for i in range(len(app.routes)) if hasattr(app.routes[i], 'path')]
        assert len(routes) > 0, 'App should have at least one route'

    def test_api_has_health_endpoint(self):
        from api import app
        paths = [r.path for r in app.routes if hasattr(r, 'path')]
        health_paths = [p for p in paths if 'health' in p.lower()]
        assert len(health_paths) > 0, "API should have a /health endpoint"

    def test_api_known_routes_registered(self):
        from api import app
        registered = [r.path for r in app.routes if hasattr(r, 'path')]
        known_routes = ['/pipeline/batch', '/pipeline/history', '/pipeline/run', '/pipeline/run/sync', '/pipeline/status/{job_id}']
        for route in known_routes:
            assert route in registered, f"Expected route {route} not found"


class TestPipelineModels:
    """Verify Pydantic request models work correctly."""

    def test_pipeline_request_defaults(self):
        from api import PipelineRequest
        req = PipelineRequest(stl="/tmp/test.stl")
        assert req.stl == '/tmp/test.stl'
        assert req.mode == 'turntable'
        assert req.preset == 'portfolio'
        assert req.fast is False

    def test_batch_request_defaults(self):
        from api import BatchRequest
        req = BatchRequest(directory="/tmp/models")
        assert req.directory == '/tmp/models'
        assert req.mode == 'turntable'

