"""
Magical Correspondences Knowledge Base

A comprehensive reference of herbs, crystals, colors, elements, planets,
days, and numbers used in witchcraft, Wicca, and folk magic traditions.

All data is pure Python with no external dependencies.
"""

# ---------------------------------------------------------------------------
# HERBS — ~50 entries
# ---------------------------------------------------------------------------

HERBS = {
    "lavender": {
        "name": "Lavender",
        "magical_properties": ["peace", "purification", "sleep", "love", "clarity", "calm"],
        "element": "air",
        "planet": "mercury",
        "chakra": "third eye",
        "moon_phase": "full moon",
        "day": "wednesday",
        "deities": ["Hecate", "Arianrhod", "Circe"],
        "safety_notes": ["Generally safe", "Avoid concentrated oil during pregnancy"],
        "pairs_with": ["chamomile", "rose", "mugwort"],
        "beginner_tip": "Keep a sachet under your pillow for peaceful sleep and prophetic dreams.",
    },
    "rosemary": {
        "name": "Rosemary",
        "magical_properties": ["protection", "memory", "purification", "love", "healing"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "waxing moon",
        "day": "sunday",
        "deities": ["Aphrodite", "Virgin Mary"],
        "safety_notes": ["Generally safe", "Avoid large medicinal doses during pregnancy"],
        "pairs_with": ["sage", "thyme", "bay laurel"],
        "beginner_tip": "Hang a sprig above your door for household protection.",
    },
    "sage": {
        "name": "Sage",
        "magical_properties": ["cleansing", "wisdom", "purification", "protection", "longevity"],
        "element": "air",
        "planet": "jupiter",
        "chakra": "crown",
        "moon_phase": "waning moon",
        "day": "thursday",
        "deities": ["Zeus", "Jupiter", "Chiron"],
        "safety_notes": ["Generally safe", "Source ethically; white sage is over-harvested"],
        "pairs_with": ["cedar", "rosemary", "lavender"],
        "beginner_tip": "Garden sage works just as well as white sage for smoke cleansing.",
    },
    "mugwort": {
        "name": "Mugwort",
        "magical_properties": ["divination", "prophetic dreams", "astral travel", "protection"],
        "element": "earth",
        "planet": "moon",
        "chakra": "third eye",
        "moon_phase": "full moon",
        "day": "monday",
        "deities": ["Artemis", "Diana"],
        "safety_notes": ["Do NOT ingest during pregnancy", "Can cause allergic reaction in those sensitive to ragweed"],
        "pairs_with": ["lavender", "wormwood", "bay laurel"],
        "beginner_tip": "Place a small amount inside a dream pillow for vivid, prophetic dreams.",
    },
    "chamomile": {
        "name": "Chamomile",
        "magical_properties": ["peace", "healing", "luck", "money", "sleep", "purification"],
        "element": "water",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "full moon",
        "day": "sunday",
        "deities": ["Ra", "Cernunnos", "Lugh"],
        "safety_notes": ["Generally safe", "Rare allergies in those sensitive to ragweed family"],
        "pairs_with": ["lavender", "lemon balm", "valerian"],
        "beginner_tip": "Wash your hands with chamomile tea before gambling or games of chance.",
    },
    "bay laurel": {
        "name": "Bay Laurel",
        "magical_properties": ["divination", "wishes", "protection", "purification", "success"],
        "element": "fire",
        "planet": "sun",
        "chakra": "third eye",
        "moon_phase": "new moon",
        "day": "sunday",
        "deities": ["Apollo", "Ceres", "Aesculapius"],
        "safety_notes": ["Generally safe", "Do not ingest essential oil"],
        "pairs_with": ["rosemary", "cinnamon", "frankincense"],
        "beginner_tip": "Write a wish on a bay leaf and burn it to release the intention.",
    },
    "cinnamon": {
        "name": "Cinnamon",
        "magical_properties": ["prosperity", "success", "passion", "protection", "power", "speed"],
        "element": "fire",
        "planet": "sun",
        "chakra": "sacral",
        "moon_phase": "waxing moon",
        "day": "sunday",
        "deities": ["Aphrodite", "Venus"],
        "safety_notes": ["Generally safe in culinary amounts", "Cassia cinnamon contains coumarin; use true Ceylon cinnamon for frequent consumption"],
        "pairs_with": ["ginger", "clove", "basil"],
        "beginner_tip": "Blow cinnamon powder in through your front door on the first of the month for abundance.",
    },
    "basil": {
        "name": "Basil",
        "magical_properties": ["prosperity", "love", "protection", "harmony", "courage"],
        "element": "fire",
        "planet": "mars",
        "chakra": "heart",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Vishnu", "Krishna", "Ares"],
        "safety_notes": ["Generally safe", "Tulsi (holy basil) is considered sacred in Hinduism"],
        "pairs_with": ["cinnamon", "mint", "rosemary"],
        "beginner_tip": "Keep a basil plant in your kitchen to attract wealth and protect the home.",
    },
    "thyme": {
        "name": "Thyme",
        "magical_properties": ["courage", "healing", "purification", "psychic powers", "sleep"],
        "element": "water",
        "planet": "venus",
        "chakra": "heart",
        "moon_phase": "waxing moon",
        "day": "friday",
        "deities": ["Aphrodite", "Ares", "Faerie folk"],
        "safety_notes": ["Generally safe"],
        "pairs_with": ["rosemary", "lavender", "sage"],
        "beginner_tip": "Place thyme under your pillow to prevent nightmares.",
    },
    "mint": {
        "name": "Mint",
        "magical_properties": ["prosperity", "healing", "travel", "protection", "energy"],
        "element": "air",
        "planet": "mercury",
        "chakra": "throat",
        "moon_phase": "waxing moon",
        "day": "wednesday",
        "deities": ["Pluto", "Hecate"],
        "safety_notes": ["Generally safe", "Peppermint oil can irritate skin; dilute before topical use"],
        "pairs_with": ["basil", "lavender", "chamomile"],
        "beginner_tip": "Rub fresh mint leaves on your wallet to attract money.",
    },
    "rose": {
        "name": "Rose",
        "magical_properties": ["love", "beauty", "healing", "divination", "protection", "psychic powers"],
        "element": "water",
        "planet": "venus",
        "chakra": "heart",
        "moon_phase": "full moon",
        "day": "friday",
        "deities": ["Aphrodite", "Venus", "Isis", "Hathor", "Freya"],
        "safety_notes": ["Generally safe", "Thorns can puncture skin; handle carefully"],
        "pairs_with": ["jasmine", "lavender", "chamomile"],
        "beginner_tip": "Add rose petals to a bath for self-love magic.",
    },
    "jasmine": {
        "name": "Jasmine",
        "magical_properties": ["love", "prophetic dreams", "money", "sensuality", "spiritual love"],
        "element": "water",
        "planet": "moon",
        "chakra": "sacral",
        "moon_phase": "full moon",
        "day": "monday",
        "deities": ["Vishnu", "Diana"],
        "safety_notes": ["Generally safe", "Essential oil is potent; use sparingly"],
        "pairs_with": ["rose", "lavender", "sandalwood"],
        "beginner_tip": "Burn dried jasmine flowers at night to encourage prophetic dreams.",
    },
    "elderflower": {
        "name": "Elderflower",
        "magical_properties": ["protection", "healing", "faerie magic", "prosperity", "exorcism"],
        "element": "water",
        "planet": "venus",
        "chakra": "crown",
        "moon_phase": "full moon",
        "day": "friday",
        "deities": ["Holda", "Venus", "Elder Mother"],
        "safety_notes": ["Flowers and ripe berries are safe when cooked", "Raw berries, bark, and leaves are mildly toxic"],
        "pairs_with": ["hawthorn", "rowan", "yarrow"],
        "beginner_tip": "Ask the Elder Mother's permission before harvesting any part of the tree.",
    },
    "vervain": {
        "name": "Vervain",
        "magical_properties": ["protection", "purification", "love", "peace", "money", "enchantment"],
        "element": "earth",
        "planet": "venus",
        "chakra": "heart",
        "moon_phase": "waxing moon",
        "day": "friday",
        "deities": ["Isis", "Thor", "Jupiter", "Cerridwen"],
        "safety_notes": ["Avoid during pregnancy", "Generally safe in small amounts"],
        "pairs_with": ["rosemary", "sage", "bay laurel"],
        "beginner_tip": "Vervain is one of the most revered herbs in European folk magic; bury it in your garden for protection.",
    },
    "yarrow": {
        "name": "Yarrow",
        "magical_properties": ["courage", "divination", "love", "healing", "psychic powers"],
        "element": "water",
        "planet": "venus",
        "chakra": "third eye",
        "moon_phase": "waning moon",
        "day": "friday",
        "deities": ["Achilles", "Aphrodite"],
        "safety_notes": ["Avoid during pregnancy", "Can cause skin sensitivity in some"],
        "pairs_with": ["mugwort", "elderflower", "lavender"],
        "beginner_tip": "Yarrow stalks are traditionally used in I Ching divination.",
    },
    "nettle": {
        "name": "Nettle",
        "magical_properties": ["protection", "healing", "courage", "exorcism", "lust"],
        "element": "fire",
        "planet": "mars",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Thor", "Mars"],
        "safety_notes": ["Wear gloves when harvesting fresh", "Stinging hairs neutralize when dried or cooked"],
        "pairs_with": ["rosemary", "basil", "ginger"],
        "beginner_tip": "Dried nettle in a sachet is a powerful protective charm.",
    },
    "valerian": {
        "name": "Valerian",
        "magical_properties": ["sleep", "protection", "love", "purification", "harmony"],
        "element": "water",
        "planet": "venus",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "friday",
        "deities": ["Venus"],
        "safety_notes": ["Can cause drowsiness", "Do not combine with sedative medications", "Has a strong, pungent odor"],
        "pairs_with": ["chamomile", "lavender", "lemon balm"],
        "beginner_tip": "Add to sachets placed in quarreling spaces to restore harmony.",
    },
    "st. john's wort": {
        "name": "St. John's Wort",
        "magical_properties": ["protection", "healing", "courage", "banishing", "divination"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "full moon",
        "day": "sunday",
        "deities": ["Baldur", "St. John"],
        "safety_notes": ["Interacts with many medications including antidepressants, birth control, and blood thinners", "Causes photosensitivity", "Consult doctor before use"],
        "pairs_with": ["rosemary", "vervain", "bay laurel"],
        "beginner_tip": "Traditionally gathered on Midsummer's Eve for maximum potency.",
    },
    "lemon balm": {
        "name": "Lemon Balm",
        "magical_properties": ["love", "healing", "success", "peace", "memory"],
        "element": "water",
        "planet": "moon",
        "chakra": "heart",
        "moon_phase": "full moon",
        "day": "monday",
        "deities": ["Diana", "Artemis"],
        "safety_notes": ["Generally safe", "May interact with thyroid and sedative medications"],
        "pairs_with": ["chamomile", "lavender", "mint"],
        "beginner_tip": "Carry lemon balm to attract love or soothe a broken heart.",
    },
    "dandelion": {
        "name": "Dandelion",
        "magical_properties": ["divination", "wishes", "spirit calling", "healing", "resilience"],
        "element": "air",
        "planet": "jupiter",
        "chakra": "solar plexus",
        "moon_phase": "full moon",
        "day": "thursday",
        "deities": ["Hecate", "Brigid"],
        "safety_notes": ["Generally safe", "Avoid if allergic to ragweed family"],
        "pairs_with": ["chamomile", "calendula", "mint"],
        "beginner_tip": "Blow a dandelion puff and make a wish; the seeds carry your intention.",
    },
    "calendula": {
        "name": "Calendula",
        "magical_properties": ["protection", "prophetic dreams", "legal matters", "psychic powers", "healing"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "full moon",
        "day": "sunday",
        "deities": ["Marigold Mary", "Sun deities"],
        "safety_notes": ["Generally safe", "Avoid during pregnancy in medicinal doses"],
        "pairs_with": ["chamomile", "st. john's wort", "lavender"],
        "beginner_tip": "Scatter petals under your bed for prophetic dreams and protection during sleep.",
    },
    "wormwood": {
        "name": "Wormwood",
        "magical_properties": ["divination", "spirit communication", "protection", "psychic powers", "love"],
        "element": "fire",
        "planet": "mars",
        "chakra": "third eye",
        "moon_phase": "dark moon",
        "day": "tuesday",
        "deities": ["Artemis", "Diana", "Iris"],
        "safety_notes": ["Contains thujone, which is toxic in large amounts", "Do NOT ingest essential oil", "Use externally or as incense only"],
        "pairs_with": ["mugwort", "frankincense", "myrrh"],
        "beginner_tip": "Burn small amounts as incense to aid scrying and divination.",
    },
    "frankincense": {
        "name": "Frankincense",
        "magical_properties": ["purification", "spirituality", "protection", "consecration", "meditation"],
        "element": "fire",
        "planet": "sun",
        "chakra": "crown",
        "moon_phase": "full moon",
        "day": "sunday",
        "deities": ["Ra", "Baal", "Many deities across traditions"],
        "safety_notes": ["Generally safe as incense", "Source ethically; trees are over-tapped"],
        "pairs_with": ["myrrh", "sandalwood", "cedar"],
        "beginner_tip": "Burn frankincense resin on charcoal to purify and consecrate ritual space.",
    },
    "myrrh": {
        "name": "Myrrh",
        "magical_properties": ["purification", "protection", "healing", "spirituality", "banishing"],
        "element": "water",
        "planet": "moon",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "monday",
        "deities": ["Isis", "Adonis", "Ra"],
        "safety_notes": ["Generally safe as incense", "Avoid ingestion during pregnancy"],
        "pairs_with": ["frankincense", "sandalwood", "cedar"],
        "beginner_tip": "Combine with frankincense for a classic temple purification incense.",
    },
    "sandalwood": {
        "name": "Sandalwood",
        "magical_properties": ["spirituality", "healing", "protection", "wishes", "meditation"],
        "element": "water",
        "planet": "moon",
        "chakra": "crown",
        "moon_phase": "full moon",
        "day": "monday",
        "deities": ["Vishnu", "Buddha", "Lakshmi"],
        "safety_notes": ["Generally safe", "Source ethically; Indian sandalwood is endangered"],
        "pairs_with": ["frankincense", "lavender", "rose"],
        "beginner_tip": "Burn sandalwood incense during meditation to deepen your practice.",
    },
    "patchouli": {
        "name": "Patchouli",
        "magical_properties": ["prosperity", "grounding", "fertility", "lust", "protection"],
        "element": "earth",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "saturday",
        "deities": ["Gaia", "Pan"],
        "safety_notes": ["Generally safe", "Strong scent; use sparingly"],
        "pairs_with": ["cinnamon", "cedar", "vetiver"],
        "beginner_tip": "Add to money-drawing sachets or anoint a green candle for prosperity work.",
    },
    "cedar": {
        "name": "Cedar",
        "magical_properties": ["purification", "protection", "prosperity", "healing", "courage"],
        "element": "fire",
        "planet": "sun",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "sunday",
        "deities": ["Artemis", "Persephone", "Astarte"],
        "safety_notes": ["Generally safe as incense", "Some cedar oils can irritate skin"],
        "pairs_with": ["sage", "sweetgrass", "juniper"],
        "beginner_tip": "Burn cedar chips to cleanse a new home before moving in.",
    },
    "juniper": {
        "name": "Juniper",
        "magical_properties": ["protection", "banishing", "healing", "love", "anti-theft"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "waning moon",
        "day": "sunday",
        "deities": ["Astarte", "Inanna"],
        "safety_notes": ["Generally safe as incense", "Avoid berry ingestion during pregnancy"],
        "pairs_with": ["cedar", "rosemary", "sage"],
        "beginner_tip": "Hang juniper berries above your door to ward off thieves and negativity.",
    },
    "pine": {
        "name": "Pine",
        "magical_properties": ["healing", "prosperity", "purification", "protection", "fertility"],
        "element": "air",
        "planet": "mars",
        "chakra": "heart",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Pan", "Dionysus", "Cybele", "Attis"],
        "safety_notes": ["Generally safe", "Pine pollen can trigger allergies"],
        "pairs_with": ["cedar", "juniper", "eucalyptus"],
        "beginner_tip": "Scatter pine needles on the floor and sweep toward the door to banish negativity.",
    },
    "holly": {
        "name": "Holly",
        "magical_properties": ["protection", "luck", "dream magic", "balance", "consecration"],
        "element": "fire",
        "planet": "mars",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "tuesday",
        "deities": ["Holly King", "Lugh", "Tannus"],
        "safety_notes": ["Berries are TOXIC if ingested", "Use leaves and wood only"],
        "pairs_with": ["oak", "ivy", "mistletoe"],
        "beginner_tip": "Holly is a powerful Yule decoration that protects the household through winter.",
    },
    "ivy": {
        "name": "Ivy",
        "magical_properties": ["protection", "fidelity", "binding", "healing", "perseverance"],
        "element": "water",
        "planet": "saturn",
        "chakra": "heart",
        "moon_phase": "waning moon",
        "day": "saturday",
        "deities": ["Dionysus", "Bacchus", "Osiris"],
        "safety_notes": ["All parts are toxic if ingested", "Can cause skin irritation", "External or symbolic use only"],
        "pairs_with": ["holly", "vine", "oak"],
        "beginner_tip": "Grow ivy on your home for protection; give it indoors for fidelity magic.",
    },
    "oak": {
        "name": "Oak",
        "magical_properties": ["strength", "protection", "wisdom", "fertility", "luck", "healing"],
        "element": "fire",
        "planet": "sun",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "thursday",
        "deities": ["Zeus", "Thor", "Jupiter", "Dagda", "Herne"],
        "safety_notes": ["Generally safe", "Use bark, leaves, or acorns"],
        "pairs_with": ["holly", "ash", "hawthorn"],
        "beginner_tip": "Carry an acorn for luck and to preserve youthfulness.",
    },
    "hawthorn": {
        "name": "Hawthorn",
        "magical_properties": ["protection", "fertility", "faerie magic", "happiness", "heart healing"],
        "element": "fire",
        "planet": "mars",
        "chakra": "heart",
        "moon_phase": "full moon",
        "day": "tuesday",
        "deities": ["Cardea", "Flora", "Hymen", "Faerie Queen"],
        "safety_notes": ["Berries edible", "May interact with heart medications"],
        "pairs_with": ["oak", "rowan", "elderflower"],
        "beginner_tip": "Never cut a hawthorn without leaving an offering; it is a faerie tree.",
    },
    "rowan": {
        "name": "Rowan",
        "magical_properties": ["protection", "psychic powers", "healing", "divination", "success"],
        "element": "fire",
        "planet": "sun",
        "chakra": "third eye",
        "moon_phase": "full moon",
        "day": "sunday",
        "deities": ["Brigid", "Thor"],
        "safety_notes": ["Berries must be cooked before eating (raw seeds contain parasorbic acid)"],
        "pairs_with": ["hawthorn", "ash", "oak"],
        "beginner_tip": "Tie two rowan twigs into an equal-armed cross with red thread for protection.",
    },
    "birch": {
        "name": "Birch",
        "magical_properties": ["new beginnings", "purification", "protection", "fertility", "creativity"],
        "element": "water",
        "planet": "venus",
        "chakra": "sacral",
        "moon_phase": "new moon",
        "day": "friday",
        "deities": ["Frigga", "Freya", "Venus"],
        "safety_notes": ["Generally safe", "Birch sap can be consumed"],
        "pairs_with": ["rowan", "willow", "alder"],
        "beginner_tip": "Write intentions on birch bark for new beginnings at the new moon.",
    },
    "willow": {
        "name": "Willow",
        "magical_properties": ["healing", "love", "moon magic", "divination", "enchantment", "grief"],
        "element": "water",
        "planet": "moon",
        "chakra": "sacral",
        "moon_phase": "full moon",
        "day": "monday",
        "deities": ["Hecate", "Persephone", "Artemis", "Cerridwen", "Brigid"],
        "safety_notes": ["Bark contains salicin (aspirin precursor)", "Avoid if allergic to aspirin"],
        "pairs_with": ["mugwort", "birch", "rose"],
        "beginner_tip": "Make wishes by tying knots in flexible willow branches.",
    },
    "ash": {
        "name": "Ash",
        "magical_properties": ["protection", "prosperity", "health", "sea magic", "prophecy"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "waxing moon",
        "day": "sunday",
        "deities": ["Odin", "Poseidon", "Neptune", "Gwydion"],
        "safety_notes": ["Generally safe"],
        "pairs_with": ["oak", "rowan", "hawthorn"],
        "beginner_tip": "Ash is Yggdrasil, the Norse World Tree; carry a leaf for protection on journeys.",
    },
    "mandrake": {
        "name": "Mandrake",
        "magical_properties": ["protection", "fertility", "prosperity", "love", "power"],
        "element": "fire",
        "planet": "mercury",
        "chakra": "root",
        "moon_phase": "full moon",
        "day": "wednesday",
        "deities": ["Hecate", "Aphrodite", "Circe"],
        "safety_notes": ["ALL parts are TOXIC", "Do NOT ingest", "Handle root with care", "Use as a charm or talisman only, not for consumption"],
        "pairs_with": ["mugwort", "wormwood", "frankincense"],
        "beginner_tip": "True mandrake root is rare and toxic; American mandrake (mayapple) is a different plant and is also toxic.",
    },
    "belladonna": {
        "name": "Belladonna",
        "magical_properties": ["astral projection", "visions", "protection", "enchantment"],
        "element": "water",
        "planet": "saturn",
        "chakra": "third eye",
        "moon_phase": "dark moon",
        "day": "saturday",
        "deities": ["Hecate", "Bellona", "Circe", "Atropos"],
        "safety_notes": [
            "EXTREMELY TOXIC - ALL parts of this plant are deadly poisonous",
            "DO NOT INGEST under any circumstances",
            "DO NOT handle without gloves",
            "Even small amounts can cause hallucinations, seizures, and death",
            "Keep away from children and pets",
            "Use ONLY as a symbolic or visual representation, never internally or externally",
        ],
        "pairs_with": ["wormwood", "mandrake", "henbane"],
        "beginner_tip": "DANGER: Do NOT use belladonna in practice. Work with safer visionary herbs like mugwort instead.",
    },
    "hemlock": {
        "name": "Hemlock",
        "magical_properties": ["astral projection", "consecration of ritual tools"],
        "element": "water",
        "planet": "saturn",
        "chakra": "crown",
        "moon_phase": "dark moon",
        "day": "saturday",
        "deities": ["Hecate"],
        "safety_notes": [
            "LETHAL POISON - DO NOT USE",
            "ALL parts of this plant are fatally toxic",
            "There is NO safe dose for human contact or consumption",
            "Skin contact can cause poisoning",
            "This is the poison that killed Socrates",
            "DO NOT grow, harvest, handle, or use in ANY form",
        ],
        "pairs_with": [],
        "beginner_tip": "DO NOT USE HEMLOCK. There is no safe way to work with this plant. This entry exists for educational reference only.",
    },
    "henbane": {
        "name": "Henbane",
        "magical_properties": ["love", "rain magic", "necromancy", "spirit work"],
        "element": "water",
        "planet": "saturn",
        "chakra": "third eye",
        "moon_phase": "dark moon",
        "day": "saturday",
        "deities": ["Hecate", "Jupiter"],
        "safety_notes": [
            "HIGHLY TOXIC - ALL parts are poisonous",
            "DO NOT INGEST or apply to skin",
            "Causes delirium, hallucinations, and can be fatal",
            "Historical use in flying ointments caused many deaths",
            "Use only as a symbolic or visual reference",
        ],
        "pairs_with": ["belladonna", "mandrake"],
        "beginner_tip": "DO NOT USE. Work with mugwort or lavender for spirit work instead.",
    },
    "datura": {
        "name": "Datura",
        "magical_properties": ["visions", "hex-breaking", "protection", "sleep"],
        "element": "water",
        "planet": "saturn",
        "chakra": "third eye",
        "moon_phase": "dark moon",
        "day": "saturday",
        "deities": ["Shiva", "Hecate"],
        "safety_notes": [
            "EXTREMELY DANGEROUS - LETHAL POISON",
            "ALL parts are highly toxic, including seeds, flowers, and leaves",
            "Causes severe hallucinations, psychosis, organ failure, and death",
            "There is NO safe dosage - toxicity varies wildly between individual plants",
            "DO NOT grow near children or animals",
            "This entry exists for educational reference ONLY",
        ],
        "pairs_with": [],
        "beginner_tip": "NEVER USE DATURA. It is unpredictably lethal. Use mugwort for visionary work.",
    },
    "comfrey": {
        "name": "Comfrey",
        "magical_properties": ["protection during travel", "money", "healing", "stability"],
        "element": "water",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "saturday",
        "deities": ["Hecate"],
        "safety_notes": ["Do NOT ingest; contains pyrrolizidine alkaloids toxic to the liver", "External use only or as a magical sachet"],
        "pairs_with": ["mugwort", "lavender", "mint"],
        "beginner_tip": "Tuck comfrey in your luggage for safe travels.",
    },
    "echinacea": {
        "name": "Echinacea",
        "magical_properties": ["strength", "healing", "prosperity", "offerings"],
        "element": "earth",
        "planet": "mars",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Earth Mother"],
        "safety_notes": ["Generally safe", "May interact with immunosuppressants"],
        "pairs_with": ["calendula", "chamomile", "nettle"],
        "beginner_tip": "Used in traditional Indigenous medicine; approach with respect for its origins.",
    },
    "ginger": {
        "name": "Ginger",
        "magical_properties": ["power", "success", "love", "money", "courage", "energy"],
        "element": "fire",
        "planet": "mars",
        "chakra": "sacral",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Mars", "Ares"],
        "safety_notes": ["Generally safe", "May interact with blood thinners in large amounts"],
        "pairs_with": ["cinnamon", "clove", "basil"],
        "beginner_tip": "Chew a piece of ginger before spell work to increase the power of your magic.",
    },
    "turmeric": {
        "name": "Turmeric",
        "magical_properties": ["purification", "protection", "prosperity", "fertility"],
        "element": "fire",
        "planet": "mars",
        "chakra": "solar plexus",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Ganesh", "Parvati", "Lakshmi"],
        "safety_notes": ["Generally safe", "Stains skin and fabric intensely"],
        "pairs_with": ["ginger", "cinnamon", "saffron"],
        "beginner_tip": "Sacred in Hindu traditions; add to purification baths or sprinkle around thresholds.",
    },
    "star anise": {
        "name": "Star Anise",
        "magical_properties": ["psychic powers", "luck", "purification", "dreams", "consecration"],
        "element": "air",
        "planet": "jupiter",
        "chakra": "third eye",
        "moon_phase": "full moon",
        "day": "thursday",
        "deities": ["Mercury", "Hermes"],
        "safety_notes": ["Generally safe in culinary amounts", "Do not confuse with Japanese star anise, which is toxic"],
        "pairs_with": ["cinnamon", "clove", "bay laurel"],
        "beginner_tip": "Place on your altar to increase psychic awareness.",
    },
    "clove": {
        "name": "Clove",
        "magical_properties": ["protection", "banishing", "love", "money", "exorcism"],
        "element": "fire",
        "planet": "jupiter",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "thursday",
        "deities": ["Jupiter", "Zeus"],
        "safety_notes": ["Generally safe in culinary amounts", "Clove oil can burn skin and mucous membranes"],
        "pairs_with": ["cinnamon", "ginger", "star anise"],
        "beginner_tip": "Stud an orange with cloves (a pomander) for Yule protection and prosperity.",
    },
    "nutmeg": {
        "name": "Nutmeg",
        "magical_properties": ["luck", "money", "fidelity", "health", "psychic powers"],
        "element": "fire",
        "planet": "jupiter",
        "chakra": "third eye",
        "moon_phase": "waxing moon",
        "day": "thursday",
        "deities": ["Jupiter"],
        "safety_notes": ["Safe in culinary amounts", "TOXIC in large doses (more than one whole nut); can cause hallucinations and organ damage"],
        "pairs_with": ["cinnamon", "clove", "ginger"],
        "beginner_tip": "Carry a whole nutmeg in your pocket as a good-luck charm.",
    },
}


# ---------------------------------------------------------------------------
# CRYSTALS — ~40 entries
# ---------------------------------------------------------------------------

CRYSTALS = {
    "clear quartz": {
        "name": "Clear Quartz",
        "magical_properties": ["amplification", "healing", "clarity", "programming", "all-purpose"],
        "element": "all",
        "planet": "sun",
        "chakra": "crown",
        "moon_phase": "any",
        "day": "sunday",
        "deities": ["All"],
        "safety_notes": ["Safe to handle", "Do not make elixirs with raw stone in water without research"],
        "pairs_with": ["amethyst", "rose quartz", "selenite"],
        "beginner_tip": "Clear quartz amplifies the energy of any crystal placed near it. It can substitute for any stone.",
    },
    "amethyst": {
        "name": "Amethyst",
        "magical_properties": ["peace", "intuition", "sobriety", "wisdom", "psychic powers", "protection"],
        "element": "water",
        "planet": "jupiter",
        "chakra": "third eye",
        "moon_phase": "full moon",
        "day": "thursday",
        "deities": ["Dionysus", "Bacchus", "Diana"],
        "safety_notes": ["Safe to handle", "Fades in prolonged direct sunlight"],
        "pairs_with": ["clear quartz", "selenite", "lepidolite"],
        "beginner_tip": "Place under your pillow to prevent nightmares and encourage prophetic dreams.",
    },
    "rose quartz": {
        "name": "Rose Quartz",
        "magical_properties": ["love", "self-love", "compassion", "emotional healing", "friendship"],
        "element": "water",
        "planet": "venus",
        "chakra": "heart",
        "moon_phase": "full moon",
        "day": "friday",
        "deities": ["Aphrodite", "Venus", "Adonis"],
        "safety_notes": ["Safe to handle", "Fades in prolonged direct sunlight"],
        "pairs_with": ["amethyst", "rhodonite", "clear quartz"],
        "beginner_tip": "Hold during self-love affirmations or place on your heart chakra.",
    },
    "black tourmaline": {
        "name": "Black Tourmaline",
        "magical_properties": ["protection", "grounding", "banishing", "shielding", "purification"],
        "element": "earth",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "saturday",
        "deities": [],
        "safety_notes": ["Safe to handle", "Brittle; can chip easily"],
        "pairs_with": ["selenite", "hematite", "smoky quartz"],
        "beginner_tip": "Place a piece near your front door or at each corner of your home for protection.",
    },
    "citrine": {
        "name": "Citrine",
        "magical_properties": ["prosperity", "success", "joy", "confidence", "creativity", "manifestation"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "waxing moon",
        "day": "sunday",
        "deities": ["Demeter", "Sekhmet"],
        "safety_notes": ["Safe to handle", "Natural citrine is rare; most is heat-treated amethyst"],
        "pairs_with": ["pyrite", "carnelian", "clear quartz"],
        "beginner_tip": "Keep citrine in your cash register, wallet, or wealth corner (far left from your front door).",
    },
    "selenite": {
        "name": "Selenite",
        "magical_properties": ["cleansing", "clarity", "peace", "higher consciousness", "charging"],
        "element": "air",
        "planet": "moon",
        "chakra": "crown",
        "moon_phase": "full moon",
        "day": "monday",
        "deities": ["Selene", "Thoth"],
        "safety_notes": ["NEVER place in water; it will dissolve", "Very soft and fragile"],
        "pairs_with": ["clear quartz", "amethyst", "black tourmaline"],
        "beginner_tip": "Place other crystals on a selenite plate to cleanse and recharge them.",
    },
    "labradorite": {
        "name": "Labradorite",
        "magical_properties": ["transformation", "intuition", "protection", "magic", "psychic powers"],
        "element": "water",
        "planet": "uranus",
        "chakra": "third eye",
        "moon_phase": "full moon",
        "day": "wednesday",
        "deities": ["Aurora Borealis spirits", "Arianrhod"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["moonstone", "amethyst", "moldavite"],
        "beginner_tip": "Known as the Stone of Magic; excellent for anyone developing psychic abilities.",
    },
    "moonstone": {
        "name": "Moonstone",
        "magical_properties": ["intuition", "new beginnings", "moon magic", "fertility", "divination"],
        "element": "water",
        "planet": "moon",
        "chakra": "third eye",
        "moon_phase": "new moon",
        "day": "monday",
        "deities": ["Selene", "Diana", "Hecate", "Thoth"],
        "safety_notes": ["Safe to handle", "Relatively soft; store separately"],
        "pairs_with": ["selenite", "labradorite", "amethyst"],
        "beginner_tip": "Wear during the new moon to set intentions; charge under the full moon.",
    },
    "obsidian": {
        "name": "Obsidian",
        "magical_properties": ["protection", "truth", "grounding", "scrying", "banishing", "shadow work"],
        "element": "fire",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "dark moon",
        "day": "saturday",
        "deities": ["Tezcatlipoca", "Pele"],
        "safety_notes": ["Natural edges can be extremely sharp", "Handle polished specimens only"],
        "pairs_with": ["black tourmaline", "smoky quartz", "apache tear"],
        "beginner_tip": "An obsidian mirror or sphere is a powerful scrying tool. Start with an obsidian palm stone.",
    },
    "tiger's eye": {
        "name": "Tiger's Eye",
        "magical_properties": ["confidence", "courage", "protection", "willpower", "clarity", "prosperity"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "waxing moon",
        "day": "sunday",
        "deities": ["Ra", "Sekhmet"],
        "safety_notes": ["Safe to handle", "Contains asbestos fibers sealed in quartz; do not grind or inhale dust"],
        "pairs_with": ["citrine", "carnelian", "red jasper"],
        "beginner_tip": "Carry in your pocket before job interviews or difficult conversations for courage.",
    },
    "carnelian": {
        "name": "Carnelian",
        "magical_properties": ["creativity", "courage", "vitality", "motivation", "sexuality", "confidence"],
        "element": "fire",
        "planet": "sun",
        "chakra": "sacral",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Isis", "Sekhmet"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["citrine", "tiger's eye", "garnet"],
        "beginner_tip": "The ancient Egyptians called it the 'Stone of Courage.' Carry it to overcome creative blocks.",
    },
    "lapis lazuli": {
        "name": "Lapis Lazuli",
        "magical_properties": ["wisdom", "truth", "intuition", "communication", "royalty", "inner power"],
        "element": "water",
        "planet": "jupiter",
        "chakra": "throat",
        "moon_phase": "full moon",
        "day": "thursday",
        "deities": ["Isis", "Athena", "Venus", "Maat"],
        "safety_notes": ["Safe to handle", "Contains pyrite inclusions; do not use to make gem water"],
        "pairs_with": ["amethyst", "sodalite", "turquoise"],
        "beginner_tip": "Meditate with lapis on your throat to speak your truth and enhance communication.",
    },
    "malachite": {
        "name": "Malachite",
        "magical_properties": ["transformation", "protection", "healing", "prosperity", "heart opening"],
        "element": "earth",
        "planet": "venus",
        "chakra": "heart",
        "moon_phase": "full moon",
        "day": "friday",
        "deities": ["Venus", "Freya", "Hathor"],
        "safety_notes": ["TOXIC if ingested or inhaled as dust", "Do NOT make gem elixirs with malachite in water", "Handle polished specimens; wash hands after"],
        "pairs_with": ["rose quartz", "chrysocolla", "jade"],
        "beginner_tip": "A powerful transformation stone, but use polished pieces only and never ingest.",
    },
    "pyrite": {
        "name": "Pyrite",
        "magical_properties": ["prosperity", "abundance", "confidence", "protection", "luck"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "waxing moon",
        "day": "sunday",
        "deities": ["Sun deities"],
        "safety_notes": ["Contains sulfur; do NOT place in water", "Wash hands after handling"],
        "pairs_with": ["citrine", "tiger's eye", "green aventurine"],
        "beginner_tip": "Place on your desk or in your workspace to attract abundance and block negative energy.",
    },
    "fluorite": {
        "name": "Fluorite",
        "magical_properties": ["mental clarity", "focus", "protection", "learning", "decision-making"],
        "element": "air",
        "planet": "mercury",
        "chakra": "third eye",
        "moon_phase": "waxing moon",
        "day": "wednesday",
        "deities": ["Thoth", "Athena"],
        "safety_notes": ["Safe to handle", "Soft and fragile; store carefully"],
        "pairs_with": ["clear quartz", "amethyst", "sodalite"],
        "beginner_tip": "Keep on your study desk to sharpen mental focus and absorb new information.",
    },
    "smoky quartz": {
        "name": "Smoky Quartz",
        "magical_properties": ["grounding", "protection", "stress relief", "transmutation", "centering"],
        "element": "earth",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "saturday",
        "deities": ["Hecate", "Morrighan"],
        "safety_notes": ["Safe to handle", "Irradiated specimens are common; natural smoky quartz is preferable"],
        "pairs_with": ["black tourmaline", "hematite", "clear quartz"],
        "beginner_tip": "Hold after energy work to ground and release excess energy back to the earth.",
    },
    "amazonite": {
        "name": "Amazonite",
        "magical_properties": ["hope", "truth", "communication", "harmony", "courage"],
        "element": "water",
        "planet": "uranus",
        "chakra": "throat",
        "moon_phase": "waxing moon",
        "day": "wednesday",
        "deities": ["Amazon warriors", "Tiamat"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["turquoise", "sodalite", "moonstone"],
        "beginner_tip": "A stone of empowerment, especially for speaking difficult truths with grace.",
    },
    "garnet": {
        "name": "Garnet",
        "magical_properties": ["passion", "courage", "vitality", "love", "protection", "strength"],
        "element": "fire",
        "planet": "mars",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Persephone", "Sekhmet"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["carnelian", "ruby", "red jasper"],
        "beginner_tip": "Carry garnet for an energy boost and to inspire passionate commitment.",
    },
    "bloodstone": {
        "name": "Bloodstone",
        "magical_properties": ["courage", "vitality", "protection", "healing", "justice", "endurance"],
        "element": "fire",
        "planet": "mars",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Ares", "Mars"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["garnet", "red jasper", "carnelian"],
        "beginner_tip": "Warriors carried bloodstone into battle for courage and to staunch wounds.",
    },
    "jade": {
        "name": "Jade",
        "magical_properties": ["prosperity", "harmony", "longevity", "wisdom", "love", "luck"],
        "element": "earth",
        "planet": "venus",
        "chakra": "heart",
        "moon_phase": "waxing moon",
        "day": "friday",
        "deities": ["Kuan Yin", "Maat", "Buddha"],
        "safety_notes": ["Safe to handle", "Nephrite and jadeite are both called jade"],
        "pairs_with": ["aventurine", "malachite", "rose quartz"],
        "beginner_tip": "Jade has been treasured for thousands of years across cultures; carry for luck and longevity.",
    },
    "aventurine": {
        "name": "Aventurine",
        "magical_properties": ["luck", "prosperity", "optimism", "confidence", "heart healing"],
        "element": "earth",
        "planet": "mercury",
        "chakra": "heart",
        "moon_phase": "waxing moon",
        "day": "wednesday",
        "deities": [],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["citrine", "jade", "pyrite"],
        "beginner_tip": "Called the 'Gambler's Stone.' Carry one when you need a stroke of luck.",
    },
    "rhodonite": {
        "name": "Rhodonite",
        "magical_properties": ["emotional healing", "love", "compassion", "forgiveness", "self-worth"],
        "element": "earth",
        "planet": "venus",
        "chakra": "heart",
        "moon_phase": "full moon",
        "day": "friday",
        "deities": ["Aphrodite"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["rose quartz", "garnet", "malachite"],
        "beginner_tip": "Work with rhodonite to heal old emotional wounds before opening to new love.",
    },
    "sodalite": {
        "name": "Sodalite",
        "magical_properties": ["communication", "truth", "logic", "intuition", "calm"],
        "element": "water",
        "planet": "venus",
        "chakra": "throat",
        "moon_phase": "waxing moon",
        "day": "friday",
        "deities": ["Athena"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["lapis lazuli", "amethyst", "amazonite"],
        "beginner_tip": "Wear near your throat to communicate with clarity and confidence.",
    },
    "hematite": {
        "name": "Hematite",
        "magical_properties": ["grounding", "protection", "strength", "focus", "courage"],
        "element": "earth",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "saturday",
        "deities": ["Mars", "Ares"],
        "safety_notes": ["Safe to handle", "Will rust if left in water"],
        "pairs_with": ["black tourmaline", "smoky quartz", "obsidian"],
        "beginner_tip": "The most powerful grounding stone. Hold one in each hand to quickly center yourself.",
    },
    "turquoise": {
        "name": "Turquoise",
        "magical_properties": ["protection", "healing", "communication", "friendship", "travel safety"],
        "element": "air",
        "planet": "venus",
        "chakra": "throat",
        "moon_phase": "full moon",
        "day": "friday",
        "deities": ["Hathor", "Sky Father"],
        "safety_notes": ["Safe to handle", "Porous; avoid prolonged water exposure", "Many fakes on the market"],
        "pairs_with": ["lapis lazuli", "amazonite", "sodalite"],
        "beginner_tip": "One of the oldest protection stones. Indigenous traditions consider it deeply sacred.",
    },
    "amber": {
        "name": "Amber",
        "magical_properties": ["protection", "healing", "purification", "luck", "vitality"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "moon_phase": "any",
        "day": "sunday",
        "deities": ["Freya", "Apollo"],
        "safety_notes": ["Safe to handle", "Not technically a crystal; it is fossilized tree resin"],
        "pairs_with": ["jet", "citrine", "clear quartz"],
        "beginner_tip": "Amber and jet together are a traditional witch's necklace for power and protection.",
    },
    "aquamarine": {
        "name": "Aquamarine",
        "magical_properties": ["courage", "calm", "communication", "protection at sea", "clarity"],
        "element": "water",
        "planet": "moon",
        "chakra": "throat",
        "moon_phase": "full moon",
        "day": "monday",
        "deities": ["Poseidon", "Neptune", "sea deities"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["moonstone", "amethyst", "larimar"],
        "beginner_tip": "Sailors carried aquamarine for protection; carry it for courage during emotional storms.",
    },
    "onyx": {
        "name": "Onyx",
        "magical_properties": ["protection", "strength", "stamina", "self-control", "banishing"],
        "element": "earth",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "saturday",
        "deities": ["Mars"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["hematite", "obsidian", "black tourmaline"],
        "beginner_tip": "Wear during difficult times to bolster inner strength and resolve.",
    },
    "opal": {
        "name": "Opal",
        "magical_properties": ["intuition", "amplification", "inspiration", "emotional depth", "cosmic consciousness"],
        "element": "water",
        "planet": "venus",
        "chakra": "crown",
        "moon_phase": "full moon",
        "day": "friday",
        "deities": ["Cupid", "Ananke"],
        "safety_notes": ["Fragile; can crack in dry conditions", "Store with moisture"],
        "pairs_with": ["moonstone", "labradorite", "amethyst"],
        "beginner_tip": "Opal amplifies whatever emotions you carry. Work with it when you are in a positive state.",
    },
    "peridot": {
        "name": "Peridot",
        "magical_properties": ["prosperity", "protection", "health", "sleep", "compassion"],
        "element": "earth",
        "planet": "venus",
        "chakra": "heart",
        "moon_phase": "waxing moon",
        "day": "friday",
        "deities": ["Pele", "Isis"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["citrine", "jade", "aventurine"],
        "beginner_tip": "Called the 'Stone of the Sun' by the Egyptians. Wear for cheerful, abundant energy.",
    },
    "sunstone": {
        "name": "Sunstone",
        "magical_properties": ["joy", "vitality", "leadership", "confidence", "independence"],
        "element": "fire",
        "planet": "sun",
        "chakra": "sacral",
        "moon_phase": "waxing moon",
        "day": "sunday",
        "deities": ["Ra", "Helios"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["moonstone", "citrine", "carnelian"],
        "beginner_tip": "Pair sunstone with moonstone to balance solar and lunar energies.",
    },
    "chrysocolla": {
        "name": "Chrysocolla",
        "magical_properties": ["communication", "empowerment", "teaching", "goddess energy", "calm"],
        "element": "water",
        "planet": "venus",
        "chakra": "throat",
        "moon_phase": "full moon",
        "day": "friday",
        "deities": ["Sophia", "Kuan Yin"],
        "safety_notes": ["Contains copper; do NOT make gem water with it", "Handle polished specimens"],
        "pairs_with": ["turquoise", "malachite", "lapis lazuli"],
        "beginner_tip": "A powerful feminine-energy stone for teachers, counselors, and empaths.",
    },
    "lepidolite": {
        "name": "Lepidolite",
        "magical_properties": ["calm", "transition", "anxiety relief", "balance", "hope"],
        "element": "water",
        "planet": "jupiter",
        "chakra": "third eye",
        "moon_phase": "waning moon",
        "day": "thursday",
        "deities": [],
        "safety_notes": ["Contains lithium; do NOT make gem water", "Flakes easily"],
        "pairs_with": ["amethyst", "rose quartz", "kunzite"],
        "beginner_tip": "Naturally contains lithium. Hold it during anxious moments for calm.",
    },
    "howlite": {
        "name": "Howlite",
        "magical_properties": ["patience", "calm", "sleep", "awareness", "memory"],
        "element": "air",
        "planet": "moon",
        "chakra": "crown",
        "moon_phase": "waning moon",
        "day": "monday",
        "deities": [],
        "safety_notes": ["Safe to handle", "Often dyed to imitate turquoise"],
        "pairs_with": ["amethyst", "lepidolite", "blue lace agate"],
        "beginner_tip": "Place under your pillow for insomnia relief and calm sleep.",
    },
    "red jasper": {
        "name": "Red Jasper",
        "magical_properties": ["grounding", "stamina", "courage", "protection", "vitality"],
        "element": "fire",
        "planet": "mars",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "tuesday",
        "deities": ["Isis", "Bona Dea"],
        "safety_notes": ["Safe to handle"],
        "pairs_with": ["garnet", "bloodstone", "carnelian"],
        "beginner_tip": "Called the 'Supreme Nurturer.' Carry for sustained energy and endurance.",
    },
    "agate": {
        "name": "Agate",
        "magical_properties": ["balance", "grounding", "stability", "protection", "harmony"],
        "element": "earth",
        "planet": "mercury",
        "chakra": "root",
        "moon_phase": "waxing moon",
        "day": "wednesday",
        "deities": ["Gaia"],
        "safety_notes": ["Safe to handle", "Many varieties exist with additional properties"],
        "pairs_with": ["jasper", "aventurine", "smoky quartz"],
        "beginner_tip": "One of the oldest healing stones. Each color of agate adds specific properties.",
    },
    "apache tear": {
        "name": "Apache Tear",
        "magical_properties": ["grief healing", "protection", "grounding", "emotional release", "comfort"],
        "element": "fire",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "saturday",
        "deities": [],
        "safety_notes": ["Safe to handle", "A form of obsidian"],
        "pairs_with": ["obsidian", "smoky quartz", "rose quartz"],
        "beginner_tip": "Legend says it was formed from the tears of Apache women; carry during times of grief.",
    },
    "moldavite": {
        "name": "Moldavite",
        "magical_properties": ["transformation", "rapid change", "spiritual awakening", "star energy", "evolution"],
        "element": "fire",
        "planet": "uranus",
        "chakra": "heart",
        "moon_phase": "any",
        "day": "wednesday",
        "deities": [],
        "safety_notes": ["Many fakes on the market; buy from reputable sources", "Can cause intense reactions (dizziness, flushing); work with it gradually"],
        "pairs_with": ["black tourmaline", "smoky quartz", "hematite"],
        "beginner_tip": "A tektite formed by a meteorite impact. Work with grounding stones alongside it to stay balanced.",
    },
    "shungite": {
        "name": "Shungite",
        "magical_properties": ["purification", "protection", "grounding", "EMF shielding", "healing"],
        "element": "earth",
        "planet": "saturn",
        "chakra": "root",
        "moon_phase": "waning moon",
        "day": "saturday",
        "deities": [],
        "safety_notes": ["Safe to handle", "Can leave black residue on hands", "Only sourced from Karelia, Russia"],
        "pairs_with": ["black tourmaline", "hematite", "smoky quartz"],
        "beginner_tip": "Place near electronics for purification; used in water purification for centuries in Russia.",
    },
    "kyanite": {
        "name": "Kyanite",
        "magical_properties": ["alignment", "communication", "psychic ability", "truth", "meditation"],
        "element": "air",
        "planet": "mercury",
        "chakra": "throat",
        "moon_phase": "any",
        "day": "wednesday",
        "deities": ["Archangel Michael"],
        "safety_notes": ["Safe to handle", "Very fragile along cleavage planes"],
        "pairs_with": ["selenite", "amethyst", "labradorite"],
        "beginner_tip": "One of the few stones that never needs cleansing. It also aligns all chakras instantly.",
    },
}


# ---------------------------------------------------------------------------
# COLORS — 12 entries
# ---------------------------------------------------------------------------

COLORS = {
    "white": {
        "name": "White",
        "magical_properties": ["purification", "peace", "truth", "protection", "healing", "all-purpose"],
        "element": "all",
        "planet": "moon",
        "chakra": "crown",
        "candle_use": "Can substitute for any color. Purification, new beginnings, blessings, truth spells.",
        "pairs_with": ["silver", "blue", "purple"],
    },
    "black": {
        "name": "Black",
        "magical_properties": ["protection", "banishing", "binding", "absorption", "endings", "shadow work"],
        "element": "earth",
        "planet": "saturn",
        "chakra": "root",
        "candle_use": "Banishing, protection, absorbing negativity, breaking hexes, cord cutting.",
        "pairs_with": ["white", "red", "purple"],
    },
    "red": {
        "name": "Red",
        "magical_properties": ["passion", "courage", "strength", "willpower", "lust", "vitality"],
        "element": "fire",
        "planet": "mars",
        "chakra": "root",
        "candle_use": "Passion, courage, strength, sexual energy, conflict resolution, fast action.",
        "pairs_with": ["black", "orange", "gold"],
    },
    "pink": {
        "name": "Pink",
        "magical_properties": ["love", "romance", "friendship", "self-love", "emotional healing", "compassion"],
        "element": "water",
        "planet": "venus",
        "chakra": "heart",
        "candle_use": "Romantic love, friendship, self-care, nurturing, reconciliation, gentle healing.",
        "pairs_with": ["red", "white", "green"],
    },
    "orange": {
        "name": "Orange",
        "magical_properties": ["creativity", "joy", "success", "ambition", "energy", "attraction"],
        "element": "fire",
        "planet": "sun",
        "chakra": "sacral",
        "candle_use": "Creativity, career success, ambition, enthusiasm, opportunity, legal matters.",
        "pairs_with": ["yellow", "red", "gold"],
    },
    "yellow": {
        "name": "Yellow",
        "magical_properties": ["intellect", "communication", "confidence", "charm", "travel", "learning"],
        "element": "air",
        "planet": "mercury",
        "chakra": "solar plexus",
        "candle_use": "Study, mental clarity, communication, persuasion, travel, breaking mental blocks.",
        "pairs_with": ["orange", "gold", "white"],
    },
    "green": {
        "name": "Green",
        "magical_properties": ["prosperity", "growth", "fertility", "luck", "healing", "abundance"],
        "element": "earth",
        "planet": "venus",
        "chakra": "heart",
        "candle_use": "Money drawing, prosperity, fertility, growth, healing, employment, luck.",
        "pairs_with": ["gold", "brown", "white"],
    },
    "blue": {
        "name": "Blue",
        "magical_properties": ["healing", "peace", "communication", "wisdom", "truth", "patience"],
        "element": "water",
        "planet": "jupiter",
        "chakra": "throat",
        "candle_use": "Healing, peace, truth, meditation, dream work, communication, wisdom.",
        "pairs_with": ["white", "purple", "silver"],
    },
    "purple": {
        "name": "Purple",
        "magical_properties": ["spirituality", "psychic powers", "wisdom", "divination", "royalty", "power"],
        "element": "water",
        "planet": "jupiter",
        "chakra": "third eye",
        "candle_use": "Psychic development, divination, spiritual growth, power, ambition, justice.",
        "pairs_with": ["white", "silver", "blue"],
    },
    "silver": {
        "name": "Silver",
        "magical_properties": ["moon magic", "intuition", "dreams", "feminine energy", "psychic powers"],
        "element": "water",
        "planet": "moon",
        "chakra": "third eye",
        "candle_use": "Moon rituals, divination, astral travel, intuition, goddess work, reflection.",
        "pairs_with": ["white", "purple", "blue"],
    },
    "gold": {
        "name": "Gold",
        "magical_properties": ["wealth", "success", "power", "solar energy", "confidence", "masculine energy"],
        "element": "fire",
        "planet": "sun",
        "chakra": "solar plexus",
        "candle_use": "Wealth, success, achievement, solar rituals, god work, fame, luxury.",
        "pairs_with": ["green", "orange", "yellow"],
    },
    "brown": {
        "name": "Brown",
        "magical_properties": ["grounding", "stability", "home", "animals", "earth magic", "endurance"],
        "element": "earth",
        "planet": "saturn",
        "chakra": "root",
        "candle_use": "Grounding, home protection, animal magic, stability, material goals, court cases.",
        "pairs_with": ["green", "black", "gold"],
    },
}


# ---------------------------------------------------------------------------
# ELEMENTS — 5 entries
# ---------------------------------------------------------------------------

ELEMENTS = {
    "fire": {
        "name": "Fire",
        "direction": "south",
        "season": "summer",
        "time_of_day": "noon",
        "zodiac_signs": ["aries", "leo", "sagittarius"],
        "tools": ["athame", "wand", "candle", "sword"],
        "qualities": ["passion", "willpower", "courage", "transformation", "energy", "desire"],
        "colors": ["red", "orange", "gold"],
        "herbs": ["cinnamon", "ginger", "basil", "bay laurel", "rosemary"],
        "crystals": ["carnelian", "citrine", "garnet", "sunstone", "tiger's eye"],
    },
    "water": {
        "name": "Water",
        "direction": "west",
        "season": "autumn",
        "time_of_day": "dusk",
        "zodiac_signs": ["cancer", "scorpio", "pisces"],
        "tools": ["chalice", "cauldron", "bowl", "mirror"],
        "qualities": ["emotion", "intuition", "healing", "purification", "love", "dreams"],
        "colors": ["blue", "silver", "sea green"],
        "herbs": ["chamomile", "willow", "jasmine", "rose", "yarrow"],
        "crystals": ["amethyst", "aquamarine", "moonstone", "rose quartz", "lapis lazuli"],
    },
    "earth": {
        "name": "Earth",
        "direction": "north",
        "season": "winter",
        "time_of_day": "midnight",
        "zodiac_signs": ["taurus", "virgo", "capricorn"],
        "tools": ["pentacle", "salt", "stones", "crystals"],
        "qualities": ["stability", "prosperity", "grounding", "fertility", "strength", "endurance"],
        "colors": ["green", "brown", "black"],
        "herbs": ["patchouli", "mugwort", "vervain", "oak", "comfrey"],
        "crystals": ["jade", "aventurine", "hematite", "black tourmaline", "smoky quartz"],
    },
    "air": {
        "name": "Air",
        "direction": "east",
        "season": "spring",
        "time_of_day": "dawn",
        "zodiac_signs": ["gemini", "libra", "aquarius"],
        "tools": ["wand", "incense", "feather", "bell"],
        "qualities": ["intellect", "communication", "wisdom", "travel", "clarity", "inspiration"],
        "colors": ["yellow", "white", "pale blue"],
        "herbs": ["lavender", "mint", "sage", "star anise", "dandelion"],
        "crystals": ["fluorite", "selenite", "kyanite", "clear quartz", "turquoise"],
    },
    "spirit": {
        "name": "Spirit",
        "direction": "center",
        "season": "the wheel turning",
        "time_of_day": "the liminal hour",
        "zodiac_signs": [],
        "tools": ["self", "breath", "meditation", "ritual"],
        "qualities": ["unity", "transcendence", "divine connection", "transformation", "the void"],
        "colors": ["white", "purple", "iridescent"],
        "herbs": ["frankincense", "myrrh", "sandalwood"],
        "crystals": ["clear quartz", "moldavite", "selenite"],
    },
}


# ---------------------------------------------------------------------------
# PLANETS — 7 classical planets
# ---------------------------------------------------------------------------

PLANETS = {
    "sun": {
        "name": "Sun",
        "day": "sunday",
        "metal": "gold",
        "colors": ["gold", "yellow", "orange"],
        "herbs": ["rosemary", "chamomile", "bay laurel", "frankincense", "cinnamon", "cedar", "st. john's wort", "calendula"],
        "crystals": ["citrine", "sunstone", "tiger's eye", "amber", "pyrite", "clear quartz"],
        "magical_domains": ["success", "vitality", "confidence", "fame", "leadership", "health", "joy"],
        "zodiac_signs": ["leo"],
        "hour_sequence_position": 1,
    },
    "moon": {
        "name": "Moon",
        "day": "monday",
        "metal": "silver",
        "colors": ["silver", "white", "pale blue"],
        "herbs": ["mugwort", "jasmine", "willow", "lemon balm", "sandalwood", "myrrh"],
        "crystals": ["moonstone", "selenite", "aquamarine", "pearl", "opal"],
        "magical_domains": ["intuition", "dreams", "emotions", "fertility", "the subconscious", "psychic powers"],
        "zodiac_signs": ["cancer"],
        "hour_sequence_position": 4,
    },
    "mars": {
        "name": "Mars",
        "day": "tuesday",
        "metal": "iron",
        "colors": ["red", "scarlet", "black"],
        "herbs": ["basil", "nettle", "ginger", "turmeric", "pine", "wormwood", "holly"],
        "crystals": ["garnet", "bloodstone", "red jasper", "carnelian"],
        "magical_domains": ["courage", "strength", "conflict", "passion", "defense", "surgery", "vitality"],
        "zodiac_signs": ["aries", "scorpio"],
        "hour_sequence_position": 5,
    },
    "mercury": {
        "name": "Mercury",
        "day": "wednesday",
        "metal": "mercury (quicksilver)",
        "colors": ["yellow", "orange", "mixed colors"],
        "herbs": ["lavender", "mint", "mandrake", "star anise"],
        "crystals": ["fluorite", "agate", "aventurine", "kyanite"],
        "magical_domains": ["communication", "travel", "intellect", "commerce", "writing", "divination", "trickery"],
        "zodiac_signs": ["gemini", "virgo"],
        "hour_sequence_position": 3,
    },
    "jupiter": {
        "name": "Jupiter",
        "day": "thursday",
        "metal": "tin",
        "colors": ["blue", "purple", "royal blue"],
        "herbs": ["sage", "dandelion", "clove", "nutmeg", "star anise"],
        "crystals": ["amethyst", "lapis lazuli", "lepidolite", "turquoise"],
        "magical_domains": ["prosperity", "expansion", "luck", "justice", "wisdom", "generosity", "spirituality"],
        "zodiac_signs": ["sagittarius", "pisces"],
        "hour_sequence_position": 6,
    },
    "venus": {
        "name": "Venus",
        "day": "friday",
        "metal": "copper",
        "colors": ["green", "pink", "rose"],
        "herbs": ["rose", "thyme", "yarrow", "elderflower", "vervain", "birch", "valerian"],
        "crystals": ["rose quartz", "jade", "rhodonite", "chrysocolla", "malachite", "opal", "peridot"],
        "magical_domains": ["love", "beauty", "relationships", "art", "pleasure", "harmony", "fertility"],
        "zodiac_signs": ["taurus", "libra"],
        "hour_sequence_position": 2,
    },
    "saturn": {
        "name": "Saturn",
        "day": "saturday",
        "metal": "lead",
        "colors": ["black", "dark brown", "indigo"],
        "herbs": ["patchouli", "ivy", "comfrey", "belladonna", "hemlock", "henbane", "datura"],
        "crystals": ["black tourmaline", "obsidian", "onyx", "smoky quartz", "hematite", "shungite", "apache tear"],
        "magical_domains": ["banishing", "binding", "protection", "boundaries", "discipline", "endings", "karmic lessons"],
        "zodiac_signs": ["capricorn", "aquarius"],
        "hour_sequence_position": 7,
    },
}


# ---------------------------------------------------------------------------
# DAYS OF THE WEEK — 7 entries
# ---------------------------------------------------------------------------

DAYS_OF_WEEK = {
    "sunday": {
        "name": "Sunday",
        "planet": "sun",
        "element": "fire",
        "colors": ["gold", "yellow", "orange"],
        "herbs": ["rosemary", "frankincense", "chamomile", "bay laurel", "cinnamon", "cedar"],
        "crystals": ["citrine", "sunstone", "tiger's eye", "amber", "clear quartz"],
        "best_for": ["success", "vitality", "confidence", "health", "joy", "leadership", "fame", "personal power"],
        "avoid": ["banishing", "binding", "shadow work"],
    },
    "monday": {
        "name": "Monday",
        "planet": "moon",
        "element": "water",
        "colors": ["silver", "white", "pale blue", "lavender"],
        "herbs": ["mugwort", "jasmine", "willow", "lemon balm", "sandalwood", "myrrh"],
        "crystals": ["moonstone", "selenite", "aquamarine", "opal"],
        "best_for": ["intuition", "dreams", "emotions", "fertility", "psychic work", "divination", "home", "family"],
        "avoid": ["aggressive magic", "conflict", "competitive workings"],
    },
    "tuesday": {
        "name": "Tuesday",
        "planet": "mars",
        "element": "fire",
        "colors": ["red", "scarlet", "orange", "black"],
        "herbs": ["basil", "nettle", "ginger", "pine", "holly", "turmeric"],
        "crystals": ["garnet", "bloodstone", "red jasper", "carnelian"],
        "best_for": ["courage", "strength", "protection", "defense", "passion", "competition", "surgery", "breaking obstacles"],
        "avoid": ["love spells", "peace magic", "reconciliation"],
    },
    "wednesday": {
        "name": "Wednesday",
        "planet": "mercury",
        "element": "air",
        "colors": ["yellow", "orange", "purple", "mixed"],
        "herbs": ["lavender", "mint", "mandrake", "star anise"],
        "crystals": ["fluorite", "agate", "aventurine", "kyanite"],
        "best_for": ["communication", "travel", "study", "writing", "divination", "commerce", "networking", "mental clarity"],
        "avoid": ["long-term stability work", "slow-growth magic"],
    },
    "thursday": {
        "name": "Thursday",
        "planet": "jupiter",
        "element": "fire",
        "colors": ["blue", "purple", "royal blue", "green"],
        "herbs": ["sage", "dandelion", "clove", "nutmeg", "star anise"],
        "crystals": ["amethyst", "lapis lazuli", "lepidolite", "turquoise"],
        "best_for": ["prosperity", "expansion", "luck", "justice", "legal matters", "generosity", "wisdom", "abundance"],
        "avoid": ["banishing", "reduction", "endings"],
    },
    "friday": {
        "name": "Friday",
        "planet": "venus",
        "element": "water",
        "colors": ["green", "pink", "rose", "copper"],
        "herbs": ["rose", "thyme", "yarrow", "elderflower", "vervain", "birch", "valerian"],
        "crystals": ["rose quartz", "jade", "rhodonite", "chrysocolla", "malachite"],
        "best_for": ["love", "romance", "beauty", "art", "friendship", "pleasure", "fertility", "harmony"],
        "avoid": ["conflict magic", "separation work", "banishing"],
    },
    "saturday": {
        "name": "Saturday",
        "planet": "saturn",
        "element": "earth",
        "colors": ["black", "dark brown", "indigo", "dark purple"],
        "herbs": ["patchouli", "ivy", "comfrey"],
        "crystals": ["black tourmaline", "obsidian", "onyx", "smoky quartz", "hematite"],
        "best_for": ["banishing", "binding", "protection", "boundaries", "endings", "discipline", "karmic work", "shadow work"],
        "avoid": ["new beginnings", "attraction magic", "celebration"],
    },
}


# ---------------------------------------------------------------------------
# NUMBERS — 1 through 13
# ---------------------------------------------------------------------------

NUMBERS = {
    1: {
        "number": 1,
        "meaning": "Beginnings, independence, self, leadership, initiation, the seed",
        "planet": "sun",
        "element": "fire",
        "keywords": ["new starts", "individuality", "willpower", "creation", "unity"],
    },
    2: {
        "number": 2,
        "meaning": "Partnership, balance, duality, receptivity, cooperation",
        "planet": "moon",
        "element": "water",
        "keywords": ["polarity", "intuition", "harmony", "diplomacy", "patience"],
    },
    3: {
        "number": 3,
        "meaning": "Creativity, expression, growth, the Triple Goddess, manifestation",
        "planet": "jupiter",
        "element": "fire",
        "keywords": ["creativity", "joy", "communication", "expansion", "trinities"],
    },
    4: {
        "number": 4,
        "meaning": "Stability, foundations, the four elements, structure, earth",
        "planet": "saturn",
        "element": "earth",
        "keywords": ["foundations", "structure", "order", "hard work", "the elements"],
    },
    5: {
        "number": 5,
        "meaning": "Change, freedom, the five senses, the pentagram, adventure",
        "planet": "mercury",
        "element": "air",
        "keywords": ["change", "freedom", "travel", "versatility", "the pentacle"],
    },
    6: {
        "number": 6,
        "meaning": "Harmony, love, nurturing, home, responsibility, balance",
        "planet": "venus",
        "element": "water",
        "keywords": ["love", "family", "harmony", "service", "beauty"],
    },
    7: {
        "number": 7,
        "meaning": "Spirituality, mystery, introspection, wisdom, the seven planets",
        "planet": "moon",
        "element": "water",
        "keywords": ["mysticism", "intuition", "solitude", "wisdom", "the sacred"],
    },
    8: {
        "number": 8,
        "meaning": "Power, abundance, karma, infinity, cycles, regeneration",
        "planet": "saturn",
        "element": "earth",
        "keywords": ["abundance", "power", "cycles", "justice", "karmic balance"],
    },
    9: {
        "number": 9,
        "meaning": "Completion, wisdom, humanitarianism, spiritual mastery, endings",
        "planet": "mars",
        "element": "fire",
        "keywords": ["completion", "mastery", "service", "endings", "transformation"],
    },
    10: {
        "number": 10,
        "meaning": "Completion and renewal, wholeness, return to the beginning at a higher level",
        "planet": "sun",
        "element": "fire",
        "keywords": ["cycles", "completion", "perfection", "renewal", "totality"],
    },
    11: {
        "number": 11,
        "meaning": "Mastery, intuition, illumination, spiritual insight, a master number",
        "planet": "moon",
        "element": "spirit",
        "keywords": ["mastery", "vision", "inspiration", "channeling", "gateway"],
    },
    12: {
        "number": 12,
        "meaning": "Cosmic order, completion of cycles, the zodiac, months, wholeness",
        "planet": "jupiter",
        "element": "all",
        "keywords": ["zodiac", "cosmic order", "fulfillment", "celestial harmony", "the wheel"],
    },
    13: {
        "number": 13,
        "meaning": "Transformation, death-and-rebirth, the lunar months, the Goddess, witchcraft",
        "planet": "moon",
        "element": "water",
        "keywords": ["transformation", "rebirth", "lunar power", "the Goddess", "the witch's number"],
    },
}


# ---------------------------------------------------------------------------
# INTENTION MAP — maps intention keywords to correspondences
# ---------------------------------------------------------------------------

INTENTION_MAP = {
    "protection": {
        "herbs": ["sage", "rosemary", "cedar", "juniper", "basil", "nettle", "bay laurel", "frankincense"],
        "crystals": ["black tourmaline", "obsidian", "smoky quartz", "onyx", "hematite", "amber", "apache tear"],
        "colors": ["black", "white", "red"],
        "element": "fire",
        "planet": "mars",
        "day": "tuesday",
        "moon_phase": "waning moon",
    },
    "love": {
        "herbs": ["rose", "jasmine", "lavender", "yarrow", "basil", "thyme", "vervain", "lemon balm"],
        "crystals": ["rose quartz", "rhodonite", "garnet", "jade", "moonstone", "malachite"],
        "colors": ["pink", "red", "green"],
        "element": "water",
        "planet": "venus",
        "day": "friday",
        "moon_phase": "waxing moon",
    },
    "prosperity": {
        "herbs": ["basil", "cinnamon", "mint", "chamomile", "dandelion", "patchouli", "bay laurel", "nutmeg", "clove"],
        "crystals": ["citrine", "pyrite", "jade", "aventurine", "tiger's eye", "peridot"],
        "colors": ["green", "gold"],
        "element": "earth",
        "planet": "jupiter",
        "day": "thursday",
        "moon_phase": "waxing moon",
    },
    "healing": {
        "herbs": ["lavender", "chamomile", "rosemary", "calendula", "echinacea", "lemon balm", "comfrey", "thyme"],
        "crystals": ["amethyst", "clear quartz", "rose quartz", "turquoise", "aventurine", "amber"],
        "colors": ["blue", "green", "white"],
        "element": "water",
        "planet": "moon",
        "day": "monday",
        "moon_phase": "full moon",
    },
    "divination": {
        "herbs": ["mugwort", "bay laurel", "wormwood", "star anise", "yarrow", "dandelion", "frankincense"],
        "crystals": ["amethyst", "labradorite", "moonstone", "obsidian", "fluorite", "lapis lazuli", "kyanite"],
        "colors": ["purple", "silver", "blue"],
        "element": "water",
        "planet": "moon",
        "day": "monday",
        "moon_phase": "full moon",
    },
    "banishing": {
        "herbs": ["sage", "cedar", "rosemary", "juniper", "frankincense", "clove", "nettle", "pine"],
        "crystals": ["obsidian", "black tourmaline", "smoky quartz", "onyx", "hematite", "apache tear"],
        "colors": ["black", "white"],
        "element": "fire",
        "planet": "saturn",
        "day": "saturday",
        "moon_phase": "waning moon",
    },
    "cleansing": {
        "herbs": ["sage", "rosemary", "cedar", "lavender", "frankincense", "juniper", "pine", "thyme"],
        "crystals": ["selenite", "clear quartz", "kyanite", "amethyst", "smoky quartz"],
        "colors": ["white", "blue"],
        "element": "air",
        "planet": "moon",
        "day": "monday",
        "moon_phase": "waning moon",
    },
    "creativity": {
        "herbs": ["cinnamon", "basil", "mint", "bay laurel", "birch", "ginger"],
        "crystals": ["carnelian", "citrine", "sunstone", "fluorite", "opal", "labradorite"],
        "colors": ["orange", "yellow", "gold"],
        "element": "fire",
        "planet": "sun",
        "day": "sunday",
        "moon_phase": "waxing moon",
    },
    "wisdom": {
        "herbs": ["sage", "rosemary", "frankincense", "bay laurel", "star anise", "mugwort"],
        "crystals": ["lapis lazuli", "amethyst", "fluorite", "sodalite", "kyanite"],
        "colors": ["purple", "blue", "silver"],
        "element": "water",
        "planet": "jupiter",
        "day": "thursday",
        "moon_phase": "full moon",
    },
    "confidence": {
        "herbs": ["cinnamon", "ginger", "basil", "bay laurel", "rosemary", "calendula"],
        "crystals": ["tiger's eye", "carnelian", "citrine", "sunstone", "pyrite", "garnet"],
        "colors": ["gold", "orange", "red", "yellow"],
        "element": "fire",
        "planet": "sun",
        "day": "sunday",
        "moon_phase": "waxing moon",
    },
    "communication": {
        "herbs": ["lavender", "mint", "bay laurel", "star anise", "sage"],
        "crystals": ["sodalite", "lapis lazuli", "amazonite", "turquoise", "kyanite", "fluorite"],
        "colors": ["blue", "yellow"],
        "element": "air",
        "planet": "mercury",
        "day": "wednesday",
        "moon_phase": "waxing moon",
    },
    "grounding": {
        "herbs": ["patchouli", "mugwort", "oak", "comfrey", "cedar", "pine", "nettle"],
        "crystals": ["hematite", "smoky quartz", "black tourmaline", "obsidian", "red jasper", "shungite", "agate"],
        "colors": ["brown", "black", "green"],
        "element": "earth",
        "planet": "saturn",
        "day": "saturday",
        "moon_phase": "waning moon",
    },
    "transformation": {
        "herbs": ["wormwood", "mugwort", "frankincense", "myrrh", "mandrake", "birch"],
        "crystals": ["moldavite", "obsidian", "labradorite", "malachite", "amethyst", "apache tear"],
        "colors": ["purple", "black", "silver"],
        "element": "fire",
        "planet": "saturn",
        "day": "saturday",
        "moon_phase": "dark moon",
    },
    "peace": {
        "herbs": ["lavender", "chamomile", "lemon balm", "valerian", "rose", "elderflower", "thyme"],
        "crystals": ["amethyst", "selenite", "lepidolite", "howlite", "aquamarine", "blue lace agate"],
        "colors": ["white", "blue", "silver", "pink"],
        "element": "water",
        "planet": "moon",
        "day": "monday",
        "moon_phase": "full moon",
    },
    "courage": {
        "herbs": ["ginger", "basil", "nettle", "thyme", "rosemary", "cinnamon", "oak"],
        "crystals": ["garnet", "bloodstone", "carnelian", "red jasper", "tiger's eye", "aquamarine"],
        "colors": ["red", "orange", "gold"],
        "element": "fire",
        "planet": "mars",
        "day": "tuesday",
        "moon_phase": "waxing moon",
    },
}


# ---------------------------------------------------------------------------
# HELPER FUNCTIONS
# ---------------------------------------------------------------------------


def get_herb(name: str) -> dict | None:
    """Retrieve an herb entry by name (case-insensitive).

    Args:
        name: The common name of the herb.

    Returns:
        The herb dictionary, or None if not found.
    """
    return HERBS.get(name.lower().strip())


def get_crystal(name: str) -> dict | None:
    """Retrieve a crystal entry by name (case-insensitive).

    Args:
        name: The common name of the crystal.

    Returns:
        The crystal dictionary, or None if not found.
    """
    return CRYSTALS.get(name.lower().strip())


def get_color(name: str) -> dict | None:
    """Retrieve a color entry by name (case-insensitive).

    Args:
        name: The color name.

    Returns:
        The color dictionary, or None if not found.
    """
    return COLORS.get(name.lower().strip())


def get_element(name: str) -> dict | None:
    """Retrieve an element entry by name (case-insensitive).

    Args:
        name: The element name (fire, water, earth, air, spirit).

    Returns:
        The element dictionary, or None if not found.
    """
    return ELEMENTS.get(name.lower().strip())


def get_planet(name: str) -> dict | None:
    """Retrieve a planet entry by name (case-insensitive).

    Args:
        name: The planet name (sun, moon, mars, mercury, jupiter, venus, saturn).

    Returns:
        The planet dictionary, or None if not found.
    """
    return PLANETS.get(name.lower().strip())


def get_correspondences_for_intention(intention: str) -> dict:
    """Find matching correspondences for a given magical intention.

    Performs a fuzzy lookup by checking if the intention string contains
    any of the known intention keywords, then aggregates all matches.

    Args:
        intention: A free-text intention string, e.g. "protection and healing"
            or "love spell" or "I want prosperity and confidence".

    Returns:
        A dict with keys: herbs, crystals, colors, elements, planets, days,
        moon_phases. Each value is a deduplicated list. Returns empty lists
        if no intentions match.
    """
    intention_lower = intention.lower().strip()

    matched_herbs: list[str] = []
    matched_crystals: list[str] = []
    matched_colors: list[str] = []
    matched_elements: list[str] = []
    matched_planets: list[str] = []
    matched_days: list[str] = []
    matched_moon_phases: list[str] = []

    for keyword, correspondences in INTENTION_MAP.items():
        if keyword in intention_lower:
            matched_herbs.extend(correspondences.get("herbs", []))
            matched_crystals.extend(correspondences.get("crystals", []))
            matched_colors.extend(correspondences.get("colors", []))
            el = correspondences.get("element")
            if el:
                matched_elements.append(el)
            pl = correspondences.get("planet")
            if pl:
                matched_planets.append(pl)
            dy = correspondences.get("day")
            if dy:
                matched_days.append(dy)
            mp = correspondences.get("moon_phase")
            if mp:
                matched_moon_phases.append(mp)

    # Deduplicate while preserving order
    def _dedup(seq: list) -> list:
        seen = set()
        result = []
        for item in seq:
            if item not in seen:
                seen.add(item)
                result.append(item)
        return result

    return {
        "herbs": _dedup(matched_herbs),
        "crystals": _dedup(matched_crystals),
        "colors": _dedup(matched_colors),
        "elements": _dedup(matched_elements),
        "planets": _dedup(matched_planets),
        "days": _dedup(matched_days),
        "moon_phases": _dedup(matched_moon_phases),
    }
